### PR TITLE
feat: Add dedicated tgeo module splitter for ITk

### PR DESCRIPTION
**Pull request by niermann999**
Introduces a splitter class for ITk TGeo modules that contains a splitting method for barrel and disc modules. The splitting method and number of segments is determined by a simple sensor name map in json format.

TODO: Correct coordinate systems (annulus bounds)?

### CODE REVIEW

**Comment by niermann999** [comment]
ITk-Barrel_split
ITk-Disc_split

**Comment by niermann999** [comment]
ITk_disc_split_custom

**Comment by paulgessinger** [comment]
Ah, I just noticed in your screenshots from the barrel layers that the sensors are rotated by 90 degrees, or that the splitting is done in the wrong direction. The strips should be oriented parallel to z, not perpendicular.

**Comment by niermann999** [comment]
ITk_barrel_split_x

**Comment by asalzburger** [comment]
Hi @niermann999  - we have merge conflicts, can you fix them - this looks already great!

**Comment by paulgessinger** [comment]
Marking this WIP again until #884 is merged.

**Pull request closed without merging**
