### PR TITLE
fix: Use correct conversion from JSON to Material

### PR DESCRIPTION
**Pull request by beomki-yeo**
Two lines in `MaterialJsonConverter.cpp` of Json plugins showed the following compile error:
`call of overloaded ‘Material(const value_type&)’ is ambiguous`

Looks like "at" method of json objects causes the ambiguity issue, so I changed it to "get" method to resolve it (suggested by @paulgessinger)

### CODE REVIEW

**Comment by paulgessinger** [comment]
In principle this looks fine, but the material conversion unit tests seem to fail. Could you have a look?

**Comment by beomki-yeo** [comment]
it is fixed now

**Comment by asalzburger** [comment]
Updating - @Corentin-Allaire  - can you review, please?

**Review by Corentin-Allaire — APPROVED** [review]
Looks good to me

**Pull request merged**
