### PR TITLE
refactor!: Use `consteval` on `hashString`

### PR DESCRIPTION
**Pull request by paulgessinger**
This allows us to enforce in more places that the hash is calculated at compile time. To make the distinction explicit, I'm adding another function whose name indicates that the hash will be computed at runtime.

BREAKING CHANGES:

The `hashString` function becomes `consteval`, so requires compile-time execution. Use this if at all possible! If not, switch to `hashStringDynamic`, which remains `constexpr` and can thus be executed at runtime.

### CODE REVIEW

**Review by andiwand — DISMISSED** [review]

**Comment by andiwand** [comment]
Is this breaking @paulgessinger ?

**Comment by paulgessinger** [comment]
@andiwand probably. I'm hoping switching the custom literal from `consteval` back to `constexpr` fixes the linking error.

**Comment by paulgessinger** [comment]
Can we get this in @andiwand?

**Review by andiwand — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [387d0ade9229f95b5b91b103d462e61d83a14e1e]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46170783) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/8542220)!

**Pull request merged**
