### PR TITLE
feat: Add ConstRefHolder type, add support to TrackContainer

### PR DESCRIPTION
**Pull request by paulgessinger**
This allows construction of `TrackContainer` from const references.

### CODE REVIEW

**Review by EdwardMoyse — APPROVED** [review]
Looks good to me.

**Comment by paulgessinger** [comment]
Compiler segfault... nice.

**Comment by paulgessinger** [comment]
Ok I had to drop the `explicit` from `ValueHolder` and go back to using implicit construction of the holders in the constructor arguments. This is not ideal, but at least the `ValueHolder` constructor is not as wide open as the reference or const reference one. Let's see if the CI agrees with me.

**Comment by paulgessinger** [comment]
Segfault is gone, can you reapprove @EdwardMoyse ?

**Review by EdwardMoyse — COMMENTED** [review]
Looks good

**Review by EdwardMoyse — APPROVED** [review]

**Pull request merged**
