### PR TITLE
Add missing acts namespace in AnnealingUtility

### PR DESCRIPTION
**Pull request by baschlag**
Adds missing acts namespace in AnnealingUtility

### CODE REVIEW

**Comment by asalzburger** [comment]
@paulgessinger what's the `codecov` report problem here?

**Comment by HadrienG2** [comment]
Isn't that the one that #69 is expected to fix once merged?

**Comment by paulgessinger** [comment]
Exactly.

**Comment by paulgessinger** [comment]
Ok, #69 went in, @baschlag can you rebase?

**Comment by baschlag** [comment]
Rebase done @paulgessinger.

**Comment by baschlag** [comment]
@paulgessinger This tool is being used but within the ```Acts::``` namespace, so I can still use it without changing anything.

**Comment by paulgessinger** [comment]
So there’s no test? Or is that in the namespace as well?

**Comment by baschlag** [comment]
https://github.com/acts-project/acts/blob/master/Tests/UnitTests/Core/Utilities/AnnealingUtilityTests.cpp

In the namespace as well.

**Pull request merged**
