### PR TITLE
test: Enable interaction in `truth_tracking_kalman.py`

### PR DESCRIPTION
**Pull request by beomki-yeo**
This PR enables the material interaction in `truth_tracking_kalman`.
I did some case studies and I will let others judge which configuration (eta, momentum) is the best.

Case 1 (main)
Default momentum config
Eta: -2:2
No interaction

)

Case2 (This PR)
Default momentum config
Eta: -2:2
Yes interaction

)

Case3 
10 GeV
Eta: -2:2
Yes interaction

))

Case4 
10 GeV
Eta: 0:0
Yes interaction

)))

### CODE REVIEW

**Comment by beomki-yeo** [comment]
There is a (nagative) shift even for zero eta case - I think it is because b field is orthogonal to the particle direction which makes a curvature in the track.

**Comment by benjaminhuth** [comment]
Is this OpenDataDetector or GenericDetector?

**Comment by beomki-yeo** [comment]
It is OOD because the plots were generated by `physmon.py`

**Review by andiwand — APPROVED** [review]
I believe this is safe to merge because the fitter is already using interactions

if we want to check w/o interactions we should do this for sim and reco

**Comment by andiwand** [comment]
@beomki-yeo can you update the reference data?

**Comment by beomki-yeo** [comment]
Will do this by the end of the day

**Comment by beomki-yeo** [comment]
It's updated but there was a hiccup in Mac - someone can run it again?

**Review by andiwand — APPROVED** [review]

**Comment by beomki-yeo** [comment]
@andiwand  Do you know what this is about? The error came from `linux_examples_test`

```
Run /usr/local/bin/geant4-config --install-datasets && source /usr/local/bin/thisroot.sh && source /usr/local/bin/thisdd4hep_only.sh && source /usr/local/bin/geant4.sh && source build/python/setup.sh && export LD_LIBRARY_PATH=$PWD/build/thirdparty/OpenDataDetector/factory:$LD_LIBRARY_PATH && pip3 install -r Examples/Python/tests/requirements.txt && pytest -rFsv -v
+ created download cache
+ downloading G4NDL.4.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    55  100    55    0     0     78      0 --:--:-- --:--:-- --:--:--    78

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   228  100   228    0     0    149      0  0:00:01  0:00:01 --:--:--   489

100   191  100   191    0     0    115      0  0:00:01  0:00:01 --:--:--   115
+ checking md5 of G4NDL.4.6.tar.gz
- md5 mismatch for 'G4NDL.4.6.tar.gz' : 8f388d08d9de80d8255e1762d8b81d58(actual) != d07e43499f607e01f2c1ce06d7a09f3e(expected)
+ cleaned download cache
- dataset installation failed
Error: Process completed with exit code 1.
```

**Comment by andiwand** [comment]
never seen that before. I restarted the runs in hope that is was a random failure

**Comment by beomki-yeo** [comment]
The error is still there :/

**Comment by beomki-yeo** [comment]
Yeah it also exists in #2009

**Comment by andiwand** [comment]
looks like all the cern data links are broken atm :smile:

**Comment by andiwand** [comment]
https://github.com/acts-project/acts/pull/2011 should fix the issue

**Comment by andiwand** [comment]
@beomki-yeo there seems to be one more problem with physmon ref data. can you take a look?

**Comment by beomki-yeo** [comment]
All red flags come from truth_tracking.html You can take a look here:
https://drive.google.com/file/d/1yg--C8I93MKtuS7EbTHigg1joFKi4KxI/view?usp=share_link

**Comment by paulgessinger** [comment]
Or here: https://herald.harbinger.gessinger.dev/view/acts-project/acts/629830569/truth_tracking.html

**Comment by beomki-yeo** [comment]
@paulgessinger Am I also able to get the link? Genereting html is a drag

**Comment by andiwand** [comment]
@beomki-yeo I think you can get it from this one https://github.com/acts-project/acts/pull/1990#issuecomment-1483807206

there is a reference file for the kalman truth tracking in `CI/physmon/reference`. can you update it with the one the CI spits out?

**Comment by paulgessinger** [comment]
@andiwand can you reapprove after the added force push?

**Review by andiwand — APPROVED** [review]

**Comment by andiwand** [comment]
huch I thought I did already

**Pull request merged**
