### PR TITLE
fix: Fix CKF finalization

### PR DESCRIPTION
**Pull request by andiwand**
Apparently our CKF was not able to smooth multiple tracks for a single seed in some cases. The problem was that we expected the CKF actor to be called a second time after the first smoothing was done but there is a Stepper step in between which could kick you out of the detector because the step length is basically unconstrained.

fixes
- https://github.com/acts-project/acts/issues/1484

### CODE REVIEW

**Comment by andiwand** [comment]
@timadye if you could test this and/or have a look at the changes it would be great!

**Comment by timadye** [comment]
> @timadye if you could test this and/or have a look at the changes it would be great!

Sure, let me update my build and I'll give it a go. I'm hoping for great things! :grin:

**Comment by timadye** [comment]
Hi @andiwand,

This is a ***HUGE*** improvement!

I tested with `full_chain_itk.py` for 100 `ttbar_pu200` events, and saw the following changes:
1. All the ~3428/event `TrackFinding ERROR` messages are gone.
2. Previously 15% of seeds failed in `TrackFindingAlgorithm`. Now it is exactly 0 seeds failing.
3. The `CKFPerforman` tracking efficiency is increased from 90.0 &rarr; 97.2%. At |&eta;| ~ 2.1 it dropped to 69%, now it is 96.4% (no drop).
4. The job was ~24% slower. I guess much of the extra time is due to successfully processing more seeds.
5. There are still a few remaining `ERROR` and `WARNING` messages, but now at the level of ~11/event (not ~3428/event!). These messages (including the FPE) were all there before, so this doesn't speak against this fix. Here are typical remaining messages prefixed by the message count for 100 events:
```
1097 Propagator     ERROR     Step failed with MagneticFieldError:1: Interpolation out of bounds was requested
  26 Propagator     WARNING   Field lookup was unsuccessful, this is very likely an error
1097 FatrasSimula   ERROR     event 75 particle id=4567375009546240(1|58|221|0|0)|pdg=pi+|q=1|m=0.13957|p=52.5121 failed to simulate with error MagneticFieldError:1: Interpolation out of bounds was requested
   1 Sequencer      ERROR     Encountered 1 unmasked FPEs
```

Apart from the increase in CPU time, this is all extremely positive.  I hope this fix can be merged.

Thanks,
Tim.

**Comment by CarloVarni** [comment]
one silly question: how is it this PR is not chancing performances in the tests but it is for the ITk script? What am I missing?

**Comment by CarloVarni** [comment]
oh right, I forgot that paul's PR that adds ttbar test is not in yet. Thanks @andiwand  . I'd say we can proceed with this then

**Review by CarloVarni — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results
### :white_check_mark: All tests successful

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023743) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023742) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023741) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023740) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsTrkSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023739) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023738) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023737) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023736) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023735) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023734) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023733) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023732) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023731) |
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023730) |
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023729) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023728) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31023727) |

**Pull request merged**
