### PR TITLE
refactor!: Remove momentum and charge from track parameters

### PR DESCRIPTION
**Pull request by andiwand**
I noticed that charge and momentum leak through various places in our source code. These quantities are based on the single charge hypothesis during reconstruction. The use of these quantities is sometimes not necessary and even if, we should make the hypothesis more explicit.

In this PR I
- remove the momentum and charge from the track parameters
- remove the charge hypothesis and the momentum and charge accessors from the stepper
- remove charge template and rename `Single*TrackParameter` to `*TrackParameter`
- add the absolute charge hypothesis to the propagator options, along the mass hypothesis
- add utility functions to get charge and momentum based on the hypothesis
- handle all the downstream changes

### CODE REVIEW

**Comment by paulgessinger** [comment]
Wouldn't a rename of the typedef over singly charged be more efficient? Also do we really want to fully bake in singly charged particles only?

**Comment by andiwand** [comment]
> Wouldn't a rename of the typedef over singly charged be more efficient? Also do we really want to fully bake in singly charged particles only?

probably this would be less invasive but I feel like the `momentum` and `charge` properties should not be there in the first place and "single" charged can be dropped in this case which simplifies a lot of stuff

happy to discuss these changes and alternative solutions!

**Comment by andiwand** [comment]
TODO for me

```
2023-06-05T14:28:46.9255730Z The following tests FAILED:
2023-06-05T14:28:46.9256150Z 	 24 - BoundTrackParameters (Failed)
2023-06-05T14:28:46.9256360Z 	 26 - CurvilinearTrackParameters (Failed)
2023-06-05T14:28:46.9256560Z 	 27 - FreeTrackParameters (Failed)
2023-06-05T14:28:46.9256730Z 	105 - AtlasStepper (Failed)
2023-06-05T14:28:46.9256900Z 	115 - LoopProtection (Failed)
2023-06-05T14:28:46.9257060Z 	120 - Stepper (Failed)
2023-06-05T14:28:46.9257240Z 	121 - StraightLineStepper (Failed)
2023-06-05T14:28:46.9257440Z 	122 - VolumeMaterialInteraction (Failed)
```

**Comment by andiwand** [comment]
closing as superseded by https://github.com/acts-project/acts/pull/2181

**Pull request closed without merging**
