### PR TITLE
ci: Add automated tracking of build performance values

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR adds some plumbing to enable tracking of the build performance jobs. It runs on main only, and pushes the results to `acts-project/metrics`. This then triggers a CI job there which runs the report generation and posts it on github pages: https://acts-project.github.io/metrics/

### CODE REVIEW

**Comment by asalzburger** [comment]
I really like this, that's an excellent addition to the project.

**Comment by paulgessinger** [comment]
The whole system is extensible, so we should be able to add things like unit test execution times, or even physics parameters without a ton of work.

**Comment by HadrienG2** [comment]
As mentioned already in the chat, this is a **great** idea. Huge thanks for finding the time to do this!

Here are a couple of comments and suggestions:

- Try to adjust the horizontal scale so that not every date is printed. The current output is already hard to read, and the situation will degrade further as the project ages.
- I see that there is a second plot called "perf-tracking", which I assume is meant to track the performance of pull requests (in this case the current one). The problem is that the plot is not readable when there is only one data point. I think it might be possible to improve upon this by switching to a different kind of display, such as a plain "current PR consumption" without historical data (do we really need it ?), but with a color-coded delta wrt main. Or, if we care about PR history, maybe switch to a line-and-markers plot size, which is readable even when the time series only has one data point ?
- If you could use any help from my side in order to integrate benchmark timings into this, feel free to ping me!

**Comment by paulgessinger** [comment]
Hey @HadrienG2:

> Here are a couple of comments and suggestions:
> 
>     * Try to adjust the horizontal scale so that not every date is printed. The current output is already hard to read, and the situation will degrade further as the project ages.

It should only plot the last 100 commits. That number is hardcoded right now, but could be made configurable. I also want to move to a JS based interactive plot anyway, so this matplotlib plot is an interim solution anyway.

>     * I see that there is a second plot called "perf-tracking", which I assume is meant to track the performance of pull requests (in this case the current one). The problem is that the plot is not readable when there is only one data point. I think it might be possible to improve upon this by switching to a different kind of display, such as a plain "current PR consumption" without historical data (do we really need it ?), but with a color-coded delta wrt main. Or, if we care about PR history, maybe switch to a line-and-markers plot size, which is readable even when the time series only has one data point ?

This is because `perf-tracking` is the branch I tested the CI on in my fork over on `paulgesinger/acts`. The plot should indicate this, but the heading might not be clear enough. I intend to only run this on `main` in this repo, so once this here is merged, further data points should be appended to the `main` plot. I'll manually remove the single data point from `perf-tracking`.

>     * If you could use any help from my side in order to integrate benchmark timings into this, feel free to ping me!

Definitely! We'll have to reshuffle the CI jobs to some extent so that we're able to pass artifacts from the benchmark job into the metric collector job, but that should be doable.

**Review by HadrienG2 — APPROVED** [review]

**Comment by paulgessinger** [comment]
Maybe a final comment here: I did my due diligence testing the CI bits over on my fork, but as you're all aware, developing / debugging CI jobs is finicky business, so there is a chance this won't work right away after merging, in which case I'll have to fix it.

**Pull request merged**
