### PR TITLE
refactor: Remove globalToLocal log and return actual error message

### PR DESCRIPTION
**Pull request by osbornjd**
This is a very simple PR to change this logging message from `FATAL` level to `WARNING`. This is leftover from when the `globalToLocal` function did not return an `Acts::Result`, so if the transformation failed it was actually fatal. This result can now be passed and caught, thus it isn't necessary to flag it as `FATAL`.

### CODE REVIEW

**Comment by paulgessinger** [comment]
Should the function not return the error in this case? The way I read the code now, it will just try to continue after the `WARNING`.

**Comment by osbornjd** [comment]
> Should the function not return the error in this case? The way I read the code now, it will just try to continue after the `WARNING`.

Ha, good point... this really must be leftover then from when this piece of code just threw a `FATAL` log and then crashed. I'll change it to not log anything and instead return the error message similar to the track parameters.

**Comment by paulgessinger** [comment]
Sounds good. Can you maybe adjust the PR title to reflect the updated nature of the changes?

**Comment by osbornjd** [comment]
> Sounds good. Can you maybe adjust the PR title and descriptions to reflect the updated nature of the changes? Aside from that lgtm.

Sure, done.

**Review by paulgessinger — APPROVED** [review]

**Pull request merged**
