### PR TITLE
build: Set TBB as required in CMake

### LINKED ISSUE #504: Check for tbb version is required.
The builds on CentOS7 with devtoolset-9 (gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC))  fail due to outdated tbb on this platform tbb-4.1-9.20130314.el7.x86_64
However this tbb is accepted by the cmake.

The error is

```
[ 74%] Building CXX object Examples/Framework/CMakeFiles/ActsExamplesFramework.dir/src/Framework/Sequencer.cpp.o
+ cd /home/user/Projects/ACTS/build/Examples/Framework
+ /opt/rh/devtoolset-9/root/usr/bin/c++ '-DACTS_CORE_IDENTIFIER_PLUGIN="/home/user/Projects/ACTS/acts/Examples/Framework/include/ActsExamples/EventData/SimIdentifier.hpp"' -DActsExamplesFramework_EXPORTS -DBOOST_FILESYSTEM_NO_DEPRECATED -I/home/user/Projects/ACTS/acts/Examples/Framework/include -I/home/user/Projects/ACTS/acts/Core/include -I/home/user/Projects/ACTS/build/Core -I/home/user/Projects/ACTS/acts/Fatras/include -I/home/user/Projects/ACTS/acts/thirdparty/dfelibs -isystem /usr/include/boost169 -isystem /usr/include/eigen3 -isystem /usr/include/root -DR__HAS_STD_STRING_VIEW=1 -Wall -Wextra -Wpedantic -Wshadow -Wunused-local-typedefs -O2 -g -DNDEBUG -fPIC -std=gnu++17 -o CMakeFiles/ActsExamplesFramework.dir/src/Framework/Sequencer.cpp.o -c /home/user/Projects/ACTS/acts/Examples/Framework/src/Framework/Sequencer.cpp
In file included from /usr/include/tbb/enumerable_thread_specific.h:32,
                 from /usr/include/tbb/combinable.h:32,
                 from /usr/include/tbb/tbb.h:49,
                 from /home/user/Projects/ACTS/acts/Examples/Framework/src/Framework/Sequencer.cpp:40:
/usr/include/tbb/concurrent_vector.h: In member function ‘tbb::concurrent_vector<T, A>::iterator tbb::concurrent_vector<T, A>::grow_by(tbb::concurrent_vector<T, A>::size_type)’:
/usr/include/tbb/concurrent_vector.h:667:38: error: operands to ?: have different types ‘tbb::internal::concurrent_vector_base_v3::size_type’ {aka ‘long unsigned int’} and ‘tbb::atomic<long unsigned int>’
  667 |         return iterator(*this, delta ? internal_grow_by( delta, sizeof(T), &initialize_array, NULL ) : my_early_size);
      |                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tbb/concurrent_vector.h:667:38: note:   and each type can be converted to the other
/usr/include/tbb/concurrent_vector.h: In member function ‘tbb::concurrent_vector<T, A>::iterator tbb::concurrent_vector<T, A>::grow_by(tbb::concurrent_vector<T, A>::size_type, tbb::concurrent_vector<T, A>::const_reference)’:
/usr/include/tbb/concurrent_vector.h:680:38: error: operands to ?: have different types ‘tbb::internal::concurrent_vector_base_v3::size_type’ {aka ‘long unsigned int’} and ‘tbb::atomic<long unsigned int>’
  680 |         return iterator(*this, delta ? internal_grow_by( delta, sizeof(T), &initialize_array_by, static_cast<const void*>(&t) ) : my_early_size);
      |                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tbb/concurrent_vector.h:680:38: note:   and each type can be converted to the other
make[2]: *** [Examples/Framework/CMakeFiles/ActsExamplesFramework.dir/src/Framework/Sequencer.cpp.o] Error 1
make[1]: *** [Examples/Framework/CMakeFiles/ActsExamplesFramework.dir/all] Error 2
make: *** [all] Error 2

```

Best regards,
Andrii

### PR DESCRIPTION
**Pull request by paulgessinger**
We previously didn't mark the `find_package` call for TBB as `REQUIRED` which I believe was what was reported in #504.
I think this should resolve #504. 

@andriish, do you have any input here?

### CODE REVIEW

**Review by HadrienG2 — APPROVED** [review]

**Comment by andriish** [comment]
Hi @paulgessinger ,

that was long time ago, I don't even have that system around anymore.
But well, if the packages is required, it should be marked so.

Best regards,

Andrii

**Comment by paulgessinger** [comment]
Hm, so on CentOS7 / LCG97 it appears like CMake cannot find TBB via a `Config.cmake` file. Setting it to `REQUIRED` makes it fail there, and not try the `FindTBB.cmake` version. The latter does not support a version restriction.

What's the best solution here?

**Comment by HadrienG2** [comment]
I guess restricting the change to newer Linux systems or LCG releases might be the best course of action?

**Comment by paulgessinger** [comment]
I guess, we probably also should include some newer LCG versions, actually.

**Comment by andriish** [comment]
The cleanest solution, as for me, is just to provide own FindTBB is there is a need to support old releases without TBB cmake configs.

**Comment by paulgessinger** [comment]
We do ship a `FindTBB.cmake`, but as far as I see it, with `FindTBB.cmake` we can't require a specific version of TBB.

**Comment by andriish** [comment]
> we can't require a specific version of TBB.

Adding version determination to FindTBB?

**Comment by paulgessinger** [comment]
Hm, I think I would probably prefer not to maintain "our" `FindTBB.cmake`. Would you be willing to add a PR that does it, @andriish ?

**Comment by andriish** [comment]
>Own FindTBB

https://github.com/Kitware/VTK/blob/master/CMake/FindTBB.cmake
Should do the job

> Merge request

I'm not a user of ACTS, just helped a colleague at some point with the integration and now trying to close the issues where I was involved.

**Comment by paulgessinger** [comment]
Ok I pulled the updates w.r.t to the file you linked, and added the version to the module based `find_package`. I'm not entirely sure if this now locks down the version requirement, but I would argue this is good enough for now.

**Comment by paulgessinger** [comment]
@HadrienG2 could you reapprove?

**Review by HadrienG2 — APPROVED** [review]

**Pull request merged**
