### PR TITLE
feat: Adding features for sorting space points in r in (phi, z) grid

### PR DESCRIPTION
**Pull request by noemina**
This PR includes two features for sorting space points in radius for each (phi, z) grid bin.
- A new parameter, `binSizeR`, is added to the `SeedFinderConfig` in order to allow the user to configure the bin size in R. By default it stays 1 mm.
- A new boolean, `forceRadialSorting`, is added to the `SeedFinderConfig` in order to allow the user to force the space point in each (phi, z) bin to be sorted in radius. This is false by default.

### CODE REVIEW

**Comment by noemina** [comment]
FYI: @LuisFelipeCoelho

**Comment by LuisFelipeCoelho** [comment]
Good from my side

**Review by robertlangenberg — COMMENTED** [review]
is the sorting taken advantage of somewhere?

**Comment by noemina** [comment]
> is the sorting taken advantage of somewhere?

We (ATLAS seeder) have use cases profiting of both options implemented in this PR.

**Review by robertlangenberg — COMMENTED** [review]
I'm confused.. I thought I had already commented a question where the sorting is used? was this a similar PR?

**Review by robertlangenberg — APPROVED** [review]

**Pull request merged**
