### PR TITLE
feat: material composition analysis

### PR DESCRIPTION
**Pull request by asalzburger**
This PR adds an analysis script and associated executable that allows to inspect the material composition of a detector.
It also corrects a spelling mistake in the `Scripts` directory, from `MaterialMaping` to `MaterialMapping`.

### CODE REVIEW

**Comment by asalzburger** [comment]
Ping @Corentin-Allaire

**Review by Corentin-Allaire — COMMENTED** [review]
Sorry for the delay ! If I understand correctly this create histograms showing the contribution in X0 and L0 of every single element in the detector ? That looks good
Do you think you could write a few lines about it in the `run_material_mapping` how to ? Also if possible update that how to to have the correct path for the old script (now that you have fixed my spelling mistake...)

**Comment by asalzburger** [comment]
> Sorry for the delay ! If I understand correctly this create histograms showing the contribution in X0 and L0 of every single element in the detector ? That looks good
> Do you think you could write a few lines about it in the `run_material_mapping` how to ? Also if possible update that how to to have the correct path for the old script (now that you have fixed my spelling mistake...)

That's a good idea, yes, indeed - I will update the description.

**Comment by asalzburger** [comment]
@Corentin-Allaire - none of the AnalysisApps have yet a documentation, I fixed the `MaterialMapping` spelling in the docs for this one, and will open a new PR that adds documentation for the `AnalysisApps` altogether.

The reason for this is, I would like to decouple those from the actual running how-to-dos. Do you agree?

**Comment by Corentin-Allaire** [comment]
@asalzburger I think this is a good idea ! But I think you forgot to push the change to the doc in your branch ? As soon as you can do that I can approve this.

**Comment by asalzburger** [comment]
> @asalzburger I think this is a good idea ! But I think you forgot to push the change to the doc in your branch ? As soon as you can do that I can approve this.

Absolutely right, done now.

**Review by Corentin-Allaire — APPROVED** [review]

**Pull request merged**
