### PR TITLE
feat: ProxyAccessor constructor can now be constexpr

### PR DESCRIPTION
**Pull request by timadye**
Since C++20 supports `constexpr std::string`, we can make `ProxyAccessorBase(const std::string& _key)` constructor `constexpr`.

### CODE REVIEW

**Comment by timadye** [comment]
> Makes sense. There's one unit test failure on macOS related to an unused variable.

So the warning is [here](https://github.com/acts-project/acts/blob/main/Tests/UnitTests/Core/EventData/TrackContainerComplianceTests.cpp#L77):
```
/Users/runner/work/acts/acts/build/Tests/UnitTests/Core/EventData/TrackContainerComplianceTests.cpp:77:36: error: unused variable 'caccNMeasuements' [-Werror,-Wunused-variable]
  ConstProxyAccessor<unsigned int> caccNMeasuements("nMeasurements");
```
Indeed, that variable is not used, because it is just used to check that you can't modify through a `ConstProxyAccessor`. I don't understand why this warning wasn't always there, and only appears now this constructor is `constexpr`.

That aside, do you have any ideas on how to fix this?

**Comment by paulgessinger** [comment]
In principle there should be a fix for this already. Maybe it's not merged yet

**Comment by timadye** [comment]
@AJPfleger I think this is waiting for your approval, if you do approve. Thanks!

**Review by AJPfleger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/45695015) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/8468781)!

**Pull request merged**
