### PR TITLE
feat(examples): Add/use a concrete Index type for containers. (EDM rework part 2b/4)

### PR DESCRIPTION
**Pull request by msmk0**
Add a `Index` typeded to be used to identify indices into edm containers. The `IndexMultimap<...>` container is updated to always use this type as its key instead of being templated on it.

### CODE REVIEW

**Comment by msmk0** [comment]
@baschlag Could you have a look since you are using the examples EDM quite a bit?

**Review by baschlag — APPROVED** [review]
Looks good to me, no objections.

**Comment by paulgessinger** [comment]
FYI this got merged without the prefix in the message.

**Comment by msmk0** [comment]
@paulgessinger We should really see if there is a bot that automatically sets the commit message and the body from the PR title and description. I have the feeling that this is filled once, but changes to the PR title might not be reflected if you merge it.

**Comment by paulgessinger** [comment]
I just double check when clicking the button.

**Comment by msmk0** [comment]
Yes, I try to do that, too.

**Pull request merged**
