### PR TITLE
ci: Physics performance monitoring

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR introduces a set of "physics" monitoring CI jobs based on histogram comparisons. 
Currently this runs

- CKF truth estimated
- CKF truth smeared
- CKF seeded
- truth tracking

I intend to run this for a bit and see how it behaves. If it works well, we should extend it to cover other areas as well.

### CODE REVIEW

**Comment by paulgessinger** [comment]
Test

**Comment by paulgessinger** [comment]
I think this is good to go now.

**Comment by paulgessinger** [comment]
@asalzburger @robertlangenberg can we get this in? I think it would help #1188 as well as #1181.

**Review by robertlangenberg — APPROVED** [review]
Very clean, nice. We can adjust the thresholds as we go if they're too tight or too loose.

**Pull request merged**
