### PR TITLE
fix: Added missing return to seedfinder::CreateSeedsForGroup

### PR DESCRIPTION
**Pull request by guilhermeAlmeida1**
Added missing return at the end of non-void function seedfinder::CreateSeedsForGroup.

### CODE REVIEW

**Review by LuisFelipeCoelho — APPROVED** [review]

**Comment by paulgessinger** [comment]
Hmm. Codecov seems to be MIA.

**Comment by paulgessinger** [comment]
There we go.

**Comment by andiwand** [comment]
@paulgessinger is this something we can catch with clang tidy?

**Comment by paulgessinger** [comment]
I guess `-Wreturn-type` in the compilation would already do it.

**Pull request merged**
