### PR TITLE
fix: Resolve compile errors of Autodiff Plugin caused by PR  #569

### PR DESCRIPTION
**Pull request by benjaminhuth**
This PR updates the Autodiff-Plugin, since it is dependent on the internal data layout of the `StepperState`, which was changed in PR #569.

PS: I'm not sure how this works internally, but shouldn't such things be catched by the CI? Or does this not apply for Plugins?

### CODE REVIEW

**Comment by paulgessinger** [comment]
It should, but the AutoDiff plugin is currently not included in the CI jobs. Maybe we can discuss how to make that happen? In principle the dependency is bundled, right? So we'd just have to enable it, I suppose.

**Comment by benjaminhuth** [comment]
Yes, the autodiff library is bundled in the thirdparty folder.

**Comment by benjaminhuth** [comment]
Okay, the changes that should resolve all `-Wunsused-parameter` warnings are merged into autodiff, and the last commit updates the bundled version of autodiff to this newest version. 
Therefore, this can go in I think, except there are any concerns about the changes.

**Comment by paulgessinger** [comment]
Other than the warning, it did compile in my CI branch, so I'm approving this.

**Review by paulgessinger — APPROVED** [review]

**Comment by paulgessinger** [comment]
@benjaminhuth can you bump autodiff to `v0.5.12` also for the `find_program` call in the root `CMakeLists.txt`?

**Comment by benjaminhuth** [comment]
I think thats not so easy, because they (the autodiff maintainers) did not update the version in autodiff's `CMakeLists.txt`, they just released a new version in github...
On the other hand, is that really necessary? v0.5.11 contains all features needed for Acts, so if somebody has a v0.5.11 system installation of autodiff, this should work fine...

**Comment by paulgessinger** [comment]
Right, I guess it'll print the warnings, but that shouldn't matter... Ok let's mege this then.

**Pull request merged**
