### PR TITLE
fix(Fatras): Fix process filtering in InteractionList

### PR DESCRIPTION
**Pull request by msmk0**
The process filtering into continuous and point-like interactions in the `InteractionList` did not work if the process member functions are templated on the generator type. This PR fixes the selection and update the corresponding test to match the actual physics process implementations.

### CODE REVIEW

**Comment by msmk0** [comment]
@paulgessinger This is a followup to #719. This implementation error showed up when trying to update #722. It would be nice if this could go in as soon as possible.

**Review by robertlangenberg — APPROVED** [review]
My comments were already answered on !722, so this can go in, unless @paulgessinger has objections

**Comment by paulgessinger** [comment]
I don't see anything problematic.

**Comment by msmk0** [comment]
@paulgessinger @robertlangenberg Could one of you merge this then?

**Pull request merged**
