### PR TITLE
refactor: Split `GainMatrixUpdater` compilation

### PR DESCRIPTION
**Pull request by paulgessinger**
Once again, our compilation memory usage is out of control, among others due to `GainMatrixUpdater`. This currently takes about 1.2G peak memory.

In this PR, I'm moving the function doing the heavy instantiation back into a header, but I'm suppressing the instantiation of the template via `extern template`.

Then, I have CMake generate `.cpp` files where each file instantiates one dimension. The linker ultimately resolves these separate template insantiations.

Now, this is a bit ugly, but it does reduce **peak** memory consumption to under 600M, at the cost of now having 6 instead of one compilation unit:

```
[   16.73M, max:   295.39M] [    1.63s] - Core/src/TrackFitting/GainMatrixUpdater.cpp
[   16.58M, max:   431.10M] [    2.95s] - build/Core/src/TrackFitting/GainMatrixUpdaterImpl1.cpp
[   16.58M, max:   456.64M] [    3.13s] - build/Core/src/TrackFitting/GainMatrixUpdaterImpl2.cpp
[   17.06M, max:   485.18M] [    3.40s] - build/Core/src/TrackFitting/GainMatrixUpdaterImpl3.cpp
[   16.86M, max:   456.70M] [    3.24s] - build/Core/src/TrackFitting/GainMatrixUpdaterImpl4.cpp
[   16.58M, max:   568.34M] [    4.37s] - build/Core/src/TrackFitting/GainMatrixUpdaterImpl5.cpp
[   16.73M, max:   537.15M] [    4.11s] - build/Core/src/TrackFitting/GainMatrixUpdaterImpl6.cpp
```

Not sure this is the way to go, but I wanted to suggest it.

### CODE REVIEW

**Comment by paulgessinger** [comment]
@andiwand The generated source files are only in the build folder, not in the source folder at all. In terms of where exactly the template function is, I don't have a preference. We'd have to include it the `.cpp` file, but it doesn't matter where it is.

**Comment by andiwand** [comment]
Maybe we can just put it directly into the `GainMatrixUpdater.cpp`

**Comment by paulgessinger** [comment]
@andiwand And then include the `.cpp` file? Always feels weird to me.

**Comment by andiwand** [comment]
Right it really should be a header file. I would put it rather in `detail` to box the template and only show it to the source file. But it is only a slight preference on my side

**Comment by paulgessinger** [comment]
Done now @andiwand.

**Review by andiwand — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [ea794f29899a2ced13e4f477ca9437ab6f16cce9]
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7894028)!

|status|job|report|
|------|---|------|
|:green_circle: | [report_pull_request](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096653)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096652)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096651)||
|:green_circle: | [test_ActsDumpGeometryIdentifiers](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096650)||
|:red_circle: | [test_ActsCheckObjectCountsCachedWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096649)||
|:red_circle: | [test_ActsCheckObjectCountsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096648)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096647)||
|:green_circle: | [test_ActsPersistifySeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096646)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096645)||
|:green_circle: | [test_ActsAnalogueClustering](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096644)||
|:green_circle: | [test_ActsWorkflowHeavyIons](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096643)||
|:green_circle: | [test_ActsWorkflowFastTracking](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096642)||
|:green_circle: | [test_ActsWorkflowCached](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096641)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096640)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096639)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096638)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096637)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096636)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096635)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096634)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096633)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096632)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096631)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096630)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096629)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096628)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096627)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096626)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096625)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096624)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096623)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096622)||
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42096621)||

**Pull request merged**
