### PR TITLE
perf: Use MBF smoother by default in `TrackHelpers` in Examples track finding

### PR DESCRIPTION
**Pull request by andiwand**
Making the MBF smoother default in the Examples track finding after https://github.com/acts-project/acts/pull/3420

### CODE REVIEW

**Comment by paulgessinger** [comment]
Did this have a significant impact on performance?

**Comment by andiwand** [comment]
> Did this have a significant impact on performance?

I measured a speedup of `2.56` which does not really effect the overall track finding performance because we only spend about 1% of the time in the smoothing step. I measured that with ODD and Fatras so it might have a bigger impact with full sim and ITk. Since we do not loose anything be using this I thought it makes sense to use it as a default.

Interestingly it seems to shift some outlier tracks which is why physmon fails. Some of the pT outliers are shuffled around but I think those where outliers in the first place.

**Comment by paulgessinger** [comment]
My only argument against this is that it's nice to have the straight up 1:1 Frühwirth smoothing as the default, since it's readily available in literature.

**Comment by andiwand** [comment]
> My only argument against this is that it's nice to have the straight up 1:1 Frühwirth smoothing as the default, since it's readily available in literature.

Good point - maybe it makes more sense to use it per default in the Examples then?

**Review by paulgessinger — COMMENTED** [review]
No objections. Would we be testing / monitoring the gain matrix smoother anywhere? Might be nice to avoid decay.

**Pull request closed without merging**
