### PR TITLE
refactor!: Rename MaterialProperties to MaterialSlab

### LINKED ISSUE #29: Material class names are misleading
[GitLab issue: #671](https://gitlab.cern.ch/acts/acts-core/issues/671)

`Material` defines the material properties for a material of undefined dimensions while `MaterialProperties` defines a block/slab/slice of a concrete material.

Suggestion: rename `MaterialProperties` to `MaterialSlab`.

### PR DESCRIPTION
**Pull request by Corentin-Allaire**
As mentioned in #29 the name `MaterialProperties` is misleading since the material properties are contained in `Material`. This PR thus renames it to `MaterialSlab` since it represents material properties associated with a thickness.

Fixes #29.

### CODE REVIEW

**Comment by asalzburger** [comment]
Is this ready to be reviewed?

If you could do a rebase, I think we can move ahead with this.

**Review by asalzburger — APPROVED** [review]
Straight-forward renaming.

**Comment by asalzburger** [comment]
I will update the branch with the web-interface

**Comment by asalzburger** [comment]
Waiting for CI to run, then this can be merged.

**Comment by Corentin-Allaire** [comment]
Thanks

**Comment by asalzburger** [comment]
This can just squash and merge afterwards (no rebasing necessary), as master only diverged marginally

**Pull request merged**
