### PR TITLE
docs: Enable sphinx linkcheck build in CI

### PR DESCRIPTION
**Pull request by paulgessinger**

### CODE REVIEW

**Comment by paulgessinger** [comment]
Let's see if this works.

**Comment by paulgessinger** [comment]
I think it's more basic, the way I add the argument to the command in cmake escapes the space, so it doesn't parse it correctly.

**Comment by paulgessinger** [comment]
I fixed the invocation I think, and also found an actual broken link! Can you check this again @benjaminhuth?

**Review by benjaminhuth — APPROVED** [review]
Very cool, the tool seems to work!

**Pull request merged**
