### PR TITLE
fix: globalToLocal failure for some truth hits

### LINKED ISSUE #440: Truth fitting fails due to `globalToLocal` failure
The truth fitting fails with the reported error of `globalToLocal` transform failure during the hit smearing.
There is a tiny shift of the truth hit position written into the Csv file from the original position provided by the `stepper`. This shift could makes the truth hit out of surface and it could be arising from those following aspects:
1. The material interaction during the simulation [here](https://github.com/acts-project/acts/blob/0c56a3e4f31355891908ff150f282519fff0b120/Fatras/include/ActsFatras/Kernel/detail/Interactor.hpp#L141)
2. The truth hit position in the `TruthHitData` has a `float` precision
3. The Csv planar cluster writer has a limited precision

@msmk0 @asalzburger , should we just skip those truth hits which are numerically out of surface then?

### PR DESCRIPTION
**Pull request by XiaocongAi**
This increases the tolerance for the global-to-local transformation when reading data from file using the `PlanarClusterCsvReader`.

This PR closes #440 .

### CODE REVIEW

**Comment by msmk0** [comment]
@XiaocongAi As discussed in the meeting, I will wait for you to do a few more tests regarding the fraction of invalid hits.

**Comment by XiaocongAi** [comment]
Hi @msmk0 , here is some statistics. I ran the following two truth fitting tests:

- 10k single muon, eta=[-2.5, 2.5], pt = [0.1, 100] GeV/c. The number of `globalToLocal` failure W (W/O) changing the `TrackMLData` from `float` to `double` is 1 (149);
- 1 ttbar at pileup =200. The number of `globalToLocal` failure W(W/O) changing the `float` to `double` is 5(258).

The reason for the large fraction of failure when using `float` is because we lose some precision [here](https://github.com/acts-project/acts/blob/master/Examples/Io/Csv/src/CsvPlanarClusterWriter.cpp#L111) when going from a `double` position to a `float` one. By writing the truth hit out and read in again, we lose more precision, but this is really not so much after using `double`. 

You're right, we could get around of this by tuning the tolerance for `globalToLocal` from default 0.1 um to 0.5 um. So I revert the change to the cluster writer and tune the tolerance instead. But do you think we need to change from `float` to `double` still? Even without this change, we could still have successful `globalToLocal` with the 0.5 um tolerance.

**Comment by XiaocongAi** [comment]
Hi @msmk0 , it's only two lines changes for `globalToLocal` tolerance now. We should be safe for the moment.

**Review by msmk0 — APPROVED** [review]
@XiaocongAi Looks good. I will merge it.

**Comment by msmk0** [comment]
@XiaocongAi Just for your information: I updated the PR description to match the reduced content and fixed the closing keywords to #440 get closed automatically.

**Pull request merged**
