### PR TITLE
feat: Alignment centralization

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR reworks the `AlignedDetector` and the `PayloadDetector`. 
It rationalizes this to **one** `AlignedDetector`, which can be configured to do the alignment either internally (like previous `AlignedDetector`) or externally (like previous `PayloadDetector`). The logic that steers this largely lives in the alignment context decorators. The `AlignedDetector` does relatively little, other than setting up the decorator and passing through the options.

I also implemented garbage collection for the IOVs in flight, and in order to make that work, had to introduce some additional locking.

I did some testing on the alignment that the geometry receives with propagation tests, and it seems to me they are consistent between internal and external:

fig_external
fig_internal

I think those look fine, but let me know what you think.

I also made some quick plots of the memory usage over time with and without the GC (you can turn that off via command line option now):

plot

### CODE REVIEW

**Comment by paulgessinger** [comment]
@asalzburger could you have a look at this?

**Review by asalzburger — APPROVED** [review]
Happy with that one, could not find anything that would request change.

**Comment by paulgessinger** [comment]
@asalzburger I had to rebase and make slight adjustments after the python bindings were merged. Can you reapprove?

**Comment by asalzburger** [comment]
I had approved that already, so this should go in.

**Pull request merged**
