### PR TITLE
feat: add useTime to AMVFinder + python binding

### PR DESCRIPTION
**Pull request by felix-russo**
Enables time seeding and time impact point estimation for `AMVF (+grid seeder) seeded`!

For  `AMVF (+grid seeder) ttbar` the performance is deteriorating because the parameters of `AdaptiveGridDensityVertexFinder` were tuned for  `AMVF (+grid seeder) seeded`. The parameters for ttbar will be tuned once #2745 went in (at the moment, the grid seeder is templated to the grid size so we can't adapt these parameters at run time).

In the following, we will discuss the physmon for  `AMVF (+grid seeder) seeded`:

We get some sensible pulls for the vertex time:
image

Also, the vertex time residual looks good:
image

Using the additional coordinate we are able to resolve more vertices:
image
At the same time, we don't overshoot (i.e., reconstruct more vertices than there are) as this plot nicely shows.

Finally, we are able to better resolve which track corresponds to which vertex:
image

Some remarks:
Even though we reconstruct more vertices, the number of entries in the histogram of the vertex covariance seems to decrease: 
image
However, this is not actually the case: the tail of the monitored distribution just gets longer.

For higher pile-ups, we expect the improvement to be even more significant.

### CODE REVIEW

**Review by andiwand — DISMISSED** [review]
looks good :+1: 

time is default off so Athena should be fine right?

I think this is ready to merge then @paulgessinger

**Comment by felix-russo** [comment]
Let's us run the athena tests to be sure (the changes in `AdaptiveMultiVertexFinder.ipp` might affect it). Can you trigger the tests? @paulgessinger?

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [4e5b59dac09dadb4eb6a30c7d13144cc45617dea]
### :white_check_mark: All tests successful

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513385) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsBenchmarkWithSpot.sh 8 100](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513384) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513383) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateAmbiguityResolution.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513382) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateResolvedTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513381) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513380) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513379) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513378) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513377) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513376) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513375) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513374) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsGSFRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513373) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513372) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513371) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513370) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513369) |
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513368) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513367) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513366) |
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513365) |
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34513364) |

**Review by andiwand — APPROVED** [review]

**Comment by paulgessinger** [comment]
Athena seems fine!

**Pull request merged**
