### PR TITLE
feat: Make Grid bin count accessible with and without over/underflow bins

### PR DESCRIPTION
**Pull request by beomki-yeo**
@paulgessinger
This is for using Acts Grid in traccc.

traccc [PR35](https://github.com/acts-project/traccc/pull/35) 
traccc [PR46](https://github.com/acts-project/traccc/pull/46)

### CODE REVIEW

**Comment by beomki-yeo** [comment]
BTW, the purpose of modification for returning the total number of bins in spacepoint grid

**Comment by beomki-yeo** [comment]
@paulgessinger Can you review this MR at  your earilest convenience? There is a reason that I want it to be merged asap

**Review by paulgessinger — APPROVED** [review]
LGTM. 

I'd probably call the argument `includeUnderOverFlow`, and put it into the doxygen string, but not critically important.

**Comment by paulgessinger** [comment]
Doc failure should be #876

**Pull request merged**
