### PR TITLE
refactor!: Reset navigation state in (C)KF

### PR DESCRIPTION
**Pull request by XiaocongAi**
This PR simplifies the reset of the navigation state to enable the navigation to start from a new surface with provided position and momentum. It requires the `Navigator` `State` struct has a method `reset`.

### CODE REVIEW

**Comment by paulgessinger** [comment]
Hmmm. Maybe this should just be constructing a new navigator instance and replacing the previous one with it? Having a long list of values being reset by a method seems a bit brittle to me, to be honest. It also requires maintaining two spots for all the defaults and initial values.

**Comment by XiaocongAi** [comment]
Hi @asalzburger , do you have time still to have a look?

**Comment by asalzburger** [comment]
@paulgessinger  - we have a doc build failure here, do you know why?

**Comment by paulgessinger** [comment]
Yes, I changed it so that the doc build fails if Doxygen produces a warning. The warning is

```
/__w/acts/acts/Core/include/Acts/Propagator/DirectNavigator.hpp:123: error: argument 'geoContext' of command @param is not found in the argument list of Acts::DirectNavigator::State::reset(const GeometryContext &, const Vector3 &, const Vector3 &, const NavigationDirection, const Surface *ssurface, const Surface *tsurface) (warning treated as error, aborting now)
```

**Comment by XiaocongAi** [comment]
Hi @paulgessinger , I tried to fix the docs warning, but somehow there is more failure now, which I don't understand. Do you know how I should fix this?

**Comment by paulgessinger** [comment]
This is an actual failure now, see #876. Sorry

**Comment by XiaocongAi** [comment]
@paulgessinger , I see. Thanks! I guess I just need to wait for #876 to be merged in then.

**Review by asalzburger — APPROVED** [review]

**Pull request merged**
