### PR TITLE
refactor!: Use `std::string_view` for `addColumn` in track EDM

### PR DESCRIPTION
**Pull request by andiwand**
This makes it easier for compile time known dynamic columns to add. Pulled out of https://github.com/acts-project/acts/pull/3161

### CODE REVIEW

**Review by AJPfleger — APPROVED** [review]
Is this already updating all cases of 'const std::string&'?

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [7120c6b5f8886fb79b65ef11335b35a2f2ed8942]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38979708) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7392331)!

**Comment by andiwand** [comment]
I will fix this tomorrow

**Review by paulgessinger — COMMENTED** [review]
I did this originally because the xAOD backend I believe needs strings. I guess the backend can just make a string from the string view, however.

**Comment by andiwand** [comment]
> I did this originally because the xAOD backend I believe needs strings. I guess the backend can just make a string from the string view, however.

I see - I should have checked the xAOD backend first. Creating a `string` from a `string_view` is not optimal but at the same time this function should not be high traffic.

**Pull request merged**
