### PR TITLE
build: Remove bundled dependencies in favor of CMake FetchContent

### PR DESCRIPTION
**Pull request by paulgessinger**
As discussed in the past and also already implemented for vecmem, this PR removes the bundled copies of 

- nlohmann_json
- pybind11
- dfelibs
- autodiff

and uses CMake's FetchContent to grab a copy. Also added is an option `ACTS_USE_SYSTEM_PYBIND11` to allow using an already installed copy. For nlohmann_json and autodiff this was already present, and I don't think it's necessary for dfelibs.

### CODE REVIEW

**Comment by paulgessinger** [comment]
@krasznaa maybe you could have a look at this?

**Comment by paulgessinger** [comment]
Files of relevance should be

- `CMakeLists.txt`
- `README.md`
- `docs/getting_started.md`
- `thirdparty/README.md`
- `thirdparty/autodiff/CMakeLists.txt`
- `thirdparty/dfelibs/CMakeLists.txt`
- `thirdparty/nlohmann_json/CMakeLists.txt`
- `thirdparty/pybind11/CMakeLists.txt`

Everything else is deleted files. You should be able to click on "File filter" to hide deleted files:

grafik

**Comment by paulgessinger** [comment]
@niermann999 could you review this maybe?

**Review by asalzburger — APPROVED** [review]
Looks good, approving it - thanks for updating the documentation in the same PR.

**Pull request merged**
