### PR TITLE
feat(Fatras): Add decay interface

### PR DESCRIPTION
**Pull request by msmk0**
Add a decay template interface to the Fatras simulation and implement a default no-decay module that treats all particles as stable.

Decay modules need to implement the following methods
```cpp
  template <typename generator_t>
  Particle::Scalar generateProperTimeLimit(generator_t&, const Particle&) const;
  template <typename generator_t>
  <particle-container> generateDescendants(generator_t&, const Particle&) const;
```
that generate a lifetime limit and to decay the particle. The lifetime tracking is handled directly within the main simulation algorithm and not within the decay module to be able to correctly handle Lorentz-factor changes due to energy loss and mass-less particles.

The interface is intentionally designed to be decay-specific. The case of point-like material interactions (e.g. hadronic interactions) is only superficially similar, but does have some significant differences: material interactions can occur more than once, they do not necessarily kill the particle, and they have significantly simpler bookkeeping for the relevant decay variable (proper time with potentially variable Lorentz-factor vs. interaction/scattering length in the laboratory frame). That warrants treating them with a separate interface.

Supersedes and closes #588.

### CODE REVIEW

**Comment by FabianKlimpel** [comment]
I had a first brief look at your suggested changes. These only consider a decay as point-like simulation stopper. Consequently the photon conversion would require a copy-paste of all these changes just to provide the interface, right?

**Comment by msmk0** [comment]
> I had a first brief look at your suggested changes. These only consider a decay as point-like simulation stopper. Consequently the photon conversion would require a copy-paste of all these changes just to provide the interface, right?

Yes, this interface only applies to decays for the reasons outlined in the PR description. For the same reasons

**Comment by msmk0** [comment]
@FabianKlimpel My apologies, for accidentally closing this. Clumsy fingers.

**Review by FabianKlimpel — COMMENTED** [review]
The concept of #588 was to construct an interface for all "point-like" effects. Having photon conversion and hardonic interactions in mind, the interface in this PR is a similar approach but I don't see whether you want to include these effects by adding even more template parameters (i.e. one parameter per effect) to the simulation list or by using the decay interface as a list of effects. Latter one is from my perspective easier to implement but in that case I would not name it decay explicitly. If this is just intended to be used for decays then it looks to me like a temporary solution.
Could you consider renaming the `decay` to something like `destructive effect`? It looks to me as if one could replace the effect without any changes (beside the naming of variables). Then it would be applicable in a more general way.

But in general: It's a good solution, I'm just worried about a potential loss of generality compared to #588.

**Comment by msmk0** [comment]
Superseded by #651 .

**Pull request closed without merging**
