### PR TITLE
chore: Update ParticleDataTable.hpp

### PR DESCRIPTION
**Pull request by paulgessinger**
This updates the script to generate our particle data table from scikithep, and updates the table.

### CODE REVIEW

**Comment by AJPfleger** [comment]
Does `clang-format` do anything after generating the data base?
Maybe we should remove it? Since we don't expect any changes, an ill setup system could even mal-format the file.

**Comment by paulgessinger** [comment]
This is not intended to be run very often, so I would say it's not super critical.

**Comment by paulgessinger** [comment]
Memory consumption of compiling this header file goes from 60M to 77M, which I think we can tolerate.

**Review by andiwand — APPROVED** [review]

**Comment by andiwand** [comment]
Are the output changes coming from changes in particle properties like mass @paulgessinger ? Let's look at the new plots and check how big the variation is

**Comment by paulgessinger** [comment]
I haven't looked into this further. I'd wouldn't have expected masses to change actually but who knows.

**Comment by andiwand** [comment]
physmon looks like outliers moved a bit - unproblematic from my side

**Comment by AJPfleger** [comment]
@andiwand suggested in the dev-meeting:
- physmon is fine again, maybe just clash with different PR
- 1 hash changed, maybe because one of the masses changed. We should go with the updated mass.

Next step: @andiwand will update the hash

**Review by AJPfleger — APPROVED** [review]

**Review by AJPfleger — DISMISSED** [review]

**Review by AJPfleger — DISMISSED** [review]

**Review by AJPfleger — APPROVED** [review]

**Pull request merged**
