### PR TITLE
ci: Bump container images and add SYCL job

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR bumps all CI container images to [`v8`](https://github.com/acts-project/machines/releases/tag/v8) and adds a SYCL plugin CI build based on a [newly added image](https://github.com/acts-project/machines/pull/26).

### CODE REVIEW

**Comment by paulgessinger** [comment]
This is held up because container image generation seems to be broken. Investigating.

**Comment by paulgessinger** [comment]
Ok, it seems to finally build now. 🥳

**Comment by msmk0** [comment]
@paulgessinger Should we introduce global (env) variable for the container version to the workflows? I fear that we will always forget updating at least one image if we bump the container version.

**Comment by paulgessinger** [comment]
Not sure that will work because they are spread across different workflow files anyway. We've had inconsistent tags in the past already and it wasn't critical, so I'd just keep it as is. The tags shouldn't be able to break anything retroactively.

**Comment by msmk0** [comment]
> Not sure that will work because they are spread across different workflow files anyway. We've had inconsistent tags in the past already and it wasn't critical, so I'd just keep it as is. The tags shouldn't be able to break anything retroactively.

True, but we could have at least one variable per workflow file. That would already reduce the number of sites that need to be changed.

**Comment by msmk0** [comment]
@paulgessinger The oneAPI container is v9 while all others are v8. Is that intentional?

**Comment by paulgessinger** [comment]
Not really, I'll update this.

**Comment by msmk0** [comment]
@paulgessinger I am happy to merge this after you bumped all container images to `v9`.

**Comment by asalzburger** [comment]
This PR bumps all CI container images to v8 and adds a SYCL plugin CI build based on a newly added image.

**Comment by msmk0** [comment]
@asalzburger I think you were a bit too fast with the merge (and I forgot to set it back to WIP). I opened #642 as a follow up. Can you do this or should @paulgessinger have a go?

**Comment by paulgessinger** [comment]
I'll to it quickly.

**Pull request merged**
