### PR TITLE
feat(util): Add `overloaded` helper

### PR DESCRIPTION
**Pull request by paulgessinger**
This is useful in combination with `std::visit`. With this, you can do something like 

```cpp
  struct A {};
  std::variant<int, double, A> var;

  var = 42;

  std::visit(overloaded{
                 [](int) { BOOST_CHECK(true); },
                 [](double) { BOOST_CHECK(false); },
                 [](A) { BOOST_CHECK(false); },
             },
             var);
```

which can be convenient.

I'm using this in https://github.com/acts-project/acts/pull/3869

### CODE REVIEW

**Comment by paulgessinger** [comment]
I have a usage in the upcoming blueprint PR.

**Comment by paulgessinger** [comment]
@AJPfleger Objections?

**Comment by AJPfleger** [comment]
looks good, could you just link the blueprint-PR?

**Comment by paulgessinger** [comment]
@AJPfleger That's not ready yet

**Comment by paulgessinger** [comment]
@AJPfleger can you have another look now?

**Review by andiwand — APPROVED** [review]

**Pull request merged**
