### PR TITLE
refactor: TrackProxy::copyFrom copies track states

### PR DESCRIPTION
**Pull request by paulgessinger**
This uses a newly added function to reverse track states to create the track states with reverted order and then flip the order around to produce a good copy.

Blocked by:
- https://github.com/acts-project/acts/pull/2204

### CODE REVIEW

**Comment by paulgessinger** [comment]
@goetzgaycken

**Comment by goetzgaycken** [comment]
Great ! Seems to work. I suppose the  `tipIndex() = other.tipIndex();` in the version without this patch causes the invalid track states.

**Comment by paulgessinger** [comment]
Ok it seems I need to debug a bit more.

**Comment by paulgessinger** [comment]
Ok I think I fixed the crash, let's see if the CI agrees.

**Pull request merged**
