### PR TITLE
feat: root event diff script

### PR DESCRIPTION
**Pull request by andiwand**
small python script to check in which event a diff in a root file occurs 

can be invoked like the following

```
python CI/root_event_diff_np.py tracksummary_gsf_a.root:tracksummary tracksummary_gsf_b.root:tracksummary
```

### CODE REVIEW

**Comment by andiwand** [comment]
@paulgessinger cc

**Review by paulgessinger — APPROVED** [review]

**Review by benjaminhuth — APPROVED** [review]

**Comment by AJPfleger** [comment]
@andiwand Should we integrate the script in the CI or move it to scripts? does it still work?

**Comment by andiwand** [comment]
> @andiwand Should we integrate the script in the CI or move it to scripts? does it still work?

I used it the other day and it seems to work fine. But I don't have a strong opinion where it should live

**Comment by AJPfleger** [comment]
I guess, we can then leave it her as well for now :)

**Pull request merged**
