### PR TITLE
refactor: Generalize propagation validation in Examples

### PR DESCRIPTION
**Pull request by andiwand**
Some preparation work to monitor the propagation including stepping and navigation tightly with CI

### CODE REVIEW

**Review by asalzburger — APPROVED** [review]
That looks very good, indeed! I am looking forward to this additional information.

**Comment by asalzburger** [comment]
This will alter the output physmom examples I suppose?

**Comment by andiwand** [comment]
There are a few more downstream changes to handle but that should be done by tomorrow morning @asalzburger

**Comment by andiwand** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=acts-project_acts&pullRequest=3434) **Quality Gate failed**
> Failed conditions  [4 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=acts-project_acts&pullRequest=3434&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=acts-project_acts&pullRequest=3434)

@paulgessinger can you disable these errors?

**Comment by andiwand** [comment]
Hm hashes are changing which I think is due to changing RNG which is not really expected

**Comment by paulgessinger** [comment]
@andiwand consider having a Quick Look at the issues in sonar.

**Comment by andiwand** [comment]
I do not observe output changes locally

**Comment by asalzburger** [comment]
This has now some conflicts, because of the change to particle gun input, I would still like these changes to come in, I think the propagation summary will be very helpful in debugging G1/2/3

**Comment by andiwand** [comment]
Superseded by https://github.com/acts-project/acts/pull/3514

**Pull request closed without merging**
