### PR TITLE
Workaround for building on clang and libstdc++ (part 2)

### PR DESCRIPTION
**Pull request by czangela**
Enables compilation with clang 11.

### CODE REVIEW

**Comment by msmk0** [comment]
Hi @czangela, could you let us know in which environment you encounter this error (operating system, how are the external dependencies installed) and the exact compile error you encounter?

**Comment by paulgessinger** [comment]
> Hi @czangela, could you let us know in which environment you encounter this error (operating system, how are the external dependencies installed) and the exact compile error you encounter?

Most likely LCG clang + libstdc++, as we've had before. We really need a build of that going again...

**Comment by czangela** [comment]
> Hi @czangela, could you let us know in which environment you encounter this error (operating system, how are the external dependencies installed) and the exact compile error you encounter?

Hi @msmk0,
actually, the error is not new, that's why I did not provide extra information about it.

There was a [patch](https://gitlab.cern.ch/atlas/atlasexternals/-/blob/2.0.58/External/Acts/patches/Acts-v0.10.04-clang.patch) about it a few months ago, which content was then moved to a [separate header file](https://github.com/acts-project/acts/commits/master/Core/include/Acts/Utilities/detail/ReferenceWrapperAnyCompat.hpp).

As far as we know the error occurs because clang and gcc standard header files differ a little bit, and mixing one compiler with the other's header files might introduce errors. Usually, it doesn't mean any problem. However, putting a (const) std::any (GeometryContext) type in a std::reference_wrapper (and moving that around) seems to trigger an error. [compile_error.txt](https://github.com/acts-project/acts/files/4954535/compile_error.txt)

(So clang and libstdc++ are not 100% compatible. It has to do something with the order of template instantiation. Or something like that.)

This is just a workaround for this. It is definitely not a good solution but it works.

**Comment by krasznaa** [comment]
Hi Paul,

We see this when using Intel's compiler (https://github.com/intel/llvm) on top of GCC 8's `libstdc++` version. But @cgleggett was also reporting about some strange issues with a little different LLVM + `libstdc++` combination. So yeah, it's very much a moving target. :frowning:

Also, don't miss that the code adds a missing include and a missing `#pragma once` statement as well. :wink:

Cheers,
           Attila

**Comment by paulgessinger** [comment]
Right, makes sense and LGTM

**Pull request merged**
