### PR TITLE
feat: Add ITk module splitter based on new json

### PR DESCRIPTION
**Pull request by niermann999**
Introduces a splitter class for ITk TGeo modules that contains a splitting method for barrel and disc modules. The splitting method and number of segments is determined by a simple sensor name map in json format. This PR is rebased on the new TGeo json rw

### CODE REVIEW

**Comment by niermann999** [comment]
new_ITk_splitting_BL

**Comment by niermann999** [comment]
new_ITk_splitting_EC

**Comment by niermann999** [comment]
I am not quite sure where the macos vtable error comes from. Could you have a look, please @asalzburger?

**Comment by paulgessinger** [comment]
Most of the time, macOS build errors also show up in other clang builds, fyi.

**Comment by asalzburger** [comment]
This can be closed then, I guess?

**Pull request closed without merging**
