### PR TITLE
refactor: correcting a typo on surfacetypes and add type binding for surfaces

### PR DESCRIPTION
**Pull request by dimitra97**

### CODE REVIEW

**Comment by asalzburger** [comment]
Di you want to close it? I've added the 'next' milestone.

**Comment by dimitra97** [comment]
> Di you want to close it? I've added the 'next' milestone.

No thank you! I was trying to add the next milestone

**Review by andiwand — APPROVED** [review]
looks good to me :+1:

**Comment by andiwand** [comment]
is this ready to be merged @dimitra97 ? if so feel free to add the automerge label or ping me

**Comment by dimitra97** [comment]
> is this ready to be merged @dimitra97 ? if so feel free to add the automerge label or ping me

The 1 in progress required check is: merge-sentinel In progress — Waiting for 1 job: review-required: main

**Review by andiwand — APPROVED** [review]

**Pull request merged**
