### PR TITLE
perf: Remove positive definite check from smoothing

### PR DESCRIPTION
**Pull request by andiwand**
I saw this popping up during profiling. Not sure if this is save to remove but I wanted at least measure it and discuss it. I am not sure if the covariance is simply correctible after it broke. Maybe this would rather be a track to throw out? We are trading quite a significant amount of CPU for it at the moment.

### CODE REVIEW

**Review by AJPfleger — COMMENTED** [review]
Should we then also remove
https://github.com/acts-project/acts/blob/main/Core/include/Acts/EventData/detail/covariance_helper.hpp
as a whole?

How can the smoothed covariance become not positive semidefinite? maybe we can have a check earlier?

It seems, this never happens in our tests, but not sure if it is safe. If we want to keep some check here, we could:
- pack this one in an `assert`, then we have full performance in the release
- have a simplified test, e.g. just check if the diagonal is positive like `cov(i,i) > 1e-10`

Maybe @XiaocongAi has some input?

**Comment by andiwand** [comment]
I don't know, it might still be useful. Potentially the naming should change and it could be moved out of `detail::`.

My objective here was to get the CKF faster and this function popped up when I measured. IMO it could be an `assert` but that could also be annoying if it fires and terminates.

I would rather put this on the consumer of the tracks or the track selection. If this happens the track is not usable anyways I believe.

**Comment by AJPfleger** [comment]
> I don't know, it might still be useful. Potentially the naming should change and it could be moved out of `detail::`.

If it might be still useful, someone could revive it from an older version, I guess? If we don't remove the file, it will be eaten by the `unused-check` anyway, so we must move it to a different place. However, I see no need to "add" a fucntion, we do not intend to use at all :(
Another reason not to keep it is, that the current implementation is a bit buggy. We check for `NaN` in the beginning to abort early, but if we encounter `NaN` later in the correction-loop, we will continue, until we reach `NumIter` (in our case ok, because we have `NumIter = 1`).

> I would rather put this on the consumer of the tracks or the track selection. If this happens the track is not usable anyways I believe.

Could you maybe check, how often we have to fix the covariance? Like a very general setup with a full detector and 1e6 events (if we don't see anything in 1e4 events)?
I think, if this occurs 1 in 1e4 events, I wouldn't bother too much and the consumer should do the check.

If it occurs, we should actually put a check in a different place, before removing this one.

But if the track needs to thrown away anyway, we maybe could add an extra error-code here. For this one, I am fine with only checking the diagonal.

**Comment by asalzburger** [comment]
We should not spend all the time in checking, that's right, also patching the covariance in situ sounds fishy to me.

Can we somehow run this in debug mode only?

**Comment by andiwand** [comment]
Running with `ODD, fatras, ttbar PU 200, 100 events` I see 7 occurrences in a single event. I suspect that these are correlated by a single branching track. In these cases it is able to "fix" the covariance.

I don't see a single occurrence with muons in 1000 events with 800 muons each.

**Review by asalzburger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [c351b359b304a2f21a0576e6474d103bec944854]
### :white_check_mark: All tests successful

|status|job|report|
|------|---|------|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523622)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523621)||
|:green_circle: | [test_ActsPersistifySeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523620)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523619)||
|:green_circle: | [test_ActsAnalogueClustering](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523618)||
|:green_circle: | [test_ActsConversionWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523617)||
|:green_circle: | [test_ActsWorkflowHeavyIons](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523616)||
|:green_circle: | [test_ActsWorkflowFastTracking](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523615)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523614)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523613)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523612)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523611)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523610)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523609)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523608)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523607)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523606)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523605)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523604)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523603)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523602)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523601)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523600)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523599)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523598)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523597)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523596)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523595)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38523594)||

**Pull request merged**
