### PR TITLE
fix: AMVF track linearization and seed constraint fix for q431 test (backport)

### PR DESCRIPTION
**Pull request by baschlag**
These changes fix the issues we've seen when employing the ACTS AMVF on data in Athena, targeting an ACTS v1.2.1 bug fix release. Changes made:

- In case the algorithm finds a bad vertex and deletes it at some point again, I need to force it to relinearize the tracks in the next iteration since they were linearized with respect to the bad vertex.
- If the seed constraint is turned off, the old (e.g. beamspot) constraint will now be correctly applied.
- For consistency reasons with Athena, a negative determinant check in the track linearizer is added.

The corresponding master PR [can be found here](https://github.com/acts-project/acts/pull/550).

## Data: 
validation_AllPrimaryVertices_vx_z
validation_AllPrimaryVertices_vx_nTracks
validation_AllPrimaryVertices_vx_err_z

## MC:

validation_AllPrimaryVertices_vx_z
validation_AllPrimaryVertices_vx_nTracks
validation_AllPrimaryVertices_vx_err_z

### CODE REVIEW

**Comment by paulgessinger** [comment]
macOS build failure is expected. I'll backport the fix to the release branch

**Comment by paulgessinger** [comment]
@baschlag will you also open a PR to master containing these changes?

**Review by paulgessinger — COMMENTED** [review]
Could you elaborate in the description a little bit what the fix is/was? I'm not sure I understand just looking at the changeset.

**Comment by baschlag** [comment]
> @baschlag will you also open a PR to master containing these changes?

The master PR was already there a couple of days ago. Just un-WIP-ed it and added a link to the description above.

**Comment by baschlag** [comment]
> Could you elaborate in the description a little bit what the fix is/was? I'm not sure I understand just looking at the changeset.

Done. Sorry, I had the description in the corresponding master PR and meant to just refer to it. Updated the description now here as well.

**Comment by baschlag** [comment]
@paulgessinger Would you mind reviewing/approving and creating the next tag, so that I can open an Atlas externals MR with ACTS v.1.2.1?

**Review by paulgessinger — APPROVED** [review]

**Pull request merged**
