### PR TITLE
test: Test field invariance of direction uncertainty transport

### PR DESCRIPTION
**Pull request by andiwand**
This is testing a suspicion I had about direction uncertainty transported with and without magnetic field. The covariance of the direction does not care if it is transported in a straight line or along a curved track. This allows us to apply MSC effects after traversing the material by only remembering at which distances they occurred. Afterwards the covariance can be treated as an additional term to the final propagation covariance.

### CODE REVIEW

**Comment by andiwand** [comment]
@beomki-yeo @paulgessinger fyi

**Comment by andiwand** [comment]
Hm the SL propagator is just undoing it's own work right now so this does not prove anything yet. I think I have to introduce an additional direction uncertainty for both cases before propagating.

**Comment by beomki-yeo** [comment]
I am confused by the title. Doesn't direction uncertainty increase with the presence of the magnetic field?

**Comment by paulgessinger** [comment]
This has picked up conflicts. What's the plan for this @andiwand?

**Comment by andiwand** [comment]
I will try to follow up with this in the next few weeks

**Pull request closed without merging**
