### PR TITLE
refactor: Remove target volume estimation from `Navigator`

### PR DESCRIPTION
**Pull request by andiwand**
This is an attempt to remove (IMO) unnecessary complexity from the `Navigator`. We have a target volume estimation which runs a couple of times to guess the target volume based on an intersection with the target surface. IMO if we know the target surface we should also know the target volume and the user is responsible for passing this information.

### CODE REVIEW

**Comment by andiwand** [comment]
The error might go away after https://github.com/acts-project/acts/pull/2846 🤞

**Comment by andiwand** [comment]
image

image

**Review by AJPfleger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [0002ab1d5cec9afab7e697086cfcdaba20bb4738]
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7461656)!

|status|job|report|
|------|---|------|
|:red_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39399357)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395280)||
|:green_circle: | [test_ActsPersistifySeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395279)||
|:red_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395278)||
|:green_circle: | [test_ActsAnalogueClustering](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395277)||
|:green_circle: | [test_ActsWorkflowHeavyIons](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395276)||
|:red_circle: | [test_ActsWorkflowFastTracking](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395275)||
|:red_circle: | [test_ActsWorkflowCached](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395274)||
|:red_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395273)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395272)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395271)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395270)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395269)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395268)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395267)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395266)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395265)||
|:red_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395264)||
|:red_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395263)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395262)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395261)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395260)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395259)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395258)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395257)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395256)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395255)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395254)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/39395253)||

**Comment by paulgessinger** [comment]
How sure are we about this? What about surfaces which are not registered in the geometry? There's currently now way to figure out the target volume without a hierarchy search is there?

**Comment by andiwand** [comment]
> How sure are we about this? What about surfaces which are not registered in the geometry? There's currently now way to figure out the target volume without a hierarchy search is there? @andiwand

From my point of view it is not useful to figure out the target volume as a part of the navigation. The target volume is constant and is given by the target surface. If the target surface has no volume assigned to it (e.g. perigee surface) then we will just not know it and resolve a few more surface candidates in the volume.

Figuring out the target volume could be an initialization step, if we think that is useful. Any point on the target surface should let you figure out in which volume we are, as long as there are not overlaps which results in undesired behavior in all of our navigation code.

What I would like to do in future changes is to provide the target surface as an external surface with a correctly assigned volume so the navigator can figure out its way to the target surface. Right now the `Navigator` and the `SurfaceReached` aborter fight for the step size which can result in all sorts of funky behavior. @paulgessinger

**Comment by paulgessinger** [comment]
That definitely makes sense. I'd just like to avoid requiring the user to figure out the target volume manually, if the navigation needs it, because it feels to me like that would be easy to get wrong.

**Comment by andiwand** [comment]
> That definitely makes sense. I'd just like to avoid requiring the user to figure out the target volume manually, if the navigation needs it, because it feels to me like that would be easy to get wrong

Right - I did not see any "need" for the target volume to be present except that it might save you from putting in a few more surface candidates into a vector. I didn't measure any performance losses there. The navigation procedure itself _should_ be unaffected by this change.

That said there are a few more Athena failure after this went in but I was not able to catch up with them yet.

**Pull request merged**
