### PR TITLE
refactor: convert to bound state also on empty sensitive surfaces.

### PR DESCRIPTION
**Pull request by goetzgaycken**
This allows to merge retrieval of source link ranges, measurement selection and track state creation into one unit.

This increases the computational effort slightly for empty, sensitive surfaces, since the computation of bound states is slightly more demanding than the computation of curvilinear states, but for complex events like HL-LHC events the regression was not measurable.

--- END COMMIT MESSAGE ---

This changes track states on surfaces without measurements, which are in curvilinear parameterisation before this change but parameterised as bound states after this change. This also slightly changes some values of the track summary tree (O(10^6); `err_{eLOC1,eTHETA,eQOP}_fit, pull_{eLOC1,eTHETA,eQOP}_fit`)

## Summary by CodeRabbit

- **New Features**
	- Enhanced track finding and filtering processes with improved logic in the CombinatorialKalmanFilter.
  
- **Bug Fixes**
	- Updated error handling in the filtering process to prevent unnecessary processing when no measurements are available.

- **Tests**
	- Updated hash values for multiple test files to reflect recent modifications in their contents.

### CODE REVIEW

**Comment by goetzgaycken** [comment]
maybe it is a feature rather than refactor ?

**Comment by paulgessinger** [comment]
If @andiwand has no objections, can you update t he references @goetzgaycken?

**Comment by andiwand** [comment]
LGTM 👍

**Comment by goetzgaycken** [comment]
> If @andiwand has no objections, can you update t he references @goetzgaycken?

did so.  Thanks !

**Comment by paulgessinger** [comment]
@goetzgaycken Unfortunately, the hash file has conflicts with main now. Can you resolve them?

**Comment by goetzgaycken** [comment]
changes from  a26c65b to 7718c45:
- revert changes to hashes
- rebase to main 7718c45c38a418450725b24b1a436398823f93dd

next step update to new hashes.

**Review by andiwand — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [4cd88af8276d5f15651b2b06dea2301859a1b71e]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46545314) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/8596947)!

**Pull request merged**
