### PR TITLE
ci: Physmon for single particles

### PR DESCRIPTION
**Pull request by andiwand**
WIPWIP

### CODE REVIEW

**Comment by paulgessinger** [comment]
Let's see how long this run since it's a lot of combinations.

**Comment by andiwand** [comment]
looks like we cannot have `addGeant4` twice - I'll have to investigate

**Comment by paulgessinger** [comment]
We could add this once we're moving to pytest for physmon, I guess.

**Comment by andiwand** [comment]
I will tackle this again when we have pytest for physmon and more time at hand

**Pull request closed without merging**
