### PR TITLE
refactor: Range1D becomes special case of RangeXD

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR reimplements the `Range1D` as a special case of the more general `RangeXD`. Most importantly, I'm switching the `operator[]` of `RangeXD` to return a 1-dim `RangeXD` with the vector type set to a simple "simple element" container that has reference semantics.

Finally, `Range1D` is typedef'ed to `RangeXD` of dimension 1.

One remaining question is that the naming `XD` is not super well aligned with the rest of our naming (e.g. `Vector2`, `Vector3`), but I'm not sure if `Range`/`Range1` is any better.

### CODE REVIEW

**Review by stephenswat — DISMISSED** [review]
Looks good, thanks!

**Comment by andiwand** [comment]
> One remaining question is that the naming `XD` is not super well aligned with the rest of our naming (e.g. `Vector2`, `Vector3`), but I'm not sure if `Range`/`Range1` is any better.

Good question - `Range`/`Range1` seems more aligned with `Vector` but looks a bit too generic. I don't have a strong opinion on this. In doubt we can leave it for now.

**Comment by asalzburger** [comment]
I saw Stephen had reviewed this, as original author, that's good!

**Comment by andiwand** [comment]
clang tidy is complaining

**Comment by paulgessinger** [comment]
Currently looking for the problem in the ExaTrkX test

**Comment by paulgessinger** [comment]
Ok I got it. I was incorrectly reusing the storage vector type as the coordinate type. We only use the coordinate type for the `contains` check, so I'm moving that type to a method template.

**Comment by paulgessinger** [comment]
@stephenswat could you hit the button again?

**Review by stephenswat — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [572c49a8206f406c88f8098589b9e2e913ab2a8a]
### :white_check_mark: All tests successful

|status|job|report|
|------|---|------|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033947)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033946)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033945)||
|:green_circle: | [test_ActsConversionWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033944)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033943)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033942)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033941)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033940)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033939)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033938)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033937)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033936)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033935)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033934)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033933)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033932)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033931)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033930)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033929)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033928)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033927)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033926)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033925)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033924)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37033923)||

**Pull request merged**
