### PR TITLE
feat: minimum number of top SPs in orthogonal seeding confirmation

### PR DESCRIPTION
**Pull request by LuisFelipeCoelho**
I realised there was a step in seeding confirmation missing in the orthogonal seeding.
This avoids searching for top SPs if we set a minimum number of top SPs required for a specific region of the detector based on the seeding confirmation configuration. Probably improves slightly the time performance.

### CODE REVIEW

**Comment by LuisFelipeCoelho** [comment]
This one is ready for review (not WIP)
FYI: @CarloVarni @stephenswat

**Comment by paulgessinger** [comment]
@stephenswat could you give this a quick look?

**Review by stephenswat — APPROVED** [review]
Sorry for the delay. Looks good to me.

**Comment by paulgessinger** [comment]
System failure unrelated to PR content.

**Pull request merged**
