### PR TITLE
fix: TGeo disc and cylinder splitting

### PR DESCRIPTION
**Pull request by plariono**
This PR contains a fix of the bug in the `TGeoCylinderDiscSplitter` class that prevented splitting the disk layers only, i.e.: 

```
--geo-tgeo-cyl-nz-segs -1
--geo-tgeo-cyl-nphi-segs -1
--geo-tgeo-disc-nr-segs 1
--geo-tgeo-disc-nphi-segs 32
```

### CODE REVIEW

**Comment by asalzburger** [comment]
Great to see this - there's a few things to be done.

- [ ] we are using a common formatting style enforced by `clang-format`, this is one check that is failing, you should run locally with `./CI/check_format .` before committing. Unfortunately `clang-format` is not very stable regarding different versions, so you could (to be sure) use the docker-image version `./CI/check_format_local .` for which you'd have `docker` to be running
- [ ] looks like the CVMFS based builds needs some permission, we can sort that out later

**Comment by asalzburger** [comment]
The branch is not up-to-date with the tip of main, usually one would have to rebase it then, but it is a very small change, so I can rebase using the web interface.

**Review by asalzburger — APPROVED** [review]
The changes are exactly how they should be, they fix the flawed logic of former splitting.

**Comment by plariono** [comment]
> The branch is not up-to-date with the tip of main, usually one would have to rebase it then, but it is a very small change, so I can rebase using the web interface.

I see, thank you!

**Pull request merged**
