### PR TITLE
refactor(examples): Consistent track finding/fitting naming

### PR DESCRIPTION
**Pull request by msmk0**
Use consistent type, function, and module names for the track finding and fitting examples modules. Ensure the naming matches the naming of the corresponding modules in the Core.

This is a purely stylistic PR without any functional changes.

### CODE REVIEW

**Review by paulgessinger — APPROVED** [review]
Sure, why not.

**Comment by msmk0** [comment]
This was something that @XiaocongAi mentioned in a previous PR discussion.

**Comment by msmk0** [comment]
@paulgessinger @XiaocongAi This is ready to be reviewed.

**Review by XiaocongAi — APPROVED** [review]
Hi @msmk0 ,  it's nice changes. The naming is more consistent now.

**Pull request merged**
