### PR TITLE
refactor!: Make `BoundaryCheck` constructor from `bool` explicit

### PR DESCRIPTION
**Pull request by andiwand**
This increases readability IMO

### CODE REVIEW

**Comment by paulgessinger** [comment]
Yes please! CI fails at the moment, however.

**Comment by andiwand** [comment]
this is running through now but I guess it is a breaking change?

**Review by paulgessinger — APPROVED** [review]
Diff looks clean to me! 🎉

**Review by paulgessinger — APPROVED** [review]

**Review by paulgessinger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [2697f5a5584786014c97ae2beeab7b400ab7b36f]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33685195) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6434628)!

**Pull request merged**
