### PR TITLE
fix: Update EventRecording to remove disconnected vertices and particles

### PR DESCRIPTION
**Pull request by andriish**
Prevent problems similar to #877

### CODE REVIEW

**Comment by paulgessinger** [comment]
This does not seem to compile

**Comment by paulgessinger** [comment]
@andriish can I close this then?

**Comment by andriish** [comment]
I suspect there might be the same problem as in #877. 

A simple `for` will not work, as there might be a case of e.g. two vertices and one particle connected together but disconnected from all other particles/vertices in the event. 

VertexA ---ParticleA-->VerxexB

So after one `for` loop the event will still contain disconnected particles/vertices.

**Comment by robertlangenberg** [comment]
Hi @andriish could you give a bit more explanation what you want to fix here and get the CI to go green? Thanks!

**Comment by andriish** [comment]
Hi @robertlangenberg ,

> what you want to fix 

exactly the behaviour of #877.

Best regards,

Andrii

**Comment by andriish** [comment]
Hi @paulgessinger , @robertlangenberg ,

any progress with this MR?
I'm not using the acts by myself, just helped with some issues that were related to the work of @FabianKlimpel , so I would be grateful if this MR would be resolved is some way.

Best regards,

Andrii

**Comment by paulgessinger** [comment]
Hey @andriish,

we still do not quite understand how this PR relates to #877 and #911. Is this changing the EventRecording so that problematic vertices do not get appended at all, while #911 removes them at the end? If so, why do we need to do both?

**Comment by andriish** [comment]
Hi @paulgessinger ,

 - the current logic of the "cleaning" in the very end is:

    go through the event *ONCE* and remove 

    - the vertices w/o outgoing particles.

But it is not enough to remove only the vertices w/o outgoing particles to ensure the event has a tree-like structure.

 - so the proposed logic is:

   loop over particles and vertices until there will be no 

   - particles w/o prod. vertex
   - vertices w/o outgoing particles

The "proposed logic" cleans up more "broken" cases in the event structure (e.g. similar to #877)  than the current version and assures creation of an event with a tree-like structure that can be then correctly read back.

Of course, not all events will contain particles w/o prod. vertex or vertices w/o outgoing particles. And for some events the current version of code will work fine, but it is better to be on the safe sie, as for me. 


Best regards,

Andrii

P.S. An example of "bad" event structure that would not be cured by the current logic is 

ParticleA  has some prod_vertex VertexX and end_vertex VertexY
ParticleB has no prod_vertex but has end_vertex VertexY
VertexY has no outgoing particles

The current version of code would just remove the VertexY, but completely disconnected particleB would remain in the event.

**Comment by asalzburger** [comment]
I started cleaning out the Geant4 examples a bit more, we have several files that are now called the same, e.g. `SteppingAction.h/cpp`, etc. 

What I suggest (PR in work) is:
 * Material*Actions - for recording/writing the material
 * Simulation*Actions - for a very simplified/limited Geant4 simulation (mainly to be used for `Fatras` validation)
 * EventRecording*Actions - for the interaction recording & parameterisation stuff

**Comment by paulgessinger** [comment]
@asalzburger they're called the same but I moved them into separate namespaces in a PR that was merged a few weeks ago.

**Comment by paulgessinger** [comment]
I updated the format of the `EventRecording.cpp` file.

**Review by paulgessinger — APPROVED** [review]

**Comment by andriish** [comment]
Thanks, @paulgessinger!

If there will be any issues related to HepMC, ping me.

Best regards,

Andrii

**Pull request merged**
