### PR TITLE
ci: Pull more config into physmon script, extend PG eta range to +-4

### PR DESCRIPTION
**Pull request by paulgessinger**
I think for the physmon jobs, given the ODD, it makes little sense to only test particle up to $|\eta| < \pm2$. This PR adjusts `physmon.py` to include the particle gun configuration so I can customize it to produce particles up to $|\eta| < \pm 4$.

### CODE REVIEW

**Comment by paulgessinger** [comment]
I had a look at the physmon outputs. They're basically as expected.

# CKF Seeded 
grafik
Not entirely sure why this looks so asymmetric.

grafik
grafik
Bit of an odd feature in the tracking efficiency in $\eta$. Since this doesn't show up in the other "seeding" modes, it might be some feature of the seeding?

# CKF truth estimated
grafik

# CKF truth smeared
grafik

**Review by andiwand — APPROVED** [review]
plots look mostly reasonable IMO

the on with the holes looks a bit weird but that might be due to statistical fluctuations? the error bars are quite big. we could check with a different eta distribution, a different seed or more samples. but I don't think it is necessary

**Comment by paulgessinger** [comment]
I updated the references. I realized now that it's actually pretty hard to put in the correct reference commit SHA, because we squash and merge. No idea if that can be improved.

**Comment by andiwand** [comment]
> I updated the references. I realized now that it's actually pretty hard to put in the correct reference commit SHA, because we squash and merge. No idea if that can be improved.

yeah I think it is almost impossible. shouldn't be the git history be enough?

**Comment by paulgessinger** [comment]
Probably yeah.

**Comment by paulgessinger** [comment]
I think this is good now, @andiwand.

**Pull request merged**
