### PR TITLE
Simplify bound parameters

### LINKED ISSUE #35: Bounded track parameters store also free position and momentum
[GitLab issue: #660](https://gitlab.cern.ch/acts/acts-core/issues/660)

The bounded track parameters in `Acts/EventData/SingleTrackParameters.hpp` store 6-vector of local track parameters and derived position and momentum vectors. The later are pure duplicated data and effectively double the size. This duplicate information should be removed. In cases where really the free parameter information is needed, the new free parameters should be used instead.

This originated from the follwoing [discussion](https://gitlab.cern.ch/acts/acts-core/merge_requests/651#note_2931884)

### PR DESCRIPTION
**Pull request by msmk0**
- Implement `SingleBoundTrackParameters` without the `SingleTrackParameters` base.
- Curvilinear parameters are just bound parameters with a fixed surface type. Consequently, they are implemented as a subclass of the `SingleBoundTrackParameters` that only differs in the constructors. This should enable simpler code for cases that where previously handling bound and curvilinear track parameters separately.
- Make the bound parameters const-classes, i.e. they can not be modified after construction, by removing the `.set()` functionality. This greatly simplifies the implementation; e.g. we do not have to recompute the surface geometry for curvilinear parameters anymore. This was only used in the `RiddersPropagator`, where it can be easily replaced by the construction of a new parameters object.
- Bring typedefs for bound and free parameters in line with the naming guidelines.
- Remove cached global position and momentum. The `.position(...)` and `.momentum()` accessors compute the global information directly. To avoid inconsistencies, the `.position(...)` accessor for bound parameters now requires a geometry context that is used to compute the local-to-global transformation.
- Split the `ParameterConcept` into two separate `BoundTrackParametersConcept` and `FreeTrackParametersConcept` concepts.

Closes #35.

### CODE REVIEW

**Comment by msmk0** [comment]
This ended up being a bit larger than I would have liked to. With the changes, no geometry context is required to construct bound parameters, but it is needed when the position is transformed from the local to the global frame. Thus the position accessor `.position(const GeometryContext&)` now requires a context object. This in turn requires to update all points in the code where this is used resulting in a large PR.

If requested, I can split this up into the following smaller PRs:
- Split `ParameterConcept` into two separate ones for bound and free parameters. (This is only used at two points in the propagator and we should seriously consider removing the concept altogether until we can use proper C++20 concepts)
- Simplification of `Single{Bound,Curvilinear}TrackParameters` without adding the context-dependent position accessor. The `.position()` accessor will always use the default geometry context.
- Switch to the context-aware `.position(...)` accessor and add the necessary changes throughout the code base.

**Comment by FabianKlimpel** [comment]
> This ended up being a bit larger than I would have liked to. With the changes, no geometry context is required to construct bound parameters, but it is needed when the position is transformed from the local to the global frame. Thus the position accessor `.position(const GeometryContext&)` now requires a context object. This in turn requires to update all points in the code where this is used resulting in a large PR.
> 
> If requested, I can split this up into the following smaller PRs:
> 
> * Split `ParameterConcept` into two separate ones for bound and free parameters. (This is only used at two points in the propagator and we should seriously consider removing the concept altogether until we can use proper C++20 concepts)
> * Simplification of `Single{Bound,Curvilinear}TrackParameters` without adding the context-dependent position accessor. The `.position()` accessor will always use the default geometry context.
> * Switch to the context-aware `.position(...)` accessor and add the necessary changes throughout the code base.

Could you explain what the benefit of the modified `position(...)` method is? To me it looks like an unnecessary change.
About the concept: I would rather keep our concepts until we can move them to C++20. It provides (some) safety in our templated world.

**Comment by paulgessinger** [comment]
> - Simplification of `Single{Bound,Curvilinear}TrackParameters` without adding the context-dependent position accessor. The `.position()` accessor will always use the default geometry context.

The geometry context should **not ever** be default constructed in our code (outside of unit tests, maybe), since what *default* means is experiment specific.

**Comment by paulgessinger** [comment]
I would argue that 74 changed files with non-automatic changes cannot feasibly be reviewed by a human being.

**Comment by msmk0** [comment]
> Could you explain what the benefit of the modified `position(...)` method is?

This is a direct result from removing the global position/ momentum from the bound parameters as decided during the workshop. Previously, global position/ momentum was computed once during construction and stored (and the constructor required the `GeometryContext`). We decided then to remove the global information but retain the `.position()` and `.momentum()` accessors for convenience. Since the position uses the local-to-global transformation it requires access to the context.

My initial proposal was to remove `.position()` and `.momentum()` altogether from the bound parameters and instead provide e.g. `.toFree(const GeometryContext&)` converter that gives the eqivalent free parameters. Since the free parameters are always defined in a global system, they do not need to know about the `GeometryContext` at all. This was opposed during the workshop discussion.

Using the `GeometryContext` only during transformations is conceptually cleaner: if I define local bound parameters, I should not need to know the how they look like in the global frame. That is the definition of local. Only if I want to know the equivalent description in the global frame should I care about the context.

This type of conceptual clarification will benefit us in the long run: it reduces the interface and reduces ambiguity.

**Comment by msmk0** [comment]
> The geometry context should **not ever** be default constructed in our code (outside of unit tests, maybe), since what _default_ means is experiment specific.

I agree. That is why I want to remove the `.position()` accessor.

> I would argue that 74 changed files with non-automatic changes cannot feasibly be reviewed by a human being. sweat_smile

It is indeed quite a bit of changes. The majority of the changed files are due to replacing `.position()` with `.position(geoCtx)`. I would suggest that I split these two changes into separate PRs. We can keep them both open until they are both reviewed and merge them in quick succession.

**Comment by FabianKlimpel** [comment]
> > Could you explain what the benefit of the modified `position(...)` method is?
> 
> This is a direct result from removing the global position/ momentum from the bound parameters as decided during the workshop. Previously, global position/ momentum was computed once during construction and stored (and the constructor required the `GeometryContext`). We decided then to remove the global information but retain the `.position()` and `.momentum()` accessors for convenience. Since the position uses the local-to-global transformation it requires access to the context.
> 
> My initial proposal was to remove `.position()` and `.momentum()` altogether from the bound parameters and instead provide e.g. `.toFree(const GeometryContext&)` converter that gives the eqivalent free parameters. Since the free parameters are always defined in a global system, they do not need to know about the `GeometryContext` at all. This was opposed during the workshop discussion.
> 
> Using the `GeometryContext` only during transformations is conceptually cleaner: if I define local bound parameters, I should not need to know the how they look like in the global frame. That is the definition of local. Only if I want to know the equivalent description in the global frame should I care about the context.
> 
> This type of conceptual clarification will benefit us in the long run: it reduces the interface and reduces ambiguity.

Why don't you just store it as a reference in the object itself? It makes the access much easier.

**Comment by msmk0** [comment]
Switched back to work-in-progress until all split sub-PRs are in.

**Comment by msmk0** [comment]
This has been superseded by #327 and #328.

**Pull request closed without merging**
