### PR TITLE
feat: CSV-Writer for the Propagation Example

### PR DESCRIPTION
**Pull request by benjaminhuth**
This PR adds a CSV-Writer for the propagation example, which writes out the result of the `SteppingLogger` to a csv-file. The columns of the output file are: 

```
ssaccuracy,ssactor,ssaborter,ssuser,x,y,z,px,py,pz,surface,volume
```

The first 4 are the values in the `ConstrainedStep`. For the surface the geometryID value is written out, for the volume the `.volumeName()` string.

### CODE REVIEW

**Comment by msmk0** [comment]
As mentioned yesterday in the developers meeting: if you are only interested in writing out the steps, you could use the `CsvSimHitWriter` to write out all steps using `ActsFatras::Hit`. The hit class already stores the full kinematic state of the particle and stores a geometry identifier. It does not confine you to surfaces. By setting a volume geometry id, you can indicate that the position is in a given volume but not on a specific surface.

**Comment by benjaminhuth** [comment]
Hmm, I tought about this and I have realized, that later on I will also need a Reader for these step data (for my ML Navigator project).

I think this is not so easy with the `CsvSimHitWriter` / `CsvSimHitReader`, because they depend on Fatras and the Reader checks for the existence of some simulation files on construction, and there is this `ActsFatras::Barcode` type as well...

But I think I will reimplement this anyway with this `dfe::NamedTupleCsvWriter`, so maybe its a good idea to WIP this PR.

(Btw, how can I do this? Just put WIP in the title? Or click this 'convert to draft' link in the top right?)

**Comment by msmk0** [comment]
> I think this is not so easy with the `CsvSimHitWriter` / `CsvSimHitReader`, because they depend on Fatras and the Reader checks for the existence of some simulation files on construction, and there is this `ActsFatras::Barcode` type as well...

Fatras has no additional external dependencies and is always build when the examples are build. The `Barcode` can be default initialized. I am not sure what simulation files you refer to? The reader/writer always read/write a single file per event.

> (Btw, how can I do this? Just put WIP in the title? Or click this 'convert to draft' link in the top right?)

I'll add the WIP label.

**Comment by benjaminhuth** [comment]
In the constructor there is a comment: `// TODO check that all files (hits,cells,truth) exists`
But it seems I have overlooked that `TODO` flag, and thought that is what this function is actually doing... 

Ok, I'll try if it works with the `SimHitReader` / `SimHitWriter`...

**Comment by msmk0** [comment]
> In the constructor there is a comment: `// TODO check that all files (hits,cells,truth) exists`
> But it seems I have overlooked that `TODO` flag, and thought that is what this function is actually doing...

That comment should not be there. I see the confusion.

**Pull request closed without merging**
