### PR TITLE
fix: typo fixes and name change

### PR DESCRIPTION
**Pull request by asalzburger**
This mini-PR fixes a type in 6 files & changes the name of the `GridSurfaceMaterial` frame class.

### CODE REVIEW

**Comment by asalzburger** [comment]
Need to add an exclusion rule for doxygen.

**Review by andiwand — APPROVED** [review]
lgtm :+1:

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [115285158e5b01eb111d6047057eb7fec15eb12f]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35459658) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6772236)!

**Comment by andiwand** [comment]
Not sure if the Athena build fail is related but the rename might be breaking in any case?

**Pull request merged**
