### PR TITLE
Introducing TGeoVGM Plugin

### PR DESCRIPTION
**Pull request by asalzburger**
This PR makes it optional to use VGM (https://github.com/vmc-project/vgm) to convert `TGeoGeometry` into `Geant4` for GeantinoRecording.
VGM will allow:
   * build `Geant4` geometries from TGeo
   * `TGeo` from `GDML`

The new `ACTS_BUILD_EXAMPLES_VGM` is not planned to be included into `ACTS_BUILD_EVERYTHING` at this stage.

It has been successfully tested with the sPhenix TGeometry, but does not work with the ATLAS Geometry, as Material definitions are corrupted in the latter.

### CODE REVIEW

**Comment by asalzburger** [comment]
I think the label-bot wants to play with me ...

**Comment by asalzburger** [comment]
@paulgessinger - is there an issue with the label bot ? I can't get rid of the Triange

**Comment by asalzburger** [comment]
Hey @msmk0 - could you have a look if the CMAKE flag setting, etc. is ok with you?

**Comment by asalzburger** [comment]
Just, saw, this needs another protection for `TGEO plugin` to be defined.

**Comment by paulgessinger** [comment]
> @paulgessinger - is there an issue with the label bot ? I can't get rid of the Triange

The triage label gets set if none of the category labels are set, such as Bug, New Feature and so on. I think the labels you added where all not on that list, so the bot re-added the triage label.

**Comment by msmk0** [comment]
@asalzburger I checked the [LCG info page](lcginfo.cern.ch) and vmc-/vgm does not appear as a package. Is there some other way to support this feature. Could e.g [ROOT Virtual Monte Carlo](https://root.cern/doc/master/group__vmc.html) provide the same features?

**Comment by asalzburger** [comment]
> @asalzburger I checked the [LCG info page](lcginfo.cern.ch) and vmc-/vgm does not appear as a package. Is there some other way to support this feature. Could e.g [ROOT Virtual Monte Carlo](https://root.cern/doc/master/group__vmc.html) provide the same features?

I am not sure I want to go all-in with ROOTM VMC ... I will have a look though.

**Comment by paulgessinger** [comment]
This here is about VGM, but not necessarily about VMC, right?

**Comment by msmk0** [comment]
Yes, probably. My question is just whether the functionality provided by the standalone VGM package could also be provide via an already existing dependency.

**Comment by asalzburger** [comment]
Closing for now.

**Pull request closed without merging**
