### PR TITLE
Backport v0.27: Introduce bfield caching in vertexing and remove refitAfterBadVertex AMVF option

### PR DESCRIPTION
**Pull request by baschlag**
This PR is similar to #306 but targets the release v0.27 branch.

### CODE REVIEW

**Comment by msmk0** [comment]
This PR changes the interfaces of the existing code quite significantly. Although we do not (yet) give any guarantee on API stability, this is not just a minor bugfix. I think we should reconsider adding this directly to 0.28.0 instead without any backports.

**Comment by paulgessinger** [comment]
The reason for the backport is we can get it in quicker, as 27 will potentially require additional changes. We currently don’t consider API changes (or backward compatibility, for that matter) for our versioning, so I think we can go ahead with this one.

**Comment by paulgessinger** [comment]
@baschlag can you cherry pick the commit from https://github.com/acts-project/acts/pull/311 real quick so that the CI runs here?

**Comment by paulgessinger** [comment]
My approval doesn't count due to the cherry picked commit. I'm overriding this, however.

**Pull request merged**
