### PR TITLE
refactor!: Unify floating point type for chi2 in Track(State)

### PR DESCRIPTION
**Pull request by paulgessinger**
This was previously (not really intentionally) different.

### CODE REVIEW

**Comment by paulgessinger** [comment]
I'm changing the track state type to float first. I'm guessing this has an impact on the output, but let's see.

**Comment by paulgessinger** [comment]
Seems like output hashes change (makes sense), but physmon is unchanged.

**Review by andiwand — APPROVED** [review]

**Comment by benjaminhuth** [comment]
Is this breaking actually? Because it touches the concept and so on?

**Comment by paulgessinger** [comment]
@benjaminhuth Depends I guess.

**Comment by paulgessinger** [comment]
Failures after #2094 went in, as this still expects the other type.

**Comment by tboldagh** [comment]
Just in case this would need to be changed once more is there some Acts::Scalar type for float that could be used instead of explicity type?

**Comment by paulgessinger** [comment]
@tboldagh There is, but I'm wondering if that makes sense. Is the goal really to have **everything** use the same precision? I can't imagine we would actually ever need `double` for things like this $\chi^2$ value.

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [e956bc91b75549b96ed775844a9cc9f251a03060]
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6452148)!

|status|job|
|------|---|
|:red_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33788468) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsBenchmarkWithSpot.sh 8 100](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786800) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786799) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateAmbiguityResolution.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786798) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786797) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786796) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786795) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786794) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786793) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786792) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786791) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786790) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786789) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786788) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786787) |
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786786) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786785) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33786784) |

**Comment by tboldagh** [comment]
> @tboldagh There is, but I'm wondering if that makes sense. Is the goal really to have **everything** use the same precision? I can't imagine we would actually ever need `double` for things like this 
> χ2 value.

I was acually suggesting (indirectly and eveidently not very suggestive way) that a type: Acts::SmallScalar could be defined and used in this case. 
(the name sould be better of course).

**Comment by paulgessinger** [comment]
@tboldagh Seems like a wider discussion. Should we merge this to start with so we can land it in Athena soon?

**Comment by tboldagh** [comment]
> @tboldagh Seems like a wider discussion. Should we merge this to start with so we can land it in Athena soon?

Yes. Definitely.

**Review by tboldagh — APPROVED** [review]
Yes, this looks alright. 
Maybe I tag @CarloVarni - we will need to update xAOD class when this arrives in ATLAS.
This is breaking change (in a not so pleasent way - missing update will result in quite obscure runtime issue). If I understood well the discussion at last ACTS developers, there was plan to flag such breaking changes.

**Review by andiwand — APPROVED** [review]

**Comment by timadye** [comment]
Just to be clear, the effect of this PR is that the *TrackState chi2 type changes from double to float*, right?

The [v31.0.0 release notes](https://github.com/acts-project/acts/releases/tag/v31.0.0) has it the other way round in the **Breaking** section. Can the release notes be fixed, or it made clear at the top of this PR?

**Comment by paulgessinger** [comment]
@timadye My mistake, sorry!

**Pull request merged**
