### PR TITLE
feat: material validation using core components (MM6)

### PR DESCRIPTION
**Pull request by asalzburger**
This PR introduces (optimally navigation-less) material validation using core components.

It agrees very with the propagation based one, see below:

Screenshot 2024-04-11 at 16 34 25

This PR now enables full support for `BinnedSurfaceMaterial` and `HomogeneousSurfaceMaterial` for Gen1 and Gen2 geometry.

While #3094 and #3109  enabled the creation of `.json` and `.root` maps from both Gen1 and Gen2 material, this one allows to test them.

E.g. for the ODD:

*Gen1 geometry:*
```sh
python ~/Documents/work/dev/acts-grid-material-prs/Examples/Scripts/Python/material_validation_core.py -o odd_gen1_material_validation_root -n 1000 -t 1000 -m odd_gen1_material_maps.root
```

*Gen2 geometry:*
```sh
python ~/Documents/work/dev/acts-grid-material-prs/Examples/Scripts/Python/material_validation_core.py -o odd_gen2_material_validation_root -n 1000 -t 1000 -m odd_gen2_material_maps.root --experimental
```

### CODE REVIEW

**Comment by asalzburger** [comment]
Hey @ssdetlab you mind having a look at this, please?

**Review by ssdetlab — COMMENTED** [review]
The actual material validation part looks good to me. 

However, I'm a bit concerned with the fact the `DetectorMaterialHelper` namespace is basically unusable with the `Detector`s that are constructed via the builder pipeline. The `DetectorBuilder::construct()` returns only the constant access to the `Detector`, so the namespace functions are incompatible. We can easily solve this by omitting the `const` requirement in the `contruct`, but maybe there's a better way.

As a side note, can we introduce two interfaces, overloading the bracket, and inherit the `SurfaceMatrialAssigner` and the `VolumeMaterialAssigner` from them? This will automatically open the way to introduce some kind of `MaterialProvider` to the `InternalStructureBuilder`s.

**Comment by asalzburger** [comment]
> The actual material validation part looks good to me.
> 
> However, I'm a bit concerned with the fact the `DetectorMaterialHelper` namespace is basically unusable with the `Detector`s that are constructed via the builder pipeline. The `DetectorBuilder::construct()` returns only a constant access to the `Detector`, so the namespace functions are incompatible.
> 
> I think that we can resolve it if we introduce two interfaces that overload the bracket, and inherit the `SurfaceMatrialAssigner` and the `VolumeMaterialAssigner` from them. This will automatically open the way to introduce some kind of `MaterialProvider` to the `InternalStructureBuilder`s and will allow to avoid the `assignMaterial` for the builder-pipeline `Detector`s material validation.

You're absolutely right - this should be dealt with differently.

**Comment by ssdetlab** [comment]
Yes, I see. Looks pretty clean to me.

**Review by ssdetlab — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [1246c91d213f2082ad61c9d090c7379bdd377ff5]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38546134) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7319373)!

**Pull request merged**
