### PR TITLE
fix: Missing Include in CuboidVolumeBuilder

### PR DESCRIPTION
**Pull request by CarloVarni**
Self-Explanatory

### CODE REVIEW

**Review by benjaminhuth — APPROVED** [review]
Looks good!

**Comment by benjaminhuth** [comment]
I've restarted the failed jobs, let's hope it runs through this time!

**Comment by CarloVarni** [comment]
great @benjaminhuth the CI has indeed succeeded. Thanks! It looks though the automerge didn't happen?

**Comment by benjaminhuth** [comment]
The PR *was* enqueued at 2nd position in the automerge list, but now #1771 has been merged and it should be 1st place now. You chan check the queue position by hovering the `kodiakhq: status` in  the CI overview once the checks run through sucessfully :)

**Comment by paulgessinger** [comment]
Indeed, it's now reached the front of the merge train 🚂

**Pull request merged**
