### PR TITLE
fix: Fix FPEOVF in `RootParticleWriter`

### PR DESCRIPTION
**Pull request by andiwand**
I run into a few occasions where `float -> double` caused an FPEOVF. In this PR I change the output precision accordingly.

Discovered in https://github.com/acts-project/acts/pull/2232

### CODE REVIEW

**Review by paulgessinger — APPROVED** [review]
Ok. The alternative would be to wrap all of them into the `float` range. I don't think we actually have values that meaningfully exceed `float`.

**Comment by andiwand** [comment]
I was not sure why this occurred. Maybe G4 produces a max double in some cases. I will do the float wrapping tho so I do not have to change the reference

**Comment by andiwand** [comment]
@paulgessinger can you re-approve?

**Review by paulgessinger — APPROVED** [review]
🚀

**Pull request merged**
