### PR TITLE
Introduce SurfaceArray auto binning

### PR DESCRIPTION
**Pull request by asalzburger**
This PR (will be cherry-picked after #270 went in), introduces automated binning optimisation for Layers built with the TGeoLayerBuilder, it also adapts the options and response file format.

The explanation of latter will come as a dedicated PR that establishes more how-to-do guides for the Examples.

For the moment it is up for discussion.

For the ATLAS ID Pixels, this autobinning reduces the unbinned running time  from initially
```bash
15:32:10    Sequencer      INFO      Processed 100 events in 6.106145 s (wall clock)
15:32:10    Sequencer      INFO      Average time per event: 60.653672 ms/event
```
to:
```bash
15:25:27    Sequencer      INFO      Processed 100 events in 1.569797 s (wall clock)
15:25:27    Sequencer      INFO      Average time per event: 15.263704 ms/event
```
for 100k partlices.

It does not have an effect on the Generic detector that is already rather optimally binned.

### CODE REVIEW

**Comment by paulgessinger** [comment]
In principle we also have Auto binning in SurfaceArrayCreator, how does this fit in there?

**Comment by asalzburger** [comment]
> In principle we also have Auto binning in SurfaceArrayCreator, how does this fit in there?

You still had to tell how many bins in phi and z, or r and phi, r as far as I could tell, the SurfaceArray could not find that out. That's what this PR does, and then lets the SurfaceArray fill the bins.

**Comment by paulgessinger** [comment]
I think I actually wrote a number of tests for that back when I refactored it.

**Comment by asalzburger** [comment]
> I think I actually wrote a number of tests for that back when I refactored it.

Hmmm, when I used the TGeoParser and translate TGeoDetectorElements into SurfaceArray, I always ended up with a 1x1 array, because I did not set any nPhi, nZ parameters (and the default 1 was taken). Are you saying there's a parsing module inside the SurfaceArray that would do that for me?

**Comment by paulgessinger** [comment]
In surface array creator there should be, yeah. I actually assed system how to tell it which modules to consider “equivalent” for binning (basically strip pairs). Before, this was only on numerical position, with my change from back the you can provide a function that does whatever you want. 

As for why this didn’t work in TGeo, maybe the layer builder calls into the SAC without allowing that? Could be the matcher is not set or doing the wrong thing.

**Comment by asalzburger** [comment]
Let me check then, no reason to duplicate functionality then!

**Comment by asalzburger** [comment]
Hey @paulgessinger - I see there are two different SurfaceArray methods, I will try both of them out, with the new SurfaceArray visualisation we should see immediately how/if the autobinning works.

**Comment by asalzburger** [comment]
Hey @paulgessinger - you were right, the SurfaceArrayCreator does a very similar job, so this PR is not needed in this way, will retract it.

```shell
10:16:44    Sequencer      INFO      Processed 100 events in 1.843989 s (wall clock)
10:16:44    Sequencer      INFO      Average time per event: 17.967247 ms/event
```

This is with the SurfaceArrayCreator auto-binning.

BTW, first time we did beat `Eigen`, I tried to change the `intersect` method from the `PlanarHelper` to use `Eigen::Hyperplane` and `Eigen::ParameterizedLine` and the latter is significant slower (probably as it needs two additional object instantiation).

**Pull request closed without merging**
