### PR TITLE
fix: Iterative Vertex Finder algorithm updated for seed vertex at z = 0

### PR DESCRIPTION
**Pull request by rockybala**
Hi @baschlag and @asalzburger, Sorry I accidentally closed the last pull request while making some changes. Creating this new request. @baschlag, yes the addition of this break statement is the only change that I have done in ACTS code. The matrix inversion that I talked about earlier was in Athena. 

Please comment!

### CODE REVIEW

**Comment by baschlag** [comment]
I have one comment in the code that needs to be addressed and please fix the format. Good to see that we have this bug fix in afterwards! Thanks a lot!

**Comment by rockybala** [comment]
All the tests except 'review-required: master' have passed. @baschlag, please check.

**Comment by baschlag** [comment]
Hi. Can you please address the comment I have made on your code change? We should not check for 0 here as a breaking condition but instead for the vertex constraint z position, just as we do in the AMVF. 
Also please rebase your code. Thanks!

**Comment by baschlag** [comment]
Looks good to me. As discussed in private with @rockybala, I would first like to see the validation plots with the latest changes before approving. If the latest changes don't change the performance, I will approve and I'm happy to see this going in.

**Comment by rockybala** [comment]
Hi @baschlag, Please find the validation plots in the attached slides for 1000 events. 
[Athena_IVF_wrapper_ValidationPlots_Dec18.pdf](https://github.com/acts-project/acts/files/5718993/Athena_IVF_wrapper_ValidationPlots_Dec18.pdf)

Please let me know if you have any question/suggestion.

Thanks

**Review by baschlag — APPROVED** [review]
Looks good to me. I approve 👍

**Comment by baschlag** [comment]
@rockybala Can you rebase your branch? It looks good and I think this can go in

**Comment by baschlag** [comment]
Can somebody please merge this (e.g. @paulgessinger or @asalzburger)? Codecov failure can be ignored I guess.

**Pull request merged**
