### PR TITLE
Fix ITk navigation

### PR DESCRIPTION
**Pull request by asalzburger**
Cherry-picked version of #113 (see description there) as a start, in order to make everything working, I have had to:

- [x] change the `ProtoLayer` to use the `Extent` object of the `Polyhedron`
- [x] add UnitTests to Surfaces for the correct extent
- [x] introduce a method to find out if you are on a hyperplane (and thus radial distance needs to be checked)

Ad a consequence, I removed A LOT of code from the `LayerCreator`, which makes it way more readable, particularly the envelope handling is now done at one single space.

### CODE REVIEW

**Comment by Corentin-Allaire** [comment]
I have been trying to do the material mapping and it didn't work. Apparently it seem that there is no material decorator for TGeoDetector. Adding it by hand in BuildTGeoDetector seem to fix the problem, I should have material mapping plot with ITk available this afternoon.

**Comment by asalzburger** [comment]
> I have been trying to do the material mapping and it didn't work. Apparently it seem that there is no material decorator for TGeoDetector. Adding it by hand in BuildTGeoDetector seem to fix the problem, I should have material mapping plot with ITk available this afternoon.

I see, we should add a decorator then, of course.

**Comment by asalzburger** [comment]
And I have to fix some build errors.

**Comment by Corentin-Allaire** [comment]
I can make a branch on top of this one with the decorator. Since I also need to add the TGeo version of the Mapping examples.
PS : The material map is now good !
Val_mat_map

**Comment by asalzburger** [comment]
Putting back to WIP: The `ProtoLayer` does not yet yield the correct radial extension.

**Comment by asalzburger** [comment]
This is finally ready for reviewing.

**Comment by asalzburger** [comment]
@Corentin-Allaire - as you have been running the material mapping example on top of this, can you do again and review, please?

**Comment by paulgessinger** [comment]
Can you check if updating the branch fixes the coverage job failing with #181 merged?

**Comment by asalzburger** [comment]
> Can you check if updating the branch fixes the coverage job failing with #181 merged?

Will check, thanks!

**Comment by asalzburger** [comment]
I do not understand why the CI went all yellow again, pushing a new commit.

**Comment by asalzburger** [comment]
Hey @Corentin-Allaire - now finally this is ready for review.

**Comment by asalzburger** [comment]
> Can you check if updating the branch fixes the coverage job failing with #181 merged?

If it's not obvious: it did actually fix the problem.

**Comment by Corentin-Allaire** [comment]
I finish retesting it and the mapping works fine ! As soon as this PR get merged I will open a new one to add the decorator and the mapping examples with TGeo.

Here are two nice plot showing the mapping :
Val_mat_map
[Ratio_Val_geant_mat_X0_Eta.pdf](https://github.com/acts-project/acts/files/4593334/Ratio_Val_geant_mat_X0_Eta.pdf)

**Comment by asalzburger** [comment]
> I finish retesting it and the mapping works fine ! As soon as this PR get merged I will open a new one to add the decorator and the mapping examples with TGeo.
> 
> Here are two nice plot showing the mapping :
> Val_mat_map
> [Ratio_Val_geant_mat_X0_Eta.pdf](https://github.com/acts-project/acts/files/4593334/Ratio_Val_geant_mat_X0_Eta.pdf)

Excellent, once you are happy with it - press the the approve button :-)

**Comment by paulgessinger** [comment]
Codecov runs, but doesn’t set the status check :/

I’m overriding.

**Pull request merged**
