### PR TITLE
refactor: Use pointer for (C)KF inputMeasurements

### PR DESCRIPTION
**Pull request by XiaocongAi**
This PR changes the `inputMeasurements` in (C)KF actor to use pointer. This could save the data copy time vastly.

### CODE REVIEW

**Comment by XiaocongAi** [comment]
A comparison of the timing test W/O the change below:
image
image

**Comment by gagnonlg** [comment]
Hello @XiaocongAi , just a suggestion: `std::unique_ptr` would probably be safer here. https://en.cppreference.com/w/cpp/memory/unique_ptr

**Review by asalzburger — APPROVED** [review]
Wow, looks like we spent a lot of time copying into containers, right?

As discussed: wherever we hit a performance wall, we should use bare pointers, etc.

Can you please specify though that the ownership of the container is NOT with the KalmanActor?

**Comment by asalzburger** [comment]
> Hello @XiaocongAi , just a suggestion: `std::unique_ptr` would probably be safer here. https://en.cppreference.com/w/cpp/memory/unique_ptr

Hi, I have had a similar comment bout, however, I am not sure a `std::unique_ptr` would work, as you get the inputMeasurements object and then just dereference it?

Let's try to do the following:
- if there's really only one unique measurement container per KF/CKF run, then yes, we should try to make a `unique_ptr`.
@XiaocongAi - can you clarify this, please?

**Review by asalzburger — CHANGES_REQUESTED** [review]
We should try to clarify the ownership of the container.

**Comment by XiaocongAi** [comment]
> > Hello @XiaocongAi , just a suggestion: `std::unique_ptr` would probably be safer here. https://en.cppreference.com/w/cpp/memory/unique_ptr
> 
> Hi, I have had a similar comment bout, however, I am not sure a `std::unique_ptr` would work, as you get the inputMeasurements object and then just dereference it?
> 
> Let's try to do the following:
> 
> * if there's really only one unique measurement container per KF/CKF run, then yes, we should try to make a `unique_ptr`.
>   @XiaocongAi - can you clarify this, please?

Yes, the `inputMeasurements` is created per KF/CKF invocation. The KF/CKF `fit`/`findTracks` function has ownership of the `inputMeasurements`. The Kalman actor just deference it without any ownership of it. Since we know that the Kalman actor is created inside the `fit`/`findTracks`, I guess we should be safe with a bare pointer.

**Review by asalzburger — APPROVED** [review]

**Pull request merged**
