### PR TITLE
fix: Protection against wrong configuration of Seed finder config

### PR DESCRIPTION
**Pull request by CarloVarni**
In case a misconfiguration of the `SeedFinderConfig`  happens, and the `seedFilter` is a nullptr, the code crashes.

This PR adds a protection against this eventuality. This happens in the `toInternalUnits` function, that now takes responsibility for checking the validity of its parameters.

It checks that the seedFilter is not a `nullptr` and that its config is already in internal units.

### CODE REVIEW

**Review by paulgessinger — APPROVED** [review]
Looks good to me. You were wondering if we ever want to actually configure the finder without the filter, I guess we don't? Thoughts @LuisFelipeCoelho ?

**Comment by andiwand** [comment]
looks like our tests rely on this :thinking:

**Comment by CarloVarni** [comment]
ok, then I'll get a look at the failures here and fix them. It looks like indeed we have situation where the filter is not set

**Comment by CarloVarni** [comment]
I forgot in the precious commit to propagate the changes in the SeedingAlgorithm example to this MR. Now it all works

**Review by andiwand — APPROVED** [review]
great, thank you!

**Review by paulgessinger — APPROVED** [review]
This whole "internal units" mechanism is a bit of a crux that we should be looking to remove. That's independent of this change though.

**Pull request merged**
