### PR TITLE
Refactor the track parameters concepts

### PR DESCRIPTION
**Pull request by msmk0**
Split the previous `ParameterConcept` into `BoundTrackParametersConcept` and `FreeTrackParametersConcept` with a consistent implementation. The names are chosen to be consistent with the naming scheme for the track parameters in #151. Definitions are moved to the `Concepts` namespace as discussed in #42.

Assert that the concrete track parameters classes satisfy the concepts.

This is the first smaller PR split from #298.

### CODE REVIEW

**Comment by FabianKlimpel** [comment]
This looks good to me. Just one question before the approve: Why didn't you test the other functions? Aren't they used anywhere?

**Comment by msmk0** [comment]
> :

**Comment by msmk0** [comment]
> This looks good to me. Just one question before the approve: Why didn't you test the other functions? Aren't they used anywhere?

Which other functions? I am not quite sure what you are referring to.

**Comment by FabianKlimpel** [comment]
> > This looks good to me. Just one question before the approve: Why didn't you test the other functions? Aren't they used anywhere?
> 
> Which other functions? I am not quite sure what you are referring to.

I mean the `getParameterSet`, `uncertainty` and `get` methods.

**Pull request merged**
