### PR TITLE
feat: update ODD version

### PR DESCRIPTION
**Pull request by asalzburger**
This updates to the new ODD version, which will change the physics output ... we can use this PR to discuss if the changes are reasonable and eventually update the references then.

### CODE REVIEW

**Comment by asalzburger** [comment]
Ok, differences are really marginal, the slight changes in the DD4hep description make already slightly different truth particles.

**Comment by paulgessinger** [comment]
Can we hold this until Monday?

**Comment by asalzburger** [comment]
I've updated the material maps file - which now should include the beam pipe

**Comment by asalzburger** [comment]
Hey @paulgessinger  - the truth tracking shows a strong improvement in the `d0` pulls and also some improvement in the resolution, so - indeed - the beam pipe translation was missing and adding it brings a good next step to pulls -> 1

https://herald.harbinger.gessinger.dev/view/acts-project/acts/893582628/truth_tracking.html#pullwidth_d0_vs_eta

**Comment by asalzburger** [comment]
Mmmmm, it looks like it was the omission of the time component that caused the improvement

**Comment by paulgessinger** [comment]
Hm, yeah the time breaks completely. Do you understand what that's coming from?

**Comment by andiwand** [comment]
I disabled time measurements on ODD master some time ago because this fixed a bunch of issues downstream. I think this can be reverted now since we fixed a bunch of related bugs

**Comment by asalzburger** [comment]
> I disabled time measurements on ODD master some time ago because this fixed a bunch of issues downstream. I think this can be reverted now since we fixed a bunch of related bugs

Yes, but `acts` didn't use the head of ODD/main - I think we should still investigate a bit.

**Pull request closed without merging**
