### PR TITLE
refactor: Extra geant4 options

### LINKED ISSUE #465: Expose Geant4 Particle Gun Properties
It would be useful if the particle gun properties were configurable and exposed to the user in `ActsExampleGeantinoRecording`. In `ActsExampleMaterialMapping` the propagator options are exposed and thus the user can configure things like the particle eta/phi/pT etc. in the material mapping stage, but a similar option does not exist for the actual Geantino mapping portion of the material mapping procedure.

It looks like the particle properties are set e.g. [here](https://github.com/acts-project/acts/blob/e9621d2f6a4cd08abb8d57b656e61d054200e1a0/Examples/Algorithms/Geant4/src/PrimaryGeneratorAction.cpp#L57) - but a manual override of these properties leads to some unexpected ROOT I/O warnings and errors. 

This is not an urgent issue - just a suggestion to improve the user interface for the material mapping

### PR DESCRIPTION
**Pull request by Corentin-Allaire**
The PR add a few more option to the geantino recording in the Example. 
We can now : 
  -change the position and spread of the generation vertex.
  -generate only in a specific range in eta and phi (I have been ask a couple of time in the past if that was possible).
  -choose to generate uniformly in eta or theta. 

Closes #465.

### CODE REVIEW

**Comment by Corentin-Allaire** [comment]
Also I just noted that this resolve issue #465.

**Comment by msmk0** [comment]
> Also I just noted that this resolve issue #465.

@Corentin-Allaire I updated the PR description so #465 get automatically closed.

**Comment by osbornjd** [comment]
Awesome! Thanks for the additional feature.

**Review by paulgessinger — APPROVED** [review]
LGTM

**Comment by asalzburger** [comment]
Just waiting for the build_performance to finish.

**Review by asalzburger — APPROVED** [review]

**Pull request merged**
