### PR TITLE
fix: navigator priority with negative boundary distance

### PR DESCRIPTION
**Pull request by andiwand**
trying to fix a bug discovered with fatras here https://github.com/acts-project/acts/issues/1385

in some special cases the propagation will get stuck in a loop as the navigator is flip-flopping the target boundary of two volumes. one ahead and one behind.

these changes reorder the priority of the boundaries. first we will target everything in propagation direction and only if there are none left we will allow opposite direction

### CODE REVIEW

**Comment by andiwand** [comment]
these changes seem to fix the fatras propagation errors seen here https://github.com/acts-project/acts/issues/1385 @paulgessinger 

I wonder if we could discard the wrong sign entirely because we would only end up stepping in the wrong direction?

**Comment by paulgessinger** [comment]
Hold this PR for a potential unit test addition, or merge as is @andiwand?

**Comment by andiwand** [comment]
> Hold this PR for a potential unit test addition, or merge as is @andiwand?

I will try to set one up today/tomorrow

**Review by paulgessinger — APPROVED** [review]
let's gamble, try merging.

**Pull request merged**
