### PR TITLE
feat: Harmonization of algorithm, reader and writer interfaces

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR harmonizes the algorithm, reader and writer interfaces to a large degree. They should now all accept the same constructor arguments, their configuration should be largely equivalent (ROOT r/w should take `filePath`, `fileMode` and `treeName`, where applicable, CSV r/w should take `inputDir`/`outputDir`, as we write one file per event.

Other changes include increased verbose output, and ROOT writers closing their `TFile`s in `endRun` (@Corentin-Allaire  and me discussed that this is generally desirable).

### CODE REVIEW

**Comment by paulgessinger** [comment]
I can split this up further, if necessary.

**Review by Corentin-Allaire — COMMENTED** [review]
Looks good to me. I do have a couple of comments : 
- you have replace cfg by config everywhere (which I agree with) but in that case shouldn't we also change m_cfg to m_config ? It doesn't have to be in this MR but I think that would be more consistent no ?
- In the configs you replace both inputFile and outputFile with FilePath. I think have only FilePath instead of both path and dir is a great idea but now it is not as obvious if we have an input or an output (it is implied but it feel it is always better to have explicit stuff).

**Comment by paulgessinger** [comment]
Thanks for looking at this.

1. The main reason I changed the arguments to the full words is that for python those become relevant when you do something like 

   ```python
   sequencer.addAlgorithm(MyAlgorithm(config=config)
   ```

   `m_cfg` is internal, and here I personally care much less about the naming. But yes, this could be changed as well.
2. I see your point. While I think just the fact that you're instantiating a reader or a writer should make clear what the purpose is, these could be changed to `inputFilePath` and `outputFilePath`, if you think that is better / necessary.

**Comment by Corentin-Allaire** [comment]
Concerning `inputFilePath` and `outputFilePath` I would say it depend on how painful on your side it would be to change if it is quick then I would do it for readability if not this is fine. Do you there could be a weird edge case where a reader/writer would need both an input and an output ?

**Comment by paulgessinger** [comment]
I don't think we have such an edge case, and if we added one, it would probably also be fine to only have **that** reader/writer have both `inputFilePath` and `outputFilePath`, rather than a single `filePath`.

**Comment by Corentin-Allaire** [comment]
You are right lets keep it this way then !

**Review by Corentin-Allaire — APPROVED** [review]

**Pull request merged**
