### PR TITLE
chore: Propagation 1, separate PropagatorOptions 

### PR DESCRIPTION
**Pull request by asalzburger**
This PR simply splits out the `PropagatorOptions` into a new file and removes useless comments from `ActionList` and `AbortList`.

### CODE REVIEW

**Comment by msmk0** [comment]
I understand the removal of the comments, but I do not see the reason why this should be split into a separate file? The propagator options are only used with the propagator, so if I want to include one I always need to include the other as well?

**Comment by asalzburger** [comment]
> I understand the removal of the comments, but I do not see the reason why this should be split into a separate file? The propagator options are only used with the propagator, so if I want to include one I always need to include the other as well?

I just wanted to avoid having super long header files. If we wanted to increase test coverage we can also just test the Options (if they are consistent e.g.).

**Comment by FabianKlimpel** [comment]
I'm fine with the changes but understand the ideas of both of you. Is this part of a bigger plan?

**Comment by asalzburger** [comment]
As discussed in meeting - closing.

**Pull request closed without merging**
