### PR TITLE
perf: Use sympy generated transport jacobians for sympy covariance transport

### PR DESCRIPTION
**Pull request by andiwand**
Apparently this got lost at some point. Until now we used the Eigen implementation of the jacobian transport even though a sympy version was already preset. I fixed the include and explicitly mentioned the `sympy` namespace.

This popped out of a recent profile I did on the track finding.

### CODE REVIEW

**Comment by andiwand** [comment]
image

**Review by paulgessinger — DISMISSED** [review]

**Comment by paulgessinger** [comment]
Hashes change, physmon seems happy. Can you update the references @andiwand?

**Comment by andiwand** [comment]
@paulgessinger I would like to merge https://github.com/acts-project/acts/pull/3648 first to avoid conflicts since I updated the references there already. Is this fine for you?

**Review by paulgessinger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [319f340243227ac784e35716d6545c842fb869eb]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/43999872) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/8209904)!

**Pull request merged**
