### PR TITLE
ITk Strip Endcap navigation

### PR DESCRIPTION
**Pull request by asalzburger**
The ITk navigation is currently broken in the Strip Encaps.

This PR needs a couple of steps:

- [x] Merge #82 in first
- [x] Import the code from: https://gitlab.cern.ch/acts/acts-framework/-/merge_requests/207
- [x] Import `ProtoLayer` changes using `Polyhedron::extent()`
- [x] Fix navigation/geometry

### CODE REVIEW

**Comment by asalzburger** [comment]
Screenshot 2020-04-21 at 10 19 11

**Comment by asalzburger** [comment]
Actually, it's the geometry which is wrong:

```sh
11:07:21    LayerCreator   VERBOSE   Creating a disk Layer:
11:07:21    LayerCreator   VERBOSE    - at Z position    = 2536.25
11:07:21    LayerCreator   VERBOSE    - from Z min/max   = 2536.17 / 2536.33
11:07:21    LayerCreator   VERBOSE    - with Z thickness = 2.16
11:07:21    LayerCreator   VERBOSE      - incl envelope  = 1 / 1
11:07:21    LayerCreator   VERBOSE    - with R min/max   = 867.012 (-1) / 968.235 (+1)
11:07:21    LayerCreator   VERBOSE    - with phi min/max = 0.0695201 / -0.029516
11:07:21    LayerCreator   VERBOSE    - # of modules    = 576 ordered in ( 1 x 1)
```

The inner radius is too small !

**Comment by paulgessinger** [comment]
I think I encountered this problem ~2 years ago :D

**Comment by asalzburger** [comment]
ITk-fixed

**Comment by asalzburger** [comment]
@Corentin-Allaire have a look, I think this works now ...

**Comment by Corentin-Allaire** [comment]
OK, I will have a try ! Which command did you use ?

**Comment by asalzburger** [comment]
> OK, I will have a try ! Which command did you use ?

```
./ActsExampleGeometryTGeo --geo-tgeo-filename ITk.root --geo-tgeo-worldvolume ITK_1 --geo-tgeo-bp-parameters 26. 3000. 0.8 --geo-tgeo-ringlayout 0 1 0 --geo-tgeo-ringtolerance 0. 5. 0. --geo-tgeo-nlayers 1 1 1 --geo-tgeo-clayers 1 1 1 --geo-tgeo-players 1 1 1 --geo-tgeo-nlayer-rmin 0. 135. 0. --geo-tgeo-clayer-rmin 0. 135. 350. --geo-tgeo-player-rmin 0. 135. 0. --geo-tgeo-nlayer-rmax 135. 350. 1200. --geo-tgeo-clayer-rmax 135. 350. 1200. --geo-tgeo-player-rmax 135. 350. 1200. --geo-tgeo-nlayernames Pixel::ECLayer Pixel::ECLayer SCT_ForwardMinus --geo-tgeo-clayernames Pixel::Layer Pixel::Layer SCT_Barrel --geo-tgeo-playernames Pixel::ECLayer Pixel::ECLayer SCT_ForwardPlus --geo-tgeo-nmodulenames SensorBrl SensorBrl ECSensor --geo-tgeo-cmodulenames SensorBrl SensorBrl BRLSensor --geo-tgeo-pmodulenames SensorBrl SensorBrl ECSensor --geo-tgeo-nmoduleaxes yzx yzx xyz --geo-tgeo-cmoduleaxes yzx yzx xyz --geo-tgeo-pmoduleaxes yzx yzx xyz --geo-tgeo-nlayer-rsplit 0. 15. 0. --geo-tgeo-nlayer-zsplit 10. 20. 35. --geo-tgeo-clayer-rsplit 25. 25. 35. --geo-tgeo-clayer-zsplit 0. 0. 0. --geo-tgeo-player-rsplit 0. 15. 0. --geo-tgeo-player-zsplit 10. 20. 35. --geo-subdetectors BeamPipe InnerPixels OuterPixels Strips -n1 
```

**Comment by paulgessinger** [comment]
Can you explain what the problem was, and how you fixed it?

**Comment by asalzburger** [comment]
Superseded by #127 (cherry pick) - closing this one here.

**Pull request closed without merging**
