### PR TITLE
fix: Update EventAction.cpp

### PR DESCRIPTION
**Pull request by andriish**
Fixes fixes https://github.com/acts-project/acts/issues/877

Briefly, the beam particles should have an end vertex and there should be no vertices w/o incoming particles.

### CODE REVIEW

**Comment by andriish** [comment]
I think this can be merged.

**Comment by paulgessinger** [comment]
This does not seem to compile.

**Comment by andriish** [comment]
Lines should be swapped

**Comment by paulgessinger** [comment]
Right. With this change, the output in fact does not contain `V -1 1 []` anymore.

Running e.g. `ActsExampleHepMC3Histogram` on the events produces a number of errors like
```
ERROR::ReaderAscii: too few vertices were parsed
292  vs  435 expected
ERROR::ReaderAscii: event parsing failed. Returning empty event
DEBUG(1)::Parsing failed at line:
HepMC::Asciiv3-END_EVENT_LISTING
```
however.

@FabianKlimpel ?

**Comment by andriish** [comment]
Exactly.  #910 and #911 are logically different fixes. But only together these will produce a correct output.

**Comment by paulgessinger** [comment]
Ah I see. Could you put them in one PR maybe?

**Comment by andriish** [comment]
Ok. Closing this one. Se #911

**Pull request closed without merging**
