### PR TITLE
fix: Quick fix `LineSurface` tolerance inconsistency in `globalToLocal`

### PR DESCRIPTION
**Pull request by andiwand**
This is meant as a quick fix for the problem I am experiencing in https://github.com/acts-project/acts/pull/2086. It seems like it also appeared somewhere else already and maybe in one of the recent issues.

The problem seems to be that the tolerance is not consistent between `intersection` and `globalToLocal`. Since these are used in sequence with the same tolerance `globalToLocal` will fail as it reports a higher distance than the `intersection`.

A proper fix would be to align the math of the intersection and conversion so the tolerance has the same meaning in both cases.

should also fix https://github.com/acts-project/acts/issues/2226

### CODE REVIEW

**Comment by andiwand** [comment]
logged into this issue again and this is the output I get

```
intersect distance 0.940883 position  7.57337e-05 -6.11766e-05      44.2963 momentum -0.949711  0.197314  -0.24314
globalToLocal distance 0.000101456 position  7.57337e-05 -6.11766e-05      44.2963 momentum  0.949711 -0.197314   0.24314
```

**Comment by asalzburger** [comment]
> logged into this issue again and this is the output I get
> 
> ```
> intersect distance 0.940883 position  7.57337e-05 -6.11766e-05      44.2963 momentum -0.949711  0.197314  -0.24314
> globalToLocal distance 0.000101456 position  7.57337e-05 -6.11766e-05      44.2963 momentum  0.949711 -0.197314   0.24314
> ```
> 
> you can see that both functions get the same input but conclude to a different distance.
> 
> @paulgessinger @asalzburger

There is a sign flip in the momentum, this looks like it's the cause.

**Comment by andiwand** [comment]
Nope.

```
intersect distance 0.940883 position  7.57337e-05 -6.11766e-05      44.2963 momentum -0.949711  0.197314  -0.24314
distance 0.000101456 position  7.57337e-05 -6.11766e-05      44.2963 momentum -0.949711  0.197314  -0.24314
```

I don't think the direction should make a difference in this case and it seems to not do so.

If I remember correctly there are a bunch of random sign flips in the navigation which might cause this inconsistency. But I don't think this is relevant now.

@paulgessinger @asalzburger

**Comment by asalzburger** [comment]
> Nope.
> 
> ```
> intersect distance 0.940883 position  7.57337e-05 -6.11766e-05      44.2963 momentum -0.949711  0.197314  -0.24314
> distance 0.000101456 position  7.57337e-05 -6.11766e-05      44.2963 momentum -0.949711  0.197314  -0.24314
> ```
> 
> I don't think the direction should make a difference in this case and it seems to not do so.
> 
> If I remember correctly there are a bunch of random sign flips in the navigation which might cause this inconsistency. But I don't think this is relevant now.
> 
> @paulgessinger @asalzburger

ok, understood - probably time to have a look at the code lines.

**Comment by andiwand** [comment]
linked https://github.com/acts-project/acts/issues/2226 in the description

**Comment by andiwand** [comment]
updated the hashes @paulgessinger

**Review by benjaminhuth — APPROVED** [review]

**Pull request merged**
