### PR TITLE
build: Improve traccc dependency loading

### PR DESCRIPTION
**Pull request by stephenswat**
This commit makes a few changes to the way some of the Acts R&D projects are loaded in Acts (i.e. detray, traccc, algebra-plugins), namely:

1. It adds code to load detray's dependencies if the Acts project is installed.
2. It updates the versions of detray and traccc so they are compatible.
3. It adds some documentation to the `thirdparty/` directory.
4. It refines the parameters for the CMake build systems of various projects to be more robust.

This commit comes from https://github.com/acts-project/acts/pull/3117.

### CODE REVIEW

**Comment by stephenswat** [comment]
Actually, this needs more integration with the `_acts_XXXX_version` mechanism.

**Comment by stephenswat** [comment]
Okay, this should now be good to go.

**Review by andiwand — COMMENTED** [review]
LGTM 👍

**Comment by stephenswat** [comment]
@andiwand any idea why policy-bot is refusing to accept this?

**Review by andiwand — APPROVED** [review]

**Comment by andiwand** [comment]
looks like I didn't approve 😅

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [0c376732c99f7a3bbb4b80d1652a28be6db24720]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/42044811) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7886150)!

**Pull request merged**
