### PR TITLE
build: add cmake code to find OnnxRuntime when using find_package(Acts)

### PR DESCRIPTION
**Pull request by benjaminhuth**
I recently did some experiments with the `OnnxPlugin`, and I found out that `find_package(Acts)` does not search for the `OnnxRuntime` dependency. This PR should fix this.
Since `OnnxRuntime` (as far as I know) does not provide a CMake configuration file, I found it useful to add an error message with instructions what to do if `OnnxRuntime` is not found (at least for me it was not directly clear what to do).

As a sidenote: I encountered another problem when using `find_package(Acts)` on my system. I had to enable `cmake_policy(SET CMP0057 NEW)` (my CMake version is 3.18.4). I'm not sure, if this is a problem that should be handled in Acts or by the user.

### CODE REVIEW

**Comment by msmk0** [comment]
I have seen that many packages with non-standard find modules for dependencies install them together with the CMake configuration. I suspect the same problem that you encountered for ONNX exists also for SYCL.

The CMake policy errors is weird.

**Comment by msmk0** [comment]
> I have seen that many packages with non-standard find modules for dependencies install them together with the CMake configuration. I suspect the same problem that you encountered for ONNX exists also for SYCL.
> 
> The CMake policy errors is weird.

**Comment by paulgessinger** [comment]
@msmk0 I thought we were going to merge this?

**Comment by msmk0** [comment]
Ups, misclicked.

**Review by msmk0 — APPROVED** [review]
@benjaminhuth Thanks for bringing this up. I will merge this as-is and we will try to add a cleaner solution later on. I opened #646 for this.

**Pull request merged**
