### PR TITLE
Remove misleading components from VolumeMaterialInteraction

### PR DESCRIPTION
**Pull request by FabianKlimpel**
This PR removes some components that are misleading in the context of the material interaction. In order to point out the meaning corresponding comments were added.

### CODE REVIEW

**Comment by FabianKlimpel** [comment]
In order to provide the required codecov, I added some tests to the `EigenStepper` errors in the `step()` method and one for the `VolumeMaterialInteraction`. Latter showed a possible risk multiple functions can be called on pointers without testing for `nullptr` - this was added, too

**Comment by Corentin-Allaire** [comment]
I had a look and everything seems good ! Thanks a lot for adding comments and the test for the VolumeMaterialInteraction. 

Can I ask you what the change in the eigen steper correspond to (if it is not too complicated/long to explain) ?

**Comment by FabianKlimpel** [comment]
> Can I ask you what the change in the eigen steper correspond to (if it is not too complicated/long to explain) ?

Codecov initially complained about several lines in `if`-branches that were not tested. I tried to go over them and add corresponding tests. However I couldn't find a possibility to reach this branch I removed afterwards as I realized (maybe you could double-check it?) that it is not possible. We require that `stepSizeScaling == 1` which means that `state.options.tolerance == 2. * error_estimate` (value assignment above). But since we have in the lambda above the boolean evaluation `error_estimate <= state.options.tolerance` for the while-loop in which the if statement is, we cannot reach it. (I hope it is understandable)

**Comment by Corentin-Allaire** [comment]
It make perfect sense thanks a lot !

**Pull request merged**
