### PR TITLE
fix: fill bounds variable in CsvTrackingGeometryWriter

### PR DESCRIPTION
**Pull request by asalzburger**
This PR fixes a copy-and-paste error in the `CsvTrackingGeometryWriter` where the bounds are not correctly filled.

There's not much more to say.

### CODE REVIEW

**Comment by asalzburger** [comment]
One-liner, @Corentin-Allaire can you have a look, please?

**Review by Corentin-Allaire — APPROVED** [review]
Uncontroversial fix. I approve !

**Comment by asalzburger** [comment]
> Uncontroversial fix. I approve !

I will have to push another small update, this `CsvWriter` is a bit out of date...

**Comment by Corentin-Allaire** [comment]
> > Uncontroversial fix. I approve !
> 
> I will have to push another small update, this `CsvWriter` is a bit out of date...

Sure Let me know when it is done. I can re-review afterward. This remind me that some of the root writer are also probably completely outdated, I should try to have a look.

**Pull request merged**
