### PR TITLE
fix: ensure there is at least one zBin

### PR DESCRIPTION
**Pull request by yslai**
Fixes the issue: https://github.com/acts-project/acts/issues/1111

### CODE REVIEW

**Review by robertlangenberg — APPROVED** [review]
Thanks for spotting, reporting and fixing the bug, the full package :)

**Comment by paulgessinger** [comment]
Hey @yslai, thanks for spotting this.

@LuisFelipeCoelho: can you review this PR?

**Comment by LuisFelipeCoelho** [comment]
This change is fine to me.
But I'm getting `no matching function for call to 'max'` so maybe change it to `int zBins = std::max(1, (int) std::floor((config.zMax - config.zMin) / zBinSize));` ?

**Comment by yslai** [comment]
> This change is fine to me. But I'm getting `no matching function for call to 'max'` so maybe change it to `int zBins = std::max(1, (int) std::floor((config.zMax - config.zMin) / zBinSize));` ?

Yes, updated. Thanks.

**Review by LuisFelipeCoelho — APPROVED** [review]

**Comment by paulgessinger** [comment]
@yslai can you fix the format?

**Comment by paulgessinger** [comment]
I pushed a formatting commit, @robertlangenberg or @LuisFelipeCoelho can you reapprove?

**Review by LuisFelipeCoelho — APPROVED** [review]

**Pull request merged**
