### PR TITLE
chore: rename NextNavigator to DetectorNavigator

### PR DESCRIPTION
**Pull request by asalzburger**
To distinguish between the `Navigator` that takes the `TrackingGeometry` and the one for the updated `Detector` description, this PR renames the `NextNavigator` to `DetectorNavigator` to make sure what is meant by that.

### CODE REVIEW

**Review by andiwand — APPROVED** [review]

**Comment by asalzburger** [comment]
@andiwand can you re-approve, please?

**Review by andiwand — APPROVED** [review]

**Comment by asalzburger** [comment]
Hey @paulgessinger @andiwand - I saw this now several times: the `clang-tidy` job finishes in 26 mins, but the ci-bridge is stalled since 11h ?

Is there a way to fix this?

**Comment by paulgessinger** [comment]
> Hey @paulgessinger @andiwand - I saw this now several times: the `clang-tidy` job finishes in 26 mins, but the ci-bridge is stalled since 11h ?
> 
> 
> 
> Is there a way to fix this?

Best guess is some webhook delivery fails or the status update API call doesn't get through

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/5934834)!

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219052) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219051) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219050) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219049) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsTrkSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219048) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219047) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219046) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219045) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219044) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219043) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219042) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219041) |
|:red_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219040) |
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219039) |
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219038) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219037) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31219036) |

**Comment by paulgessinger** [comment]
@CarloVarni is this an unrelated error?

**Comment by CarloVarni** [comment]
Hi @paulgessinger yes. The error is `AttributeError: No such flag: Tracking.doITkConversion` but that comes from the `AthenaConfiguration` package that we are not compiling in the acts-athena-CI... it's the already known python files issue that we have to fix.

Tomorrow this error will be gone.

We can already get rid of it by compiling `AthenaConfiguration` as well, but if we keep doing this we'll end up with a full build

**Pull request merged**
