### PR TITLE
fix: More precise track parameter estimation for high curvature tracks

### PR DESCRIPTION
**Pull request by beomki-yeo**
Calculation from #2211 without approximation arcsin.

I will put some plots later to estimate how correct the PR is compared to current calculation

Following is the plot for residual between track parameter estimation and truth value (for p and qop separately)

I tested with 
- three helix points generated at 200, 400, 600 mm of trajectory 
- the initial track direction in [1/sqrt(2),0,1/sqrt(2)], 
- B field: 2T in z-axis
- Repeat the same test from 0.1 GeV/c , 0.2 GeV/c , ... , 9.9 GeV/c

My impression is that the original track parameter estimation is not as bad as I imagined before this study. So I am not sure if we will want to proceed with the change eventually.

image

### CODE REVIEW

**Comment by beomki-yeo** [comment]
image

**Comment by andiwand** [comment]
do you know if this has any CPU performance implications?

**Comment by beomki-yeo** [comment]
I don't know the number exactly. I believe the performance won't change a lot because it is just having one more line with `arcsin` per track.

**Review by AJPfleger — CHANGES_REQUESTED** [review]
The math seems to be correct and I also don't see a need to look deeper in the performance change from the `asin`.

Could you update the hashes?

**Comment by andiwand** [comment]
@CarloVarni did some optimizations on this https://github.com/acts-project/acts/pull/2699

**Comment by CarloVarni** [comment]
From my side there are no objection to this. If this provides a more precise computation w.r.t. the current implementation, then we should go for it. I'm a little surprised @beomki-yeo that there are no changes in physics performance, I would have expected (minor) changes in the CKF output.

On the CPU impact, the estimation of the parameter from seeds is already very cheap. Even if there is a small increase due to this change that would be hardly relevant in the entire track reconstruction process. So I'd say we can go on with this.

**Comment by CarloVarni** [comment]
ok thanks @andiwand then I'm approving this

**Review by CarloVarni — DISMISSED** [review]

**Comment by andiwand** [comment]
@beomki-yeo can you update the hashes? and @AJPfleger needs to lower the red flag after this

**Review by AJPfleger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [28c31336ca89c7680a998cbd8acde90f4c2f4f60]
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7044593)!

|status|job|report|
|------|---|------|
|:red_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36972364)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969747)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969746)||
|:green_circle: | [test_ActsConversionWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969745)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969744)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969743)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969742)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969741)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969740)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969739)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969738)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969737)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969736)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969735)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969734)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969733)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969732)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969731)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969730)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969729)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969728)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969727)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969726)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969725)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/36969724)||

**Comment by paulgessinger** [comment]
The Athena output change seems to be related to this. We seem to be getting a single digit number of additional tracks. I think we can tolerate this.

(cc @CarloVarni)

**Pull request merged**
