### PR TITLE
ci: Turn on FORCE_ASSERTIONS

### PR DESCRIPTION
**Pull request by paulgessinger**
In #1182 I unfortunately set the wrong CMake option to turn the forces
assertions on.

This PR should fix this.

### CODE REVIEW

**Comment by stephenswat** [comment]
I looked into this, and it seems like the ROOT people have solved the issue in [this commit](https://github.com/root-project/root/commit/acfe6dc8476f1a06aab3d31b25e4e2bfa3003a02). Updating the ROOT version on the MacOS CI machine should fix this issue.

**Comment by paulgessinger** [comment]
> I looked into this, and it seems like the ROOT people have solved the issue in [this commit](https://github.com/root-project/root/commit/acfe6dc8476f1a06aab3d31b25e4e2bfa3003a02). Updating the ROOT version on the MacOS CI machine should fix this issue.
> 
> Edit: Version `510ff2e` of the MacOS dependencies (the latest one) still has an older ROOT without these fixes.

Unfortunately that is more complicated than I care to admit 😅

**Review by asalzburger — APPROVED** [review]
Trivial, approved.

**Comment by paulgessinger** [comment]
I managed to bump the macOS dependencies, let's see if that fixes the CI.

**Comment by paulgessinger** [comment]
Working now, can you reapprove @asalzburger ?

**Review by stephenswat — APPROVED** [review]
Going to go ahead and stamp this.

**Pull request merged**
