### PR TITLE
refactor: Replace magic seeding field in Examples

### PR DESCRIPTION
**Pull request by andiwand**
I believe this is not accurate anymore since we switched out the magic number in the seeding

https://github.com/acts-project/acts/pull/2132

### CODE REVIEW

**Comment by AJPfleger** [comment]
I looked how we introduced this number. First Appearance in Acts seems to be here (pre-PR time):
https://github.com/acts-project/acts/commit/fa68459b4ac8ce8606d7f734bf69f9613b2b8058

@paulgessinger suggests that the value could be the real ATLAS-field (maybe taken from Athena).

**Comment by andiwand** [comment]
> I looked how we introduced this number. First Appearance in Acts seems to be here (pre-PR time): [fa68459](https://github.com/acts-project/acts/commit/fa68459b4ac8ce8606d7f734bf69f9613b2b8058)
> 
> @paulgessinger suggests that the value could be the real ATLAS-field (maybe taken from Athena).

if I remember correctly @beomki-yeo found a magic number (300) in the seeding implementation which was an approximation for `c` and exchanged it with the physical value. but we never changed the field with compensated the difference

**Comment by AJPfleger** [comment]
I am still not sure, how the numbers relate. According to https://github.com/acts-project/acts/pull/2132 this relation should make sense `c * B = const`:

`299.792458 * 2 = 300 * 1.998616... ~ 300 * 1.99724` (quite off)
Using `c^2 * B = const`:
`299.792458^2 * 2 = 300^2 * 1.9972337... ~ 300^2 * 1.99724` (yes the rounding is wrong)
However, I don't understand the physical basis for this.

**Comment by andiwand** [comment]
it is only affecting the examples. I updated the ttbar vertexing histograms. they are quite noisy as they are low stat. otherwise it should be uncontroversial and we have one magic number less

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [0027d4c9bdc3654a83a1398b9b4245de18c709c2]
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6395720)!

|status|job|
|------|---|
|:red_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33467130) |
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466446) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466445) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466444) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466443) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466442) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466441) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466440) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466439) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466438) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466437) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466436) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466435) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466434) |
|:red_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466432) |
|:red_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33466431) |

**Pull request merged**
