### PR TITLE
ci: Add autodiff plugin to the enabled components in CI

### PR DESCRIPTION
**Pull request by paulgessinger**
This enables the Autodiff plugin in our main CI jobs. Depends on #587 and #592, so they should be merged first.

### CODE REVIEW

**Comment by paulgessinger** [comment]
FYI @benjaminhuth

**Comment by asalzburger** [comment]
I updated the branch after merging #592 - if everything runs through, I will merge this next.

**Comment by benjaminhuth** [comment]
Now where I look again on this problem and the changes, wouldn't it be a better solution to add the `AutodiffPlugin` to the `BUILD_EVERYTHING` CMake Flag in the root `CMakeLists.txt`, instead of adding it manually to the options list in the build routine?
I think if someone chooses `BUILD_EVERYTHING=ON`, he/she expects also the `AutodiffPlugin` to be built...

**Comment by asalzburger** [comment]
> Now where I look again on this problem and the changes, wouldn't it be a better solution to add the `AutodiffPlugin` to the `BUILD_EVERYTHING` CMake Flag in the root `CMakeLists.txt`, instead of adding it manually to the options list in the build routine?
> I think if someone chooses `BUILD_EVERYTHING=ON`, he/she expects also the `AutodiffPlugin` to be built...

Indeed an option, @paulgessinger what do you think?

**Comment by paulgessinger** [comment]
Ok

**Review by asalzburger — APPROVED** [review]

**Pull request merged**
