### PR TITLE
Contribution guide change

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR does a few things:

- Add `m2r` to sphinx. This allows including markdown files using the `.. mdinclude` directive. It is added in a way that keeps reCommonMark for everything else.
- Use this to pull in `CONTRIBUTING.md` from the repo root
- Modify the contributing guide to explicitly mention backport feature/bugfix, and remove the explicit style guide with a link to the style guide on RTD.

### CODE REVIEW

**Comment by paulgessinger** [comment]
@msmk0: image

**Comment by msmk0** [comment]
I stand corrected.

Have you considered converting it to restructured text (as just as `CONTRIBUTING` file) and use the a `docs/contribution_guide.rst` placeholder and in include it from there. This is done e.g. for the authors file and requires no additional module.

**Comment by paulgessinger** [comment]
I have not since I didn’t want to spend the time to convert it.

**Comment by msmk0** [comment]
> I have not since I didn’t want to spend the time to convert it.

If you want, I can do the conversion.

**Comment by paulgessinger** [comment]
Honestly, not sure why this is controversial. Either merge it, or close it. 
I didn't want to waste my time converting the markdown, but I you want to waste your time (and mine making this PR), then ok.

**Comment by msmk0** [comment]
It is not controversial. I just wanted to know if you would consider alternatives that do not add additional dependencies. I agree with you that it is probably not worth the effort.

I will merge this as-is.

**Pull request merged**
