### PR TITLE
refactor: remove division of vertex covariance with weight

### PR DESCRIPTION
**Pull request by felix-russo**
Removes the division of the vertex covariance matrix with a weight that depends on the annealing temperature.

I believe that the reasoning behind this practice is that the vertex covariance should decrease gradually with temperature. This seems however a bit random to me because

- the temperature is already considered in the track weights
- the `chi2` corresponding to the weight is set to the arbitrary value 1
- there is no documentation on this that I know of. For example, https://link.springer.com/book/10.1007/978-3-030-65771-0 on page 154, the authors only mention the inflation of the track covariance matrices `Vi`, see 
image

Let me know if I am missing something!

### CODE REVIEW

**Comment by paulgessinger** [comment]
Should we try to investigate where this comes from? @baschlag do you remember if this was discussed at some point?

**Comment by felix-russo** [comment]
I found the same line athena, might be helpful to for tracing where this comes from: https://gitlab.cern.ch/atlas/athena/-/blame/main/Tracking/TrkVertexFitter/TrkVertexFitters/src/AdaptiveMultiVertexFitter.cxx#L137

**Comment by baschlag** [comment]
Hi. This part was indeed just adopted from the original Athena implementation in order to guarantee numerical agreement between the ACTS and Athena version (which was needed for validating the code). So I think your changes look in fact very reasonable.

**Review by paulgessinger — APPROVED** [review]
Seems good to me then. Let's see what the CI says in terms of Athena outputs after we merge.

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6349055)!

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223601) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223600) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223599) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223598) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223597) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223596) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223595) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223594) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223593) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223592) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223591) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223590) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223589) |
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223588) |
|:red_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223587) |
|:red_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223586) |
|:red_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33223585) |

**Comment by felix-russo** [comment]
Hm.. What should we do?

**Comment by paulgessinger** [comment]
If we want to tag another non-major version this week, we might have to revert this. That ok for you?

**Comment by felix-russo** [comment]
Sure, as long as it gets in at some point :)
I will prepare the PRs

**Pull request merged**
