### PR TITLE
refactor: Refactor target direction logic in KF/CKF

### PR DESCRIPTION
**Pull request by andiwand**
Not sure what the use case for this was but to me it seems like the target propagation logic is flawed in KF/CKF. If we propagate to target from the last state the smoothing seems unnecessary. Also since the target surface is a perigee surface for us there are edge cases where the last state has a smaller "distance" to the perigee than the first one.

In general I'd say the user should take such a decision but this is too big of a change at the moment.

discovered with https://github.com/acts-project/acts/pull/2518

### CODE REVIEW

**Comment by Corentin-Allaire** [comment]
Hello I am teaching this week, so I will look at this on Monday if it is fine

**Comment by Corentin-Allaire** [comment]
I will need to cross check but does the target surface has to be a perigee surface at the beamline can't it be any aribitrary surface ? Because I can see a few use case where you would want to have it behind the last measurements.

**Comment by andiwand** [comment]
> I will need to cross check but does the target surface has to be a perigee surface at the beamline can't it be any arbitrary surface ? Because I can see a few use case where you would want to have it behind the last measurements.

I agree, it might be generally useful but the current implementation is unstable for our usual setup with the perigee in front of the first sensitive.

If the target surface is behind the last sensitive smoothing should not be necessary but is currently coupled to the target propagation.

The problem I encounter is that the perigee surface might be "closer" to the last track state VS the first track state because we intersect with the PCA and not a plane surface in that case. Apart from that it is not clear what happens if we cannot reach the target source or if we are not in the bounds.

These details should be handled by the user IMO because it would be way to complicated to handle all of them in a core algorithm.

**Comment by andiwand** [comment]
@paulgessinger @asalzburger @XiaocongAi is someone aware if users rely on this feature? @Corentin-Allaire is (rightfully) concerned that this will break user code

**Comment by Corentin-Allaire** [comment]
Hello I am teaching this week, so I will look at this on Monday if it is fine 

> @paulgessinger @asalzburger @XiaocongAi is someone aware if users rely on this feature? @Corentin-Allaire is (rightfully) concerned that this will break user code

To be more precise i there any users for which the target surface is not before the first layer (the main thing that would come to mind for me is test beam setup or maybe fix target)

**Comment by paulgessinger** [comment]
I believe @pbutti needs the last measurement surface, but I think he's picking it up manually anyway. Can you confirm?

**Comment by osbornjd** [comment]
I may be misunderstanding the use case, but it sounds like this also might affect cosmic track fitting where a cosmic ray traverses your entire detector and you want to the track parameters determined at some target surface outside the detector at an arbitrary location.

**Review by Corentin-Allaire — COMMENTED** [review]
Thanks a lot for your work andi ! I think for the time being this will work. I agree with you that in the futur having a separate module for the extrapolation is probably the way to go. 

I small point (and it is up to you) do you think it would be possible to add a target surface strategy option in our python binding ?

**Review by Corentin-Allaire — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6361896)!

|status|job|
|------|---|
|:red_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298488) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298487) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298486) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298485) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298484) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298483) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298482) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298481) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298480) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298479) |
|:red_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298478) |
|:red_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298477) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298476) |
|:red_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298475) |
|:red_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298474) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298473) |
|:red_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33298472) |

**Pull request merged**
