### PR TITLE
ci: Add pythia8 particles and vertices to physmon output

### PR DESCRIPTION
**Pull request by paulgessinger**
I'm investigating physmon seemingly randomly failing. By adding these outputs, I might be able to see if it's pythia producing different truth inputs to the chain, or if something else is wrong.

### CODE REVIEW

**Comment by paulgessinger** [comment]
It's green now again, anyway 🤷

**Review by andiwand — APPROVED** [review]

**Comment by andiwand** [comment]
plots changed again @paulgessinger

**Comment by paulgessinger** [comment]
Yes. Now that's what I was concerned about. Seems like Pythia8 seems to just produce different outputs some of the time... 

No idea how to approach this. Can double check the Pythia RNG setup, or alternatively I can try downgrading back to 310 or 311 (we went from 309 to 312) in the last update.

**Review by andiwand — APPROVED** [review]
lets put this in

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [05c0ebde4aa83baea3c716a3c79cf8481b65817b]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/41194314) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7750624)!

**Pull request merged**
