### PR TITLE
feat: Update ODD to v3.0.3 and small ODD fixes

### PR DESCRIPTION
**Pull request by asalzburger**
This updates the ODD to v3.0.3, which brings in a fix:

- the long strip sensors were different in front and back side
- the geometric config file works (was not working)

It fixes the problem of: 
- `Examples/Scripts/Python/geoemtry.py` crashing on default because of missing output folder

And enables the building of:
- `Examples/Scripts/Python/detector_creation.py`

*Note: small performance chances are explected*

### CODE REVIEW

**Comment by asalzburger** [comment]
As expected, this introduces fluctuations in the result due to the slight change of LongStrip description (fix that the sensors are identical).

**Comment by andiwand** [comment]
looked at the physmon output - looks uncontroversial to me

**Comment by asalzburger** [comment]
> looked at the physmon output - looks uncontroversial to me

Thanks, I will update the references then.

**Comment by andiwand** [comment]
superseded by https://github.com/acts-project/acts/pull/2992 @asalzburger ?

**Pull request closed without merging**
