### PR TITLE
feat: Add timing to vertex performance writer 

### PR DESCRIPTION
**Pull request by baschlag**
This PR adds the reconstruction time of primary vertexing directly to the root output performance file, allowing the produce plots like time vs. ntracks or time vs. pileup directly from the output root file.

### CODE REVIEW

**Review by asalzburger — COMMENTED** [review]
I think it's a nice thing to also be able to measure the timing, though if we introduce this, we should do it consistently, pinging @HadrienG2 here if he has some input.

**Comment by baschlag** [comment]
> I think it's a nice thing to also be able to measure the timing, though if we introduce this, we should do it consistently, pinging @HadrienG2 here if he has some input.

As already discussed, we use ```std::chrono``` also in many other places for performance measurements, if this was your concern.

**Comment by HadrienG2** [comment]
Yeah, the use of `std::chrono` is not bothering me either if that's the concern. I would personally not use `high_resolution_clock` since [cppreference advises against it](https://en.cppreference.com/w/cpp/chrono/high_resolution_clock), but that's a minor nitpick.

**Comment by baschlag** [comment]
> Yeah, the use of `std::chrono` is not bothering me either if that's the concern. I would personally not use `high_resolution_clock` since [cppreference advises against it](https://en.cppreference.com/w/cpp/chrono/high_resolution_clock), but that's a minor nitpick.

If you ask me to change it, I can do it. Just let me know :)

**Review by HadrienG2 — APPROVED** [review]
I just don't care enough :) Change it to steady_clock if you do, otherwise I'd just merge as-is.

**Comment by asalzburger** [comment]
Thanks @HadrienG2 for approving, will merge it in after updating.

**Review by asalzburger — APPROVED** [review]
Comments have been addressed appropriately

**Pull request merged**
