### PR TITLE
Add local-global roundtrip tests for surfaces

### PR DESCRIPTION
**Pull request by msmk0**
Add systematic tests to check that the local->global->local transformation gives back the same result.

### CODE REVIEW

**Comment by msmk0** [comment]
The tests fail at the moment and it is not quite clear to me why. It would be nice if someone could have a look and tell me if I am doing something wrong, e.g. in the setup.

**Comment by msmk0** [comment]
@asalzburger After playing around with the test limits, all tests now run through. The failures that I previously saw where all related to edge cases, e.g. theta=0/pi for the perigee surface. I exclude these now from the relevant test cases.

**Comment by asalzburger** [comment]
> @asalzburger After playing around with the test limits, all tests now run through. The failures that I previously saw where all related to edge cases, e.g. theta=0/pi for the perigee surface. I exclude these now from the relevant test cases.

That eases my mind a bit, indeed. I will review today.

**Comment by asalzburger** [comment]
I am fine merging this in, I just had one question for my understanding.

**Comment by msmk0** [comment]
> I see you use `8*std::numeric_limits<...>::epsilon()` - why 8?

Because using just `::epsilon()` lead to false positives. The `CHECK_CLOSE_OR_SMALL` check seems to require a bit larger test epsilon and the transformations can accumulate more numerical issues. I suspect due to the sin/cos/atan2 chain, but I do not know for certain.

**Comment by HadrienG2** [comment]
If there are trig functions involved, you indeed can't assume an output precision of 1 ULP. IEEE-754 doesn't guarantee that, and the GNU libm doesn't offer it.

Personally, I tend to avoid epsilon-based tolerances because that's focusing on what the machine does, not what you need, which in my opinion is taking the problem by the wrong end.

**Pull request merged**
