### PR TITLE
docs: adding Fatras description

### PR DESCRIPTION
**Pull request by asalzburger**
This PR adds the Fatras documentation consisting of
* Fatras simulation
* Digitisation
* Configuration

### CODE REVIEW

**Review by AJPfleger — COMMENTED** [review]
I think the new UnitTests should be in a separate PR.

**Comment by benjaminhuth** [comment]
@asalzburger I would suggest to bring this in in this state now, what do you think? Should we separate the unit test from this PR as @AJPfleger suggested or merge this directly?

**Comment by asalzburger** [comment]
Indeed, as suggested,  the new unit tests should be split off.

**Comment by asalzburger** [comment]
Unit tests are partly superseded, closing this one for now.

**Pull request closed without merging**
