### PR TITLE
build: Install third party FindXXX.cmake files

### LINKED ISSUE #646: Install custom CMake find modules
Some of the optional dependencies do not provide CMake config files and are instead found using custom CMake find modules. When installing Acts these custom CMake find modules must be installed as well. Otherwise, using some plugins from an Acts installation (e.g. Onnx or Sycl) will break due to missing dependencies.

_Originally posted by @msmk0 in https://github.com/acts-project/acts/issues/637#issuecomment-748293886_

### PR DESCRIPTION
**Pull request by benjaminhuth**
Fixes #646.

With this PR the files `FindOnnxRuntime.cmake` and `FindSYCL.cmake` are installed to the `${install_package_config_dir}` of Acts, so that these files can be used to find the corresponding components in `ActsConfig.cmake`. It also removes the verbose error message from PR #637.

I couldn't test if this works for SYCL, since I have not installed it on my system, but it definitively should work...

### CODE REVIEW

**Review by msmk0 — APPROVED** [review]
@benjaminhuth Thanks for the quick update. This looks good from my side and can go in as-is. I'll wait for the CI runs to go through and will merge it if there are no errors.

**Comment by msmk0** [comment]
@benjaminhuth You could try to add build steps for the downstream test project to the Sycl CI build.

**Comment by benjaminhuth** [comment]
Could you point me to the file, where the test project is defined? I couldn't see it on a quick search...
And is there a way to enable the CI on my fork?

**Comment by msmk0** [comment]
> Could you point me to the file, where the test project is defined? I couldn't see it on a quick search...

The CI jobs are defined in `.github/workflows/builds.yml`.

> And is there a way to enable the CI on my fork?

It should be automatically enabled, but I am not 100% sure. @paulgessinger Is that correct?

**Comment by benjaminhuth** [comment]
Ah, I had to activate something in the 'Actions' tab of Github. It seems Github deactivates actions on forks by default for some reason. Maybe this is a new behaviour, if it works for older forks by default.

Whatsoever, now I can try it out.

**Comment by msmk0** [comment]
> Whatsoever, now I can try it out.

You can either try to add it to this PR or introduce it as a separate one. Your choice.

**Comment by benjaminhuth** [comment]
Hmm, all this CI stuff requires a bit trial and error from my side.
I will commit it to this PR when it works, then we can merge it.

**Comment by benjaminhuth** [comment]
I encountered some difficulties while trying to setup the downstream project with SYCL in the CI:
* The downstream project seems to require to build Acts with `-D ACTS_BUILD_EVERYTHING=ON`
* But that does not seem to work on this `ghcr.io/acts-project/ubuntu2004_oneapi:v9` machine, the configure step of Acts fails because its not finding DD4hep

So, if I understand everything right, we need a downstream project which requires only the SYCL Plugin. This also would save build time I think. Or we could make the downstream project configurable what components it requires?

**Comment by paulgessinger** [comment]
Yeah, I only install the minimal dependencies in the SYCL image, since that already blows up the image size. @msmk0  and I discussed we'll go ahead with this without the downstream project. Ok?

**Comment by benjaminhuth** [comment]
Yes, I think this can go in. Even though the downstream project failed in total, I checked the cmd line output and it was able to find SYCL.

**Review by msmk0 — APPROVED** [review]

**Pull request merged**
