### PR TITLE
refactor!: Surface returns transform by value

### PR DESCRIPTION
**Pull request by asalzburger**
This PR tests how much performance loss we would experience when changing the return object of `Surface` objects from

```c++
const Transform& transform(const GeometryContext& gctx) const;
```

to 

```c++
Transform transform(const GeometryContext& gctx) const;
```

This change would allow us to create surfaces on the fly, (or at least their transforms) for e.g. Drift straws, etc.

Initial tests - running the propagation test only, which is relatively highly effected by this - shows.

### Propagation test

**without this change**
```sh
09:57:30    Sequencer      INFO      Average time per event: 19.184849 ms/event
```

**with this change**
```sh
09:56:55    Sequencer      INFO      Average time per event: 20.279401 ms/event
```
It indicates a 5% penalty in this workflow.

### Truth Tracking

```sh
14:07:33    Sequencer      INFO      Average time per event: 44.465655 ms/event
```

vs.

```sh
14:07:42    Sequencer      INFO      Average time per event: 45.216276 ms/event
```

So, closer to 2 % effect there, already interesting, I will do a full chain run as well.

### CODE REVIEW

**Comment by asalzburger** [comment]
> We probably want to run some workflows a number of times to characterize the performance. 5% seems non-negligible.

Yes, completely agree. I will run a full chain workflow later to see where we stand on that.

**Comment by paulgessinger** [comment]
Probably we should then also change this in `DetectorElementBase`.

**Comment by andiwand** [comment]
alternatively we could cache the transform in a `unique_ptr` or in a pool to avoid recomputation. but that would also be up for measurements if that actually happens a lot and if it makes a difference

**Comment by asalzburger** [comment]
Good news though everything seems to run through ...

**Comment by asalzburger** [comment]
> alternatively we could cache the transform in a `unique_ptr` or in a pool to avoid recomputation. but that would also be up for measurements if that actually happens a lot and if it makes a difference

I am not sure we should go for some lazy initialisation - I hope we can stick to a clean design: either object and copy or pre-construct and return by const ref.

**Comment by paulgessinger** [comment]
We could consider using an atomic pointer to model lazy initialization and caching of the transform.

Anyway, should we move forward with this, or close it for now?

**Comment by andiwand** [comment]
archiving this due to inactivity for now

**Comment by dimitra97** [comment]
An update on this:

I also changed the DetectorElement to return the copy of transforms and run the full chain itk with muons.

These are the numbers:
transform by value (after chaning also detector element transform return type)
11:58:52    Sequencer      INFO      Processed 100 events in 579.503603 ms (wall clock)
11:58:52    Sequencer      INFO      Average time per event: 34.349944 ms/event

transform by reference:

12:33:35    Sequencer      INFO      Processed 100 events in 299.885020 ms (wall clock)
12:33:35    Sequencer      INFO      Average time per event: 8.733620 ms/event

@asalzburger @paulgessinger @andiwand @noemina

**Comment by dimitra97** [comment]
> An update on this:
> 
> I also changed the DetectorElement to return the copy of transforms and run the full chain itk with muons.
> 
> These are the numbers: transform by value (after chaning also detector element transform return type) 11:58:52 Sequencer INFO Processed 100 events in 579.503603 ms (wall clock) 11:58:52 Sequencer INFO Average time per event: 34.349944 ms/event
> 
> transform by reference:
> 
> 12:33:35 Sequencer INFO Processed 100 events in 299.885020 ms (wall clock) 12:33:35 Sequencer INFO Average time per event: 8.733620 ms/event
> 
> @asalzburger @paulgessinger @andiwand @noemina

I am investigating it more because the results seem a little bit suspicious to me..
I ran this on Max's pc who has given me access
TO DO:
-Run  locally on my laptop
-Use profiler 
-Run ttbar events

**Comment by andiwand** [comment]
We should also run this through track finding performance evaluation.

Make sure you are building release and turned off "forced assertions" in CMake options. And that main is merged since this PR is quite outdated.

**Comment by dimitra97** [comment]
Thanks! Yes I build Release and ACTS_FORCE_ASSERTIONS=OFF. Also I made the changes locally in my branch and compiled. And I just run in also with main to compare. 
Also would like to ask, should this run in one thread? I think I get weird numbers when I run it with more than one thread.
Anyway, after running it with **one thread** and 500 events muons I got these
**By reference:**

`

identifier | time_total_s | time_perevent_s
-- | -- | --
Reader:EventGenerator | 0.00242394 | 0.00000484788
Algorithm:ParticleSelector | 0.000614666 | 0.00000122933
Algorithm:FatrasSimulation | 0.181111 | 0.000362221
Writer:RootParticleWriter | 0.00270309 | 0.00000540619
Writer:RootSimHitWriter | 0.0193535 | 0.0000387069
Algorithm:DigitizationAlgorithm | 0.0150528 | 0.0000301055
Writer:RootMeasurementWriter | 0.042879 | 0.000085758
Algorithm:TruthSeedSelector | 0.00110042 | 0.00000220085
Algorithm:SpacePointMaker | 0.00616078 | 0.0000123216
Algorithm:SeedingAlgorithm | 0.0190994 | 0.0000381988
Algorithm:TrackParamsEstimationAlgorithm | 0.00467625 | 0.0000093525
Algorithm:SeedsToPrototracks | 0.000718147 | 0.00000143629
Writer:SeedingPerformanceWriter | 0.00255357 | 0.00000510714
Writer:RootTrackParameterWriter | 0.013037 | 0.000026074
Algorithm:TrackFindingAlgorithm | 0.327189 | 0.000654378
Algorithm:TrackTruthMatcher | 0.00249506 | 0.00000499012
Writer:RootTrackStatesWriter | 0.329053 | 0.000658106
Writer:RootTrackSummaryWriter | 0.00995316 | 0.0000199063
Writer:CKFPerformanceWriter | 0.00270485 | 0.0000054097
Algorithm:GreedyAmbiguityResolutionAlgorithm | 0.0135394 | 0.0000270787
Algorithm:TrackTruthMatcher | 0.00189313 | 0.00000378625
Writer:RootTrackStatesWriter | 0.26711 | 0.00053422
Writer:RootTrackSummaryWriter | 0.00836417 | 0.0000167283
Writer:CKFPerformanceWriter | 0.00196708 | 0.00000393415
Algorithm:TracksToParameters | 0.00361164 | 0.00000722328
Algorithm:AdaptiveMultiVertexFinder | 0.021304 | 0.0000426079
Writer:VertexPerformanceWriter | 0.0152228 | 0.0000304457
  | TOTAL: | 0.00263178038



`
**By value:**

`


identifier | time_total_s | time_perevent_s
-- | -- | --
Reader:EventGenerator | 0.00261064 | 0.00000522127
Algorithm:ParticleSelector | 0.000584152 | 0.0000011683
Algorithm:FatrasSimulation | 0.209827 | 0.000419654
Writer:RootParticleWriter | 0.00315261 | 0.00000630523
Writer:RootSimHitWriter | 0.0192369 | 0.0000384739
Algorithm:DigitizationAlgorithm | 0.0164004 | 0.0000328008
Writer:RootMeasurementWriter | 0.0440818 | 0.0000881636
Algorithm:TruthSeedSelector | 0.00110519 | 0.00000221037
Algorithm:SpacePointMaker | 0.00673793 | 0.0000134759
Algorithm:SeedingAlgorithm | 0.0192255 | 0.000038451
Algorithm:TrackParamsEstimationAlgorithm | 0.00501124 | 0.0000100225
Algorithm:SeedsToPrototracks | 0.000753074 | 0.00000150615
Writer:SeedingPerformanceWriter | 0.00265913 | 0.00000531826
Writer:RootTrackParameterWriter | 0.0132796 | 0.0000265592
Algorithm:TrackFindingAlgorithm | 0.360383 | 0.000720766
Algorithm:TrackTruthMatcher | 0.00252331 | 0.00000504662
Writer:RootTrackStatesWriter | 0.331812 | 0.000663623
Writer:RootTrackSummaryWriter | 0.0107357 | 0.0000214714
Writer:CKFPerformanceWriter | 0.00297329 | 0.00000594658
Algorithm:GreedyAmbiguityResolutionAlgorithm | 0.012348 | 0.0000246961
Algorithm:TrackTruthMatcher | 0.00183735 | 0.00000367471
Writer:RootTrackStatesWriter | 0.269911 | 0.000539823
Writer:RootTrackSummaryWriter | 0.00940603 | 0.0000188121
Writer:CKFPerformanceWriter | 0.00224713 | 0.00000449426
Algorithm:TracksToParameters | 0.00350597 | 0.00000701193
Algorithm:AdaptiveMultiVertexFinder | 0.0207162 | 0.0000414324
Writer:VertexPerformanceWriter | 0.0165867 | 0.0000331734
  |   | 0.00277930198




`

**Comment by dimitra97** [comment]
I followed Andreas' suggestions and I also ran it for 200 runs with 500 events each of single muons. The distributions of the time/event (ms) and also an indicative timing record of the algorithms for one event (which maybe not that much useful).

```
timing_valueTransform
identifier,time_total_s,time_perevent_s
Reader:EventGenerator,0.00381614,7.63227e-06
Algorithm:ParticleSelector,0.000559921,1.11984e-06
Algorithm:FatrasSimulation,0.239644,0.000479287
Algorithm:DigitizationAlgorithm,0.0179579,3.59159e-05
Algorithm:TruthSeedSelector,0.00123092,2.46185e-06
Algorithm:SpacePointMaker,0.00706782,1.41356e-05
Algorithm:SeedingAlgorithm,0.0216665,4.33329e-05
Algorithm:TrackParamsEstimationAlgorithm,0.00531086,1.06217e-05
Algorithm:SeedsToPrototracks,0.000676327,1.35265e-06
Algorithm:TrackFindingAlgorithm,0.405541,0.000811082
Algorithm:TrackTruthMatcher,0.00267545,5.3509e-06
Algorithm:GreedyAmbiguityResolutionAlgorithm,0.0130588,2.61176e-05
Algorithm:TrackTruthMatcher,0.00169751,3.39502e-06
Algorithm:TracksToParameters,0.00239154,4.78307e-06
Algorithm:AdaptiveMultiVertexFinder,0.020124,4.0248e-05

timing_referenceOfTransform
identifier,time_total_s,time_perevent_s
Reader:EventGenerator,0.00373888,7.47776e-06
Algorithm:ParticleSelector,0.000551456,1.10291e-06
Algorithm:FatrasSimulation,0.218897,0.000437794
Algorithm:DigitizationAlgorithm,0.0178356,3.56712e-05
Algorithm:TruthSeedSelector,0.00124355,2.4871e-06
Algorithm:SpacePointMaker,0.00699204,1.39841e-05
Algorithm:SeedingAlgorithm,0.0218878,4.37756e-05
Algorithm:TrackParamsEstimationAlgorithm,0.0051693,1.03386e-05
Algorithm:SeedsToPrototracks,0.000739396,1.47879e-06
Algorithm:TrackFindingAlgorithm,0.383247,0.000766494
Algorithm:TrackTruthMatcher,0.0028563,5.7126e-06
Algorithm:GreedyAmbiguityResolutionAlgorithm,0.0128478,2.56955e-05
Algorithm:TrackTruthMatcher,0.00176835,3.53671e-06
Algorithm:TracksToParameters,0.00265669,5.31338e-06
Algorithm:AdaptiveMultiVertexFinder,0.019765,3.953e-05
```


image

**Comment by dimitra97** [comment]
I followed Andreas suggestion for the benchmark. I ran 200 runs with 500 events each with single muons. I have the plot with the distributions and also an indicative timing record for the algorithms  for the last event (maybe not thta much useful at this point).
image
```
timing_valueTransform
identifier,time_total_s,time_perevent_s
Reader:EventGenerator,0.00381614,7.63227e-06
Algorithm:ParticleSelector,0.000559921,1.11984e-06
Algorithm:FatrasSimulation,0.239644,0.000479287
Algorithm:DigitizationAlgorithm,0.0179579,3.59159e-05
Algorithm:TruthSeedSelector,0.00123092,2.46185e-06
Algorithm:SpacePointMaker,0.00706782,1.41356e-05
Algorithm:SeedingAlgorithm,0.0216665,4.33329e-05
Algorithm:TrackParamsEstimationAlgorithm,0.00531086,1.06217e-05
Algorithm:SeedsToPrototracks,0.000676327,1.35265e-06
Algorithm:TrackFindingAlgorithm,0.405541,0.000811082
Algorithm:TrackTruthMatcher,0.00267545,5.3509e-06
Algorithm:GreedyAmbiguityResolutionAlgorithm,0.0130588,2.61176e-05
Algorithm:TrackTruthMatcher,0.00169751,3.39502e-06
Algorithm:TracksToParameters,0.00239154,4.78307e-06
Algorithm:AdaptiveMultiVertexFinder,0.020124,4.0248e-05

timing_referenceOfTransform
identifier,time_total_s,time_perevent_s
Reader:EventGenerator,0.00373888,7.47776e-06
Algorithm:ParticleSelector,0.000551456,1.10291e-06
Algorithm:FatrasSimulation,0.218897,0.000437794
Algorithm:DigitizationAlgorithm,0.0178356,3.56712e-05
Algorithm:TruthSeedSelector,0.00124355,2.4871e-06
Algorithm:SpacePointMaker,0.00699204,1.39841e-05
Algorithm:SeedingAlgorithm,0.0218878,4.37756e-05
Algorithm:TrackParamsEstimationAlgorithm,0.0051693,1.03386e-05
Algorithm:SeedsToPrototracks,0.000739396,1.47879e-06
Algorithm:TrackFindingAlgorithm,0.383247,0.000766494
Algorithm:TrackTruthMatcher,0.0028563,5.7126e-06
Algorithm:GreedyAmbiguityResolutionAlgorithm,0.0128478,2.56955e-05
Algorithm:TrackTruthMatcher,0.00176835,3.53671e-06
Algorithm:TracksToParameters,0.00265669,5.31338e-06
Algorithm:AdaptiveMultiVertexFinder,0.019765,3.953e-05
```

**Pull request closed without merging**
