### PR TITLE
refactor!: Rename the Track{Finding,Fitting} modules

### LINKED ISSUE #444: Use consistent module names
The tracking and vertexing modules are inconsistently named/organized. Switch to the following consistent organization
```
Acts/TrackSeeding/ # was Seeding 
Acts/TrackFinding/  # was Fitter  
Acts/TrackFitting/    # was TrackFitter
Acts/VertexSeeding/ # was Vertexing
Acts/VertexFinding/  # was Vertexing
Acts/VertexFitting/    # was Vertexing
```
Seeding and finding algorithms could also be grouped together into `{Track,Vertex}/Finding` modules.

### PR DESCRIPTION
**Pull request by msmk0**
Fixes #444.

### CODE REVIEW

**Review by XiaocongAi — COMMENTED** [review]
Hi @msmk0 , thank you for putting this in order. Shall we rename the `FItting`/`FittingAlgorithm` to `TrackFitting`/`TrackFittingAlgorithm` as well?

**Review by XiaocongAi — APPROVED** [review]
OK. Let's get this in first.

**Comment by msmk0** [comment]
@XiaocongAi @paulgessinger I am not sure why the debug build is still marked as *Skipped*. All jobs were re-started after merging the most recent master and there was no manual intervention from my side. Any ideas?

**Comment by paulgessinger** [comment]
Hm, the debug build fails again. 😟 OOM?

**Comment by asalzburger** [comment]
> Hm, the debug build fails again. 😟 OOM?

But after two hours?

**Comment by asalzburger** [comment]
Re-triggered it.

**Comment by msmk0** [comment]
Still failing. Why this one? This only changes a few include names and order.

**Comment by paulgessinger** [comment]
If we're close to the limit, maybe the renaming changes the order in which compilation units are processed, and we have some bad luck with two heavy hitters overlapping?

**Comment by msmk0** [comment]
And the master branch is building fine. Maybe just a transient error: stuck on a bad machine?

**Comment by msmk0** [comment]
> If we're close to the limit, maybe the renaming changes the order in which compilation units are processed, and we have some bad luck with two heavy hitters overlapping?

That could be a reason. Checking the `build_performance` output there is no difference to the master branch for memory consumption. In both cases, the track fitter and finder algorithms are among the top memory consumers.

**Comment by paulgessinger** [comment]
Right but that's not indicative of the order in which the compilation units are processed. I'm not even entirely sure we use multiple processes in the debug build, tbh.

**Review by XiaocongAi — APPROVED** [review]
I guess I have already approved, no? But will approve again anyway.

**Comment by XiaocongAi** [comment]
For the compiling issue, I think we might revert the change to the compiling order in the `CMakeLists.txt` and see what happens.

**Comment by msmk0** [comment]
> For the compiling issue, I think we might revert the change to the compiling order in the `CMakeLists.txt` and see what happens.

Yep, that did the trick. I give up now.

**Comment by paulgessinger** [comment]
This is very worrisome. :(

**Review by XiaocongAi — APPROVED** [review]
Yeah, let's just keep it like this then.

**Comment by HadrienG2** [comment]
> This is very worrisome. :unamused:

Well, if I remember our last Mattermost discussion, we plan to look into the underlying Measurement issue as soon as we're done with v1.0, right ?

**Comment by msmk0** [comment]
Yes, absolutely. I have some ideas for that and I think @paulgessinger does as well.

**Pull request merged**
