### PR TITLE
ci: Physmon follow up: enable failure again

### PR DESCRIPTION
**Pull request by paulgessinger**
Based on https://github.com/acts-project/acts/pull/1222

With https://github.com/acts-project/acts/pull/1222 in, we can have the python level tests and the perf
monitoring fail independently of one another. This PR enables that
again. Also bumps `histcmp` to v0.4.0 for a fix for missing legends in
some plots, and to include standalone PDFs in addition to the HTML
report.

### CODE REVIEW

**Comment by paulgessinger** [comment]
I'm also still investigating if/why #1216 apparently changed the output histograms.

**Comment by paulgessinger** [comment]
I updated the reference. It looks good to me by eye.

**Review by stephenswat — APPROVED** [review]
Let me sign off on this, the CI failure seems unrelated.

**Comment by paulgessinger** [comment]
I messed up the conflict resolution (reverted to histcmp 0.3.1 in the process). Hopefully fixed now.

**Review by stephenswat — APPROVED** [review]
Looks good.

**Pull request merged**
