### PR TITLE
refactor: Accumulated `EigenStepper` brush-over

### PR DESCRIPTION
**Pull request by andiwand**

### CODE REVIEW

**Comment by AJPfleger** [comment]
Interesting that the hashes change:
`===== 13 failed, 215 passed, 21 skipped, 4 deselected in 500.87s (0:08:20) =====`

I assume it is due to the change from `float` to `double` in the `stepSizeScaling`. Was there a reason why we had the conversion `double`->`float` -> `double` before?

**Comment by andiwand** [comment]
> Interesting that the hashes change: `===== 13 failed, 215 passed, 21 skipped, 4 deselected in 500.87s (0:08:20) =====`
> 
> I assume it is due to the change from `float` to `double` in the `stepSizeScaling`. Was there a reason why we had the conversion `double`->`float` -> `double` before?

I suspect that this was an optimization attempt but I would not measure a difference.

I can try to quantify it with the stepper benchmark.

**Comment by AJPfleger** [comment]
I found this regarding the float:
https://github.com/acts-project/acts/pull/1150#issuecomment-1033862762

**Comment by andiwand** [comment]
> I found this regarding the float: [#1150 (comment)](https://github.com/acts-project/acts/pull/1150#issuecomment-1033862762)

Oh yeah I also discovered that `std::pow` is incredibly slow.

Since this is a very performance critical path we might want to have a custom expansion for the sqrt.

But this is a story for another PR

**Comment by andiwand** [comment]
I measured the performance with the stepper benchmark

This branch:

```
% ~/cern/build/acts/acts/perf2/bin/ActsBenchmarkEigenStepper 
09:24:39    Eigen_Steppe   INFO      propagating 20000 tracks with pT = 1GeV in a 2T B-field
09:24:41    Eigen_Steppe   INFO      Execution stats: 20000 runs of 1 iteration(s), 455.9ms total, 22.6250+/-0.0059µs per run, 22625.000+/-5.910ns per iteration
09:24:41    Eigen_Steppe   INFO      average path length = 5000mm

% ~/cern/build/acts/acts/perf2/bin/ActsBenchmarkEigenStepper --cov false
09:24:46    Eigen_Steppe   INFO      propagating 20000 tracks with pT = 1GeV in a 2T B-field
09:24:49    Eigen_Steppe   INFO      Execution stats: 20000 runs of 1 iteration(s), 265.1ms total, 13.1250+/-0.0059µs per run, 13125.000+/-5.910ns per iteration
09:24:49    Eigen_Steppe   INFO      average path length = 5000mm
```

Main:

```
% ~/cern/build/acts/acts/perf2/bin/ActsBenchmarkEigenStepper 
09:25:46    Eigen_Steppe   INFO      propagating 20000 tracks with pT = 1GeV in a 2T B-field
09:25:49    Eigen_Steppe   INFO      Execution stats: 20000 runs of 1 iteration(s), 468.1ms total, 23.1670+/-0.0059µs per run, 23167.000+/-5.897ns per iteration
09:25:49    Eigen_Steppe   INFO      average path length = 5000mm

% ~/cern/build/acts/acts/perf2/bin/ActsBenchmarkEigenStepper --cov false
09:25:54    Eigen_Steppe   INFO      propagating 20000 tracks with pT = 1GeV in a 2T B-field
09:25:56    Eigen_Steppe   INFO      Execution stats: 20000 runs of 1 iteration(s), 269.0ms total, 13.4160+/-0.0032µs per run, 13416.000+/-3.219ns per iteration
09:25:56    Eigen_Steppe   INFO      average path length = 5000mm
```

The `double` version is consistently faster on my machine.

**Comment by AJPfleger** [comment]
But could also be due to the different clamping, or not?

**Comment by andiwand** [comment]
> But could also be faster due to the different clamping, or not?

The clamping should not make any difference but the hypot might. I will run again while isolating the float / double change

**Comment by andiwand** [comment]
Isolated the `std::sqrt` change: looks consistent. The float -> double change does not make it slower but a little faster. The rest of the speedup seems to come from the hypot -> sqrt change.

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [e0633f32a4f274313e8be1dc2c1020f742e5ebcf]
### :white_check_mark: All tests successful

|status|job|report|
|------|---|------|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257603)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257602)||
|:green_circle: | [test_ActsPersistifySeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257600)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257599)||
|:green_circle: | [test_ActsAnalogueClustering](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257598)||
|:green_circle: | [test_ActsConversionWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257597)||
|:green_circle: | [test_ActsWorkflowFastTracking](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257596)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257595)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257594)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257593)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257592)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257591)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257590)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257589)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257587)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257585)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257584)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257583)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257582)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257581)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257580)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257579)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257578)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257577)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257576)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257575)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257574)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/38257573)||

**Pull request merged**
