### PR TITLE
fix!: fixes to Digitization after EDM rework

### PR DESCRIPTION
**Pull request by asalzburger**
This PR sits on top of #557, it addresses small changes to get the Digitization running again.

For more information, please refer to #557.

### CODE REVIEW

**Comment by msmk0** [comment]
@asalzburger Should I merge this into my branch and then we merge #557 or should we merge #557 and then merge this one separately. My personal preference is on the later.

**Comment by asalzburger** [comment]
@msmk0  is good to merge into yours.

**Comment by asalzburger** [comment]
Superseded by #557

**Pull request closed without merging**
