### PR TITLE
perf: EigenStepper step size adjustment

### PR DESCRIPTION
**Pull request by FabianKlimpel**
The `EigenStepper` will either keep the step size or reduce it. This depends on the error of the numerical integration. A step accepted if the error is below the tolerance. Calculating the next step size according to ATL-SOFT-PUB-2009-001 Eqs. (6) and (7), the next step size can be estimated to be larger or equal to the accepted one. Therewith the next step could be larger (potentially) reducing the required amount of steps.

The changes were tested using the ATLAS magnetic field, the GenericDetector, 100k events with 100 events per p_T configuration. It was found that this additional scaling leads to step size adjustments (due to energy loss & magnetic field fluctuations). Without the transport of covariance matrices the propagation tend to take longer than the current implementation. Below the timings with covariance transport are shown:

Current Implementation:

identifier | time_total_s | time_perevent_s
Algorithm:PropagationAlgorithm | 26.52 | 0.0002652
Writer:RootPropagationStepsWriter | 22.54 | 0.0002254
Writer:RootPropagationStepsWriter:endRun | 0.1285 | 1.285E-06

This PR:

identifier | time_total_s | time_perevent_s
Algorithm:PropagationAlgorithm | 14.82 | 0.0001482
Writer:RootPropagationStepsWriter | 21.62 | 0.0002162
Writer:RootPropagationStepsWriter:endRun | 0.9658 | 9.658E-06

### CODE REVIEW

**Comment by paulgessinger** [comment]
Didn't @asalzburger implement re-increased step sizes at some point, or do I remember incorrectly?

**Comment by FabianKlimpel** [comment]
> Didn't @asalzburger implement re-increased step sizes at some point, or do I remember incorrectly?

If I remember correctly then the original step size adjustment implementation required a step size scaling factor of 1 in order to accept the step. As this was pretty unstable the requirement changed to just drop below the error tolerance.
So the original implementation had this possibility. As I don't remember any other changes, could it be that you mean this one?

**Comment by asalzburger** [comment]
Hi @FabianKlimpel, I can not really confirm this measurement

THIS PR:

```shell
salzburg@Andreass-MacBook-Pro bin % ./ActsExamplePropagationGeneric --bf-constant-tesla 0:0:2 -n1000 --bf-map-file ATLAS-BField-xyz.root -j1 --prop-cov on
15:59:55    MagneticFiel   INFO      Use a constant magnetic field
15:59:55    Sequencer      INFO      Added algorithm 'PropagationAlgorithm'
15:59:55    Sequencer      INFO      Processing events [0, 1000)
15:59:55    Sequencer      INFO      Starting event loop with 1 threads
15:59:55    Sequencer      INFO        0 services
15:59:55    Sequencer      INFO        0 context decorators
15:59:55    Sequencer      INFO        0 readers
15:59:55    Sequencer      INFO        1 algorithms
15:59:55    Sequencer      INFO        0 writers
15:59:58    Sequencer      INFO      100 / 1000 events processed
16:00:02    Sequencer      INFO      200 / 1000 events processed
16:00:05    Sequencer      INFO      300 / 1000 events processed
16:00:09    Sequencer      INFO      400 / 1000 events processed
16:00:12    Sequencer      INFO      500 / 1000 events processed
16:00:16    Sequencer      INFO      600 / 1000 events processed
16:00:20    Sequencer      INFO      700 / 1000 events processed
16:00:23    Sequencer      INFO      800 / 1000 events processed
16:00:27    Sequencer      INFO      900 / 1000 events processed
16:00:30    Sequencer      INFO      1000 / 1000 events processed
16:00:30    Sequencer      INFO      Processed 1000 events in 35.877175 s (wall clock)
16:00:30    Sequencer      INFO      Average time per event: 35.832491 ms/event
```

MASTER:

```shell
salzburg@Andreass-MacBook-Pro bin % ./ActsExamplePropagationGeneric --bf-constant-tesla 0:0:2 -n1000 --bf-map-file ATLAS-BField-xyz.root -j1 --prop-cov on
16:04:52    MagneticFiel   INFO      Use a constant magnetic field
16:04:52    Sequencer      INFO      Added algorithm 'PropagationAlgorithm'
16:04:52    Sequencer      INFO      Processing events [0, 1000)
16:04:52    Sequencer      INFO      Starting event loop with 1 threads
16:04:52    Sequencer      INFO        0 services
16:04:52    Sequencer      INFO        0 context decorators
16:04:52    Sequencer      INFO        0 readers
16:04:52    Sequencer      INFO        1 algorithms
16:04:52    Sequencer      INFO        0 writers
16:04:56    Sequencer      INFO      100 / 1000 events processed
16:05:00    Sequencer      INFO      200 / 1000 events processed
16:05:03    Sequencer      INFO      300 / 1000 events processed
16:05:07    Sequencer      INFO      400 / 1000 events processed
16:05:11    Sequencer      INFO      500 / 1000 events processed
16:05:15    Sequencer      INFO      600 / 1000 events processed
16:05:19    Sequencer      INFO      700 / 1000 events processed
16:05:23    Sequencer      INFO      800 / 1000 events processed
16:05:26    Sequencer      INFO      900 / 1000 events processed
16:05:30    Sequencer      INFO      1000 / 1000 events processed
16:05:30    Sequencer      INFO      Processed 1000 events in 38.222985 s (wall clock)
16:05:30    Sequencer      INFO      Average time per event: 38.154152 ms/event
```

**Comment by asalzburger** [comment]
So, probably a 10 percent difference? 

Might be still worth it though.

**Comment by asalzburger** [comment]
Ah, this is constant magnetic field.

**Comment by FabianKlimpel** [comment]
> So, probably a 10 percent difference?
> 
> Might be still worth it though.

I saw ~10% less steps required, so this is a way more reasonable number than the one I posted above (as I said, I don't really trust my number).
Did you propagate a covariance matrix?

**Comment by FabianKlimpel** [comment]
> I ran the truth fitting with ttbar events at GenericDetector and constant B field W/O the change, but see no obvious change:
> image

Thank you for running the test. Could you please repeat it with a non-constant magnetic field? For the constant one there is always a perfect step size (if you neglect the material interaction), so there is no upscaling required.

**Comment by XiaocongAi** [comment]
Hi @FabianKlimpel ,  these are the results with the ATLAS B field. No obvious difference still though:
image

**Comment by FabianKlimpel** [comment]
Thank you very much @XiaocongAi.
If we handle a dense environment, we need a concept of scaling the step size. As it looks like it doesn't matter for our current applications, we could merge in my opinion. Let's discuss this in the meeting and thank you again for the plots.

**Pull request merged**
