### PR TITLE
refactor(Examples): remove Digitization from Fatras simulations

### PR DESCRIPTION
**Pull request by msmk0**
Remove all digitization code from the Fatras examples. The available digitization within Fatras only works for the generic detector and is still based on `PlanarCluster`s. The reconstruction examples already re-digitize the simulations hits using the measurement-based digitzation.

With the removal of this (dead) code, the simulations only produce initial and final particles states and truth/ simulation hits.

### CODE REVIEW

**Comment by asalzburger** [comment]
I was thinking anyway to introduce a dedicated DigitizationExample that picks up the Simulation part and runs the digitization & writes out.

**Comment by msmk0** [comment]
@asalzburger This is ready to be merged and is just waiting for your review.

**Review by asalzburger — APPROVED** [review]
Uncontroverisal.

**Comment by asalzburger** [comment]
As discussed, we will make a dedictaed `DigitizationExample`.

**Pull request merged**
