### PR TITLE
fix: Fix navigation when collecting surface in tracking volume hierarchy

### PR DESCRIPTION
**Pull request by Corentin-Allaire**
This PR solve an issue with the navigation trough the ATLAS calorimeter (or any other volume using `compatibleSurfacesFromHierarchy`). If the none of the surface collected between start and the target intersect with the trajectory the navigation cannot reach the Navigation break (and thus cannot reach the target surface) and will loop forever.

To solve this issue an extra bool was added to the navigation state, after iterating over all the surfaces if no layer exist (which mean the surface where obtain via `compatibleSurfacesFromHierarchy`) the bool is switched to true and the layer stage is skipped.

### CODE REVIEW

**Comment by paulgessinger** [comment]
But does this not pose a problem for low-ish momentum particles? Those might hit surfaces that are not considered compatible directly from straight line intersect?

**Comment by Corentin-Allaire** [comment]
> But does this not pose a problem for low-ish momentum particles? Those might hit surfaces that are not considered compatible directly from straight line intersect?

I agree on that point but isn't it the same thing when intersecting with surfaces within layers ? We also use the options.boundaryCheck there.

**Comment by Corentin-Allaire** [comment]
@paulgessinger I found another way to fix the issue. So I have put the `compatibleSurfacesFromHierarchy` as it used to be.

**Comment by paulgessinger** [comment]
The macOS failure looks like a transient error. Try rerunning the CI.

**Comment by Corentin-Allaire** [comment]
Seem to be working now.

**Review by paulgessinger — APPROVED** [review]

**Pull request merged**
