### PR TITLE
refactor: Resolve surfaces on initialization in `Navigator`

### PR DESCRIPTION
**Pull request by andiwand**
Going a bit further than https://github.com/acts-project/acts/pull/3280 by removing the status flag for the start layer resolution and resolving the surfaces already in the initialization step.

blocked by
- https://github.com/acts-project/acts/pull/3280

### CODE REVIEW

**Comment by andiwand** [comment]
cc @benjaminhuth

**Comment by andiwand** [comment]
seems not to effect CPU performance while physmon suggests a small increase in efficiency for the CKF

image

image

**Review by noemina — APPROVED** [review]
Changes make sense and look good to me.

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [b58a4b404efdc86401e5adb077d8431de4152869]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/41651485) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7822659)!

**Pull request merged**
