### PR TITLE
feat: Define all surface methods out-of-line

### LINKED ISSUE #409: Move Surface inline code to implementation files
A significant portion of the method implementations exists as `inline` methods in `.ipp` files. Since they are almost always called via virtual function calls there should not be any performance improvement from inlining them. Moving them to `.cpp` files should reduce some of the build overhead from having the inline methods around.

### PR DESCRIPTION
**Pull request by paulgessinger**
As previously discussed, most Surface related methods are currently defined as `inline` in `.ipp` files. 

~~This PR adds a cmake option `ACTS_SURFACE_INLINE`. If enabled, the `.hpp` files will not include their corresponding `.ipp` files, but their corresponding `.cpp` files will. Using a special preprocessor directive, the `inline` keywords are removed from the methods, turning them into regular symbols.~~

This PR moves all method definitions into the corresponding `.cpp` files.

In local testing, I don't observe runtime performance degradation and slight compile-time improvement. Let's see what the CI has to say on the latter topic.

~~The use of preprocessor macros might be controversial, so let's discuss. The reason I think this approach might be a good idea is that this enables us to possible to back to the inlined methods. If we choose to go this route, we should probably ensure that both variants work in the CI.~~

Fixes #409

### CODE REVIEW

**Comment by paulgessinger** [comment]
CI reports memory usage to be the same, but hints toward slightly lower time to compile. Not super conclusive though.

**Comment by paulgessinger** [comment]
@msmk0

**Review by msmk0 — COMMENTED** [review]
I see no technical problems with this.

Personally, I would strongly prefer to not make this configurable and to move the inline code to regular `.cpp` files instead. As suggested by the CI build and by @paulgessinger observations, moving the implementations to `.cpp` files has no measurable performance impact in realistic setups. The proposed setup adds complexity that we need to maintain in the future. If there is a hotspot in one of the methods that can be improved by inlining, we can move that particular function as an inline function into the `.hpp` file in the future.

**Comment by paulgessinger** [comment]
@msmk0: I removed the `#define`, the definitions are now in the `.cpp` files.

**Review by asalzburger — APPROVED** [review]
Moving code around, looks good.

**Comment by asalzburger** [comment]
Wanted to wait to see 'if' we see some change in `build_performance`, but we can merge otherwise.

**Pull request merged**
