### PR TITLE
chore: Update ODD in thirdparty

### PR DESCRIPTION
**Pull request by paulgessinger**
https://github.com/acts-project/OpenDataDetector/pull/11

### CODE REVIEW

**Comment by paulgessinger** [comment]
Do we then switch all third party repos over to submodules, or do you only want to switch this one?

**Comment by asalzburger** [comment]
> Do we then switch all third party repos over to submodules, or do you only want to switch this one?

I think we decided on this one - as it requires `git-lfs`

**Comment by paulgessinger** [comment]
Switched `thirdparty/OpenDataDetector` to be a submodule now.

**Review by asalzburger — APPROVED** [review]
Change from copy to submodule - good.

**Pull request merged**
