### PR TITLE
feat: Python examples updates for CKF and ITk

### PR DESCRIPTION
**Pull request by timadye**
* `addCKFTracks` args has its own `CKFPerformanceConfig` instead of borrowing `TruthSeedRanges`, which isn't the same thing.
* ATLAS ITk examples now in `acts-itk` instead of `acts-detector-examples/atlas`. The GitLab repo has moved. Ask us for access.

### CODE REVIEW

**Comment by timadye** [comment]
Oops, it looks like the old syntax snuck in for the `thirdparty/OpenDataDetector/ci/full_chain_odd.py`. The fix is trivial

```
--- a/ci/full_chain_odd.py
+++ b/ci/full_chain_odd.py
@@ -64,7 +64,7 @@ from particle_gun import addParticleGun, MomentumConfig, EtaConfig, ParticleConf
 from fatras import addFatras
 from digitization import addDigitization
 from seeding import addSeeding, SeedingAlgorithm, TruthSeedRanges
-from ckf_tracks import addCKFTracks
+from ckf_tracks import addCKFTracks, CKFPerformanceConfig

 s = acts.examples.Sequencer(events=args.events, numThreads=args.jobs, skip=args.skip)
 s = addParticleGun(
@@ -102,7 +102,7 @@ s = addCKFTracks(
     s,
     trackingGeometry,
     field,
-    TruthSeedRanges(pt=(400.0 * u.MeV, None), nHits=(6, None)),
+    CKFPerformanceConfig(ptMin=400.0 * u.MeV, nMeasurementsMin=6),
     outputDirRoot=outputDir,
 )
```

but do I have to do anything special to include a submodule update in this PR?

**Comment by paulgessinger** [comment]
Nope, just update the submodule to an ODD commit on main. Will you create an MR over on Gitlab for ODD?

**Comment by timadye** [comment]
I'm not quite sure how this works, since the ODD remote is on gitlab. But I'll just assume I can ignore the submodules and see what happens.

**Comment by paulgessinger** [comment]
On this PR alone everything should work, as the `ci/full_chain_odd.py` is not executed in this repo's CI.

**Comment by timadye** [comment]
The CI doesn't seem to be able to pick up my commit for the ODD.

**Comment by paulgessinger** [comment]
If you do want to update the script in the ODD repo, then you'll have to at least push that commit to the ODD on Gitlab. In that case, I'd prefer you create an MR to the main ODD repo there, we merge that, and you bump the submodule to the merge commit.

Does that make sense?

**Comment by paulgessinger** [comment]
Ok let me try to clarify:

- `thirdparty/OpenDataDetector/ci/full_chain_odd.py` is run only in the ODD CI, not in the ACTS CI. Therefore, I don't believe it has to be updated in synchronization with this PR
  - This also doesn't break the ODD CI, since that should be locked to a specific ACTS version without this PR's changes
- **If** you want to update that script, these are the steps:
  1. Add a feature/fix branch on the GitLab ODD repository
  2. Open an MR to `main` and have it merged
  3. Update the submodule to the merge commit in this PR

**Comment by timadye** [comment]
Hi Paul,

Thanks for your crystal clear explanation. I had been confused because I saw some CI errors that I **mistakenly** thought were due to `thirdparty/OpenDataDetector/ci/full_chain_odd.py` and tried to understand the whole magic system that would allow that to happen. But it isn't used in the GitHib/ACTS CI, so it all makes sense now. I'll follow your preferred solution.

Thanks,
Tim.

**Comment by timadye** [comment]
Now only the macos build failed, and that says:
```
--2022-05-11 09:28:31--  https://acts.web.cern.ch/ci/macOS/deps.5e0adfa.tar.gz
Resolving acts.web.cern.ch (acts.web.cern.ch)... 188.185.90.87, 137.138.31.235, 188.185.87.216
Connecting to acts.web.cern.ch (acts.web.cern.ch)|188.185.90.87|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2022-05-11 09:28:32 ERROR 503: Service Unavailable.

Error: Process completed with exit code 8.
```
I guess that means it's a temporary issue, hopefully recovered now (I can download the file now). Can we try rerunning that check?

**Comment by timadye** [comment]
Hi @paulgessinger,
It looks like the macos build was retried and succeeded :)
Now the only thing left is "review-required". Do you need to re-review because of my updates?
Anyway, I requested a "re-review".
Thanks,
Tim.

**Review by paulgessinger — APPROVED** [review]

**Pull request merged**
