### PR TITLE
refactor: Remove AbstractVolume

### PR DESCRIPTION
**Pull request by paulgessinger**
This is not really needed anymore.

Blocked by:

- #3029

### CODE REVIEW

**Comment by paulgessinger** [comment]
@asalzburger confirms `AbstractVolume` is no longer relevant for us. Can you approve this?

**Review by andiwand — APPROVED** [review]

**Comment by asalzburger** [comment]
As @paulgessinger is off these days, I will resolve the conflict today.

**Review by AJPfleger — DISMISSED** [review]

**Review by AJPfleger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [e0336074ee728a040fe603170bd55a73cdbaa7f2]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/37270772) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7087777)!

**Comment by CarloVarni** [comment]
@andiwand @AJPfleger I'm afraid we have to revert this PR. It looks like this is used currently in Athena so this PR is a breaking one 

```console
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin/ld: Tracking/Acts/ActsGeometry/CMakeFiles/ActsGeometry.dir/src/ActsCaloTrackingVolumeBuilder.cxx.o: in function `ActsCaloTrackingVolumeBuilder::build_endcap(double, double, double, double, double, double) const':
/builds/acts/acts-athena-ci/athena/Tracking/Acts/ActsGeometry/src/ActsCaloTrackingVolumeBuilder.cxx:557: undefined reference to `Acts::AbstractVolume::AbstractVolume(Eigen::Transform<double, 3, 2, 0> const&, std::shared_ptr<Acts::VolumeBounds const>)'
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin/ld: Tracking/Acts/ActsGeometry/CMakeFiles/ActsGeometry.dir/src/ActsCaloTrackingVolumeBuilder.cxx.o: in function `ActsCaloTrackingVolumeBuilder::build_barrel(double, double, double, double, double, double) const':
/builds/acts/acts-athena-ci/athena/Tracking/Acts/ActsGeometry/src/ActsCaloTrackingVolumeBuilder.cxx:629: undefined reference to `Acts::AbstractVolume::AbstractVolume(Eigen::Transform<double, 3, 2, 0> const&, std::shared_ptr<Acts::VolumeBounds const>)'
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin/ld: Tracking/Acts/ActsGeometry/CMakeFiles/ActsGeometry.dir/src/ActsCaloTrackingVolumeBuilder.cxx.o: in function `ActsCaloTrackingVolumeBuilder::build_box(double, double, double, double, double, double) const':
/builds/acts/acts-athena-ci/athena/Tracking/Acts/ActsGeometry/src/ActsCaloTrackingVolumeBuilder.cxx:676: undefined reference to `Acts::AbstractVolume::AbstractVolume(Eigen::Transform<double, 3, 2, 0> const&, std::shared_ptr<Acts::VolumeBounds const>)'
```

**Comment by andiwand** [comment]
Oh I think Paul mentioned something about this. I can revert this until we catch up in Athena

**Comment by andiwand** [comment]
https://github.com/acts-project/acts/pull/3045

**Pull request merged**
