### PR TITLE
ci: Bump macOS dependencies again

### PR DESCRIPTION
**Pull request by paulgessinger**
This is because the python version got out of sync again.

### CODE REVIEW

**Comment by tboldagh** [comment]
Will CI in other PR be rerun automagically?

**Review by andiwand — APPROVED** [review]

**Comment by paulgessinger** [comment]
@tboldagh only when they get updated to latest main

**Comment by andiwand** [comment]
I will try to add a stable python build to the macos dependencies https://github.com/acts-project/ci-dependencies/pull/12

**Comment by acts-project-service** [comment]
The backport to `develop/v19.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-develop/v19.x develop/v19.x
# Navigate to the new working tree
cd .worktrees/backport-develop/v19.x
# Create a new branch
git switch --create backport-1583-to-develop/v19.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick -x --mainline 1 465fe6fa692aa672091c8eb1dac02a28abeb015c
# Push it to GitHub
git push --set-upstream origin backport-1583-to-develop/v19.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-develop/v19.x
```
Then, create a pull request where the `base` branch is `develop/v19.x` and the `compare`/`head` branch is `backport-1583-to-develop/v19.x`.

**Pull request merged**
