### PR TITLE
Miscellaneous AtlasStepper and EigenStepper fixes, AtlasStepper docs

### PR DESCRIPTION
**Pull request by HadrienG2**
Some time ago, Andi studied the AtlasStepper and EigenStepper and found that they did not perform the same number of steps for a given propagation job.

As it turns out, the reason for this is that the AtlasStepper used an incorrect expression of the step error estimate. In the ATL-SOFT-PUB-2009-001 terminology that is used by the EigenStepper, the error estimate that was computed by the AtlasStepper was `h * | k1 - k2 - k3 + k4 |` when it actually should have been `h^2 * | k1 - k2 - k3 + k4 |`.

This PR fixes that along with a few more minor problems of the AtlasStepper and EigenStepper:

- The AtlasStepper tolerance used to be hardcoded. It now correctly honors the tolerance set in the propagation options.
- After performing a propagation step, the AtlasStepper would not save it back into `state.stepping.stepSize`, instead starting over from the initial step size on every propagation step. This performance problem is now resolved.
- The EigenStepper would correctly decrease its step size until the propagation error tolerance is met, but never increase it again after that. This does not make sense in the complicated magnetic field maps that the adaptive step selection algorithms were designed for, where the step size should be allowed to go up and down depending on how "difficult" the magnetic field region is.

Since it took me half a day to reverse-engineer how the AtlasStepper works, I thought I would also leave around my notes on how the various quantities that it computes relate to those computed by the EigenStepper (which are themselves very close to the terminology used by ATL-SOFT-PUB-2009-001), so that the next person who needs to work on the AtlasStepper suffers less. If you think this is inappropriate, feel free to ping me and I'll remove the offending commit from this PR.

I would like to also investigate the poor performance of covariance transport, but since #83 is going to perform major changes in this area of the code, I think it's best for me to stop this PR at its current stage and wait for #83 to be merged in before continuing the stepper optimization work.

### CODE REVIEW

**Comment by HadrienG2** [comment]
Hmm. Didn't expect those changes to affect test results, but clearly, this needs more work.

**Comment by asalzburger** [comment]
Hi @HadrienG2 @paulgessinger - the `codecov/project` changes at `0.01 %` which should be within tolerance. The `codecov/patch` is anyway not very clear.

I have approved this PR - and would overwrite the failure.

**Comment by paulgessinger** [comment]
I guess the codecov config change was incorrect then. :/

**Comment by asalzburger** [comment]
I particularly like the code comments in the `AtlasStepper` - that will make it easier.

**Pull request merged**
