### PR TITLE
refactor: Vertex implementation

### PR DESCRIPTION
**Pull request by paulgessinger**
Big refactor of the vertexing code to rely much much less on templating.

Blocked by:
- https://github.com/acts-project/acts/pull/2874
- https://github.com/acts-project/acts/pull/2876
- #2877
- #2878 
- #2880
- #2881
- #2886 
- #2946 
- #2948
- #2951
- #2955
- #2952 
- #2953
- #2971 
- #2973 

TODO:
- [ ] Move `Vertex.ipp` to `Vertex.cpp`

### CODE REVIEW

**Comment by paulgessinger** [comment]
# Checkpoint 2023-12-18
- Physmon is green
- I don't observe any slowdown so far

## `main`
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `python CI/physmon/workflows/physmon_ckf_tracking.py /tmp/out` | 22.890 ± 0.466 | 22.135 | 23.924 | 1.00 |

## This PR
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `python CI/physmon/workflows/physmon_ckf_tracking.py /tmp/out` | 22.393 ± 0.423 | 21.668 | 23.309 | 1.00 |

**Comment by paulgessinger** [comment]
Checkpoint after making the finders use an interface and nesting them for IVF and AMVF: still no measurable change

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `python CI/physmon/workflows/physmon_ckf_tracking.py /tmp/out` | 22.517 ± 0.347 | 21.945 | 23.330 | 1.00 |

**Comment by paulgessinger** [comment]
Checkpoint after some more untemplating:

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `main` `./bench.sh` | 16.295 ± 0.365 | 15.716 | 17.099 | 1.00 |
| This PR: `./bench.sh` | 15.709 ± 0.294 | 15.341 | 16.702 | 1.00 |

**Comment by paulgessinger** [comment]
Memory-wise, we're now looking at:

### This PR:
file                                                                                  max_rss [M]    time [s]
----------------------------------------------------------------------------------  -------------  ----------
../Core/src/Vertexing/KalmanVertexUpdater.cpp                                             1053.31        6.55
../Core/src/Vertexing/KalmanVertexTrackUpdater.cpp                                         986.82        6.84
../Examples/Python/src/Vertexing.cpp                                                       950.01        7.06
../Examples/Io/Performance/ActsExamples/Io/Performance/VertexPerformanceWriter.cpp         922.48        7.97
../Examples/Algorithms/Vertexing/src/IterativeVertexFinderAlgorithm.cpp                    902.74        6.28
../Examples/Algorithms/Vertexing/src/AdaptiveMultiVertexFinderAlgorithm.cpp                901.53        6.48
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp                       892.29        7.45
../Tests/UnitTests/Core/Vertexing/LinearizedTrackFactoryTests.cpp                          861.21        6.33
../Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp                           840.40        7.08
../Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp                            815.27        6.02

file                                                                                  max_rss [M]    time [s]
----------------------------------------------------------------------------------  -------------  ----------
../Examples/Io/Performance/ActsExamples/Io/Performance/VertexPerformanceWriter.cpp         922.48        7.97
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp                       892.29        7.45
../Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp                           840.40        7.08
../Examples/Python/src/Vertexing.cpp                                                       950.01        7.06
../Core/src/Vertexing/KalmanVertexTrackUpdater.cpp                                         986.82        6.84
../Core/src/Vertexing/KalmanVertexUpdater.cpp                                             1053.31        6.55
../Examples/Algorithms/Vertexing/src/AdaptiveMultiVertexFinderAlgorithm.cpp                901.53        6.48
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp                       798.57        6.37
../Tests/UnitTests/Core/Vertexing/LinearizedTrackFactoryTests.cpp                          861.21        6.33
../Examples/Algorithms/Vertexing/src/IterativeVertexFinderAlgorithm.cpp                    902.74        6.28

### Main

file                                                                           max_rss [M]    time [s]
---------------------------------------------------------------------------  -------------  ----------
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp               1194.12       14.13
../Examples/Algorithms/Vertexing/src/IterativeVertexFinderAlgorithm.cpp            1172.44       10.14
../Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp                   1169.42       13.06
../Examples/Algorithms/Vertexing/src/AdaptiveMultiVertexFinderAlgorithm.cpp        1115.82       10.69
../Tests/UnitTests/Core/Vertexing/FullBilloirVertexFitterTests.cpp                 1115.80        9.36
../Examples/Algorithms/Vertexing/src/VertexFitterAlgorithm.cpp                     1089.14        8.83
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp                991.22        9.11
../Core/src/Vertexing/KalmanVertexTrackUpdater.cpp                                  967.03        7.18
../Examples/Python/src/Vertexing.cpp                                                963.54        7.17
../Core/src/Vertexing/KalmanVertexUpdater.cpp                                       959.86        6.92

file                                                                                  max_rss [M]    time [s]
----------------------------------------------------------------------------------  -------------  ----------
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp                      1194.12       14.13
../Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp                          1169.42       13.06
../Examples/Algorithms/Vertexing/src/AdaptiveMultiVertexFinderAlgorithm.cpp               1115.82       10.69
../Examples/Algorithms/Vertexing/src/IterativeVertexFinderAlgorithm.cpp                   1172.44       10.14
../Tests/UnitTests/Core/Vertexing/FullBilloirVertexFitterTests.cpp                        1115.80        9.36
../Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp                       991.22        9.11
../Examples/Algorithms/Vertexing/src/VertexFitterAlgorithm.cpp                            1089.14        8.83
../Examples/Io/Performance/ActsExamples/Io/Performance/VertexPerformanceWriter.cpp         915.62        7.95
../Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp                            918.67        7.38
../Core/src/Vertexing/KalmanVertexTrackUpdater.cpp                                         967.03        7.18

**Comment by paulgessinger** [comment]
Runtime performance looks like this:

| Branch | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `main` | 16.126 ± 0.394 | 15.800 | 17.578 | 1.00 |
| This PR | 16.025 ± 0.303 | 15.710 | 16.978 | 1.00 |

**Comment by andiwand** [comment]
is this the next one in the queue @paulgessinger ?

**Comment by paulgessinger** [comment]
I think this is completed.

**Pull request closed without merging**
