### PR TITLE
feat: `Surface::toStream` overload without stream argument

### PR DESCRIPTION
**Pull request by paulgessinger**
I'm adding a way that allows you to avoid having to write

```cpp
surface->toStream(gctx, std::cout);
std::cout << std::endl;
```

and instead write

```cpp
std::cout << surface->toStream(gctx) << std::endl;
```

This is done by returning a temporary helper struct that implements `operator<<`.

### CODE REVIEW

**Comment by andiwand** [comment]
I think @benjaminhuth did something similar here https://github.com/acts-project/acts/pull/1327 which requires `std::tie`ing the surface and context

**Comment by benjaminhuth** [comment]
yeah, maybe this is more intuitive than `std::cout << std::tie(surface, ctx) << std::endl`. It will definitively give better compiler errors :D

**Comment by andiwand** [comment]
Should we replace it then and converge on one version?

**Comment by benjaminhuth** [comment]
Would be fine for me.

**Comment by benjaminhuth** [comment]
Could you add this also to the doxygen description of `Acts::Surface`, so that people easily find this method @paulgessinger ?

**Comment by paulgessinger** [comment]
Ha, I had forgotten all about #1327, I was playing around with a `tuple` argument, but I didn't actually know it would work with `tie`.

Up to you, I can also close this in favor of just sticking to #1327.

**Comment by paulgessinger** [comment]
@andiwand That's a breaking change then?

**Comment by benjaminhuth** [comment]
@paulgessinger Really up to you... If your unawareness of `std::tie` is a hint that this is to non-obvious, we can use this. Otherwise we just have one PR less, which is also not too bad^^

**Review by benjaminhuth — APPROVED** [review]
Let's get it in!

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results [7d825f614faa5688281fb75d3d49ff33725b2875]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/40682654) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/7670183)!

**Pull request merged**
