### PR TITLE
feat: Stable AMVF KF fitting for examples

### PR DESCRIPTION
**Pull request by andiwand**
I noticed that the AMVF KF becomes unstable in our current examples setup. The new initial covariance for the vertex seed seems to fix that

### CODE REVIEW

**Comment by felix-russo** [comment]
Any intuition on why this helps?

**Comment by andiwand** [comment]
> Any intuition on why this helps?

I think this is a numerical precision issue. We are inverting the vertex covariance multiple times and it seems to be ill conditioned sometimes. Constraining the vertex more to the seed seems to help because the order of magnitude of the track update and seed will match better I think

**Review by felix-russo — APPROVED** [review]

**Comment by andiwand** [comment]
will update the reference as soon as https://github.com/acts-project/acts/pull/2355 is in

**Review by felix-russo — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31844743) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6070057)!

**Pull request merged**
