### PR TITLE
Updates to TGeo parsing

### PR DESCRIPTION
**Pull request by asalzburger**
This PR refines the way we parse options in the TGeo module
- [x] it allows for  or("|") syntax if wildcards are not good enough
- [x] it changes to the new `Interval` class to fix the bug that negative ranges could not be read
- [x] it introduces a parse range in z in addition to the one in r 
- [x] it refines the TGeo input option naming
- [x] it allows for `TGeoArb8` to be translated 
- [x] encapsulate the `TGeoShape` to `Acts::Surface` in a dedicated converter

Write documentation
- [x] explain how `TGeoShape` relate to `Acts::SurfaceBounds`

As a test, this is applied to the Panda detector for testing.

Tested with:
- [x] PropagationExample (for ITk)

Needs update to new `Test` directory infrastructue
- [x] Remove access via `http` and include file for testing

### CODE REVIEW

**Comment by asalzburger** [comment]
snapshot00

**Comment by msmk0** [comment]
@asalzburger After going through your changes, I realize that we need to clarify the available option types a bit. I will prepare a quick PR for this that we might want to merge before this one.

**Comment by asalzburger** [comment]
> @asalzburger After going through your changes, I realize that we need to clarify the available option types a bit. I will prepare a quick PR for this that we might want to merge before this one.

Hey @msmk0 - can you hold off for a moment please?

I am in the process to encapsulate out the `TGeoShape` translation from the `TGeoDetectorElement`.

I will then also write documentation and describe how to use the parsings, etc:

TGeoTrd1

**Comment by msmk0** [comment]
I think my cleanup is orthogonal and does not depend on this PR. Since you are modifying the options anyways, it might be a good moment to clarify them.

**Comment by asalzburger** [comment]
Ok, perfect.

**Comment by asalzburger** [comment]
These sort of explanations are needed for all shapes:

Screenshot 2020-05-29 at 15 18 16

**Comment by asalzburger** [comment]
Screenshot 2020-06-09 at 11 28 06

`TGeoArb8` translated into trapezoids.

**Comment by asalzburger** [comment]
Screenshot 2020-06-09 at 16 36 59

Back in business with ITk.

**Comment by asalzburger** [comment]
Re-opened as #258 with correct name and rebased.

**Pull request closed without merging**
