### PR TITLE
feat: full_chain_test.py config with command-line options

### PR DESCRIPTION
**Pull request by timadye**
`full_chain_test.py` supports all options from `ckf_tracks.py` (generic detector), `full_chain_odd.py`, and `full_chain_itk.py`, as well as some new additions to help with testing.

The idea is to complement those scripts which provide *examples*, where `full_chain_test.py` simplifies running interactive/batch tests with different options specified on the command-line. With all the options, it is not intended to be an easy-to-read example. The existing example scripts could eventually be simplified, since they no longer need to support those test options they do have.

The hope is that, in future, `full_chain_test.py` can be used to test new features and see the result in (at least) ODD and ITk environments.

The idea for this initial version is:
* `full_chain_test.py` exactly matches `full_chain_odd.py`
  * ODD configuration is the default
* `full_chain_test.py -A -M1 -N2` exactly matches `full_chain_itk.py`
  * `-A` selects the ATLAS ITk configuration
  * `-M1 -N2` (or `--gen-nvertices 1 --gen-nparticles 2`) changes to 2 particles per event from `full_chain_odd.py`'s default of 800 (`-M 200 -N 4`)
* `full_chain_test.py -G` is similar `ckf_tracks.py`
  * `-G` selects the generic detector configuration
  * does not exactly match the more rudimentary `ckf_tracks.py`, and doesn't try to reproduce seeding config.

Later, if this becomes a useful development test, we can harmonise the detail setup between ODD and ITk.

Also, do we need to support options from `full_chain_itk_Gbts.py` and `full_chain_odd_LRT.py`?

### CODE REVIEW

**Comment by andiwand** [comment]
Thinking longer term I believe these `full_chain_*.py` should all go away and be replaced with a physmon workflow. If that is not possible (for example ITk is not part of ACTS) it should be completely removed IMO.

If we cannot validate the output of these chains they are just another unmonitored script. To try new algorithms and configurations one can modify a standard chain and if that workflow solidifies one can add a physmon workflow for this.

**Comment by timadye** [comment]
We discussed this at some length at the Developers' meeting, with a variety of opinions.

> Thinking longer term I believe these `full_chain_*.py` should all go away and be replaced with a physmon workflow. If that is not possible (for example ITk is not part of ACTS) it should be completely removed IMO.

I think these serve different use cases from physmon, but also this new `full_chain_test.py` is different from the existing `full_chain_*.py` scripts. Maybe that could be clearer, eg. with a new name or location? Maybe the current location is best until we can simplify the other scripts.

`full_chain_itk.py` was initially intended as an *example* that people could use to help set up their own scripts, but it has developed into a test platform for new features, and rather obscures the simple use case. `full_chain_odd.py` also added command-line options.

`full_chain_test.py` is intended to take over the *interactive* testing uses from the other scripts. Later, we can simplify the other scripts back to proper examples.

There is a real need for a command to perform interactive testing with simple command-line options. The evidence being how these scripts keep popping up (and not just written by me 😄). That may not be the way everyone works, but many of us do. I used my private version of this script to do all the tests on your recent CKF PRs - and I hope that was useful. Having private versions of that script is really inconvenient as people have to develop them independently, and keep them up to date.

> If we cannot validate the output of these chains they are just another unmonitored script. To try new algorithms and configurations one can modify a standard chain and if that workflow solidifies one can add a physmon workflow for this.

Since this is a developer testing script, we'll have to provide it as-is with best-effort support. If it breaks when testing, then you fix it when you add/fix the feature you are testing.

I am thinking of adding a big disclaimer to the top of the script and in the help text, eg.

```This script is provided for interactive developer testing only. It is not intended (and not supported) for end user use, automated testing, and certainly should never be called in production. The Python API is the proper way to access the ActsExamples from scripts. The other Examples/Scripts are much better examples of how to do that. physmon in the CI is the proper way to do automated integration tests. This script is only for the case of interactive testing with one-off configuration specified by command-line options.```

**Comment by timadye** [comment]
If I understand you correctly, I think you might be confusing the purpose of this script, and what I understood was the original purpose of the existing scripts that I hope we can eventually restore.

`full_chain_odd.py` etc were originally supposed to be *simple examples* that users can take and modify for their own purposes. They have grown with the addition of inline or command-line options to provide different tests. I would like to remove this test functionality into a single script (`full_chain_test.py`) and restore the other `full_chain_*.py` to simple examples. I thought to do the `full_chain_odd.py` etc simplification in another PR, assuming people were happy using `full_chain_test.py`.

`full_chain_test.py` is intended for interactive developer testing. This can be done at the moment with `full_chain_odd.py`, but not so easily with `full_chain_itk.py`.

> IMO modifying a chain is easiest if it is not overloaded with 100 CLI flags so you can just drop things our and copy something in without wiring another flag that potentially conflicts with 10 others. So I would argue the proposed script is not a solution to give a template for later to be modified chains.

It's 32 flags at the moment, and most of them are generic flags for changing the simulated sample (eg. `--events 10 --ttbar-pu200`), the detector configuration (eg. `--itk --bf-constant`), the algorithms run (eg. `--seeding-algorithm Orthogonal --no-ckf`), and how the job is run (eg. `--output-dir test3 --loglevel DEBUG). None of these are for turning on and off particular details of the reconstruction, but rather setting up the particular test you want to run.

For most use cases, it would not be necessary to wire in another CLI flag to perform the test. But it is useful to test with different single particle momenta, or with ttbar PU200, to run with different numbers of events, to try with ODD or ITk, to send the output to different directories so as not to overwrite previous tests. Without CLI flags, doing more than one interactive test becomes difficult to manage.

Sometimes it might be useful to have a CLI flag to turn on and off a feature so one can run with and without the new feature. But that would be a temporary hack for that set of tests. I wondered whether it would be sometimes be useful to commit the new CLI flag to GitHub, but your comment convinces me that this would be a bad idea in the long term. So let's not do that.

**Comment by andiwand** [comment]
> If I understand you correctly, I think you might be confusing the purpose of this script, and what I understood was the original purpose of the existing scripts that I hope we can eventually restore.
> 
> `full_chain_odd.py` etc were originally supposed to be _simple examples_ that users can take and modify for their own purposes. They have grown with the addition of inline or command-line options to provide different tests. I would like to remove this test functionality into a single script (`full_chain_test.py`) and restore the other `full_chain_*.py` to simple examples. I thought to do the `full_chain_odd.py` etc simplification in another PR, assuming people were happy using `full_chain_test.py`.
> 
> `full_chain_test.py` is intended for interactive developer testing. This can be done at the moment with `full_chain_odd.py`, but not so easily with `full_chain_itk.py`.

I see that but what I cannot see is how the situation is improved by keeping `full_chain_odd.py` and `full_chain_itk.py` as they are in this PR. There is just another chain with numerous CLI flags and nobody knows what to start with.

IMO to move forward with this the PR should also include the proposed changes to the other chains.

> It's 32 flags at the moment, and most of them are generic flags for changing the simulated sample (eg. `--events 10 --ttbar-pu200`), the detector configuration (eg. `--itk --bf-constant`), the algorithms run (eg. `--seeding-algorithm Orthogonal --no-ckf`), and how the job is run (eg. `--output-dir test3 --loglevel DEBUG). None of these are for turning on and off particular details of the reconstruction, but rather setting up the particular test you want to run.

To me choosing a seeding algorithm and toggling the CKF is turning on and off particular details of the reconstruction. At the same time there are 3 ambi solvers to choose from. I don't think it is trivial to guarantee that all the combinations work (for example all seeders with/without CKF with ambi solver X).

This is where I think the script does not offer any benefit other than educational purposes, which is a valid one. It is way too complicated to wire in another flag because it can easily break the script with specific options.

**Comment by timadye** [comment]
> I see that but what I cannot see is how the situation is improved by keeping `full_chain_odd.py` and `full_chain_itk.py` as they are in this PR. There is just another chain with numerous CLI flags and nobody knows what to start with.

Those are useful as easy-to-read examples for how to write your own script.

> IMO to move forward with this the PR should also include the proposed changes to the other chains.

OK, I can make the simpler versions of these scripts and include it with this PR.

> To me choosing a seeding algorithm and toggling the CKF is turning on and off particular details of the reconstruction. At the same time there are 3 ambi solvers to choose from. I don't think it is trivial to guarantee that all the combinations work (for example all seeders with/without CKF with ambi solver X).

Specifying `--seeding-algorithm Orthogonal` is useful to test that algorithm. This option is mostly just passed onto `reconstruction.py`, so the complexity isn't here. Specifying `--no-ckf` (which disables the downstream ambi and vertexing) is useful if you are debugging the seeding and running the CKF just slows you down. Once you are done debugging, you should run again with the full chain to see the performance effect.

Your point may perhaps apply better to the `--simple-ckf` option. I can remove that if you think it would improve things.

As I said before, it isn't necessary to test all the options (or any). This is a developer tool. If something doesn't work for a developer, they can fix it. As I said in my proposed disclaimer, this should never be run in the CI, let alone production.

> This is where I think the script does not offer any benefit other than educational purposes, which is a valid one.

No, that is the purpose of the (simplified) `full_chain_odd.py`.

> It is way too complicated to wire in another flag because it can easily break the script with specific options.

As I said, wiring in another flag isn't the primary use case. If it's too complicated for someone, then they won't do it.

**Comment by paulgessinger** [comment]
I really don't understand how physmon can fail here...

**Comment by timadye** [comment]
> > IMO to move forward with this the PR should also include the proposed changes to the other chains.
>
> OK, I can make the simpler versions of these scripts and include it with this PR.

Simplifying `full_chain_odd.py` will mean that `test_examples.py` will need to swap to `full_chain_test.py`. I would prefer to leave that to a separate PR once this one is merged.

**Comment by timadye** [comment]
from the Dev meeting, @andiwand said that he expects #3850 will fix the physmon irreproducibility.

**Comment by paulgessinger** [comment]
@timadye that's merged now, so we should be good to go.

**Review by andiwand — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [a30ab3330174a4c44c76b54d9cfa12f7c364863f]
### :white_check_mark: All tests successful

|status|job|report|
|------|---|------|
|:green_circle: | [report_pull_request](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277241)||
|:green_circle: | [run_art_test: test_run4_acts_vertex_PU200](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277240)||
|:green_circle: | [run_art_test: test_run4_ttbar_PU200](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277239)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277238)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277237)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277236)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277235)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277234)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277233)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277232)||
|:green_circle: | [test_ActsDumpGeometryIdentifiers](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277231)||
|:green_circle: | [test_ActsCheckObjectCountsWorkflowHgtd](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277230)||
|:green_circle: | [test_ActsCheckObjectCountsCachedWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277229)||
|:green_circle: | [test_ActsCheckObjectCountsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277228)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277227)||
|:green_circle: | [test_ActsPersistifySeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277226)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277225)||
|:green_circle: | [test_ActsAnalogueClustering](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277224)||
|:green_circle: | [test_ActsWorkflowHeavyIons](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277223)||
|:green_circle: | [test_ActsWorkflowFastTracking](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277222)||
|:green_circle: | [test_ActsWorkflowCached](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277221)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277220)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277219)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277218)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277217)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277216)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277215)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277214)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277213)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277212)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277211)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277210)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277209)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277208)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277207)||
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46277206)||

**Pull request merged**
