### PR TITLE
docs: update how-to guide for (C)KF reconstruction

### PR DESCRIPTION
**Pull request by XiaocongAi**
This updates the how-to guide for (C)KF reconstruction following the recent splitting of event generation and fatras simulation etc.

### CODE REVIEW

**Review by msmk0 — CHANGES_REQUESTED** [review]
@XiaocongAi Thanks for catching this.

It seems that almost all of the how-to guides duplicate the information on how to generate a simulation dataset. I would suggest to remove those section altogether and just reference (ses [Sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-ref) to the Fatras guide in the `Prerequisites` section. Something along the lines of

```
Prerequisites
-----------------

Acts has to be build with ....

We assume that you have generated a simulation dataset as described in
:ref:`THE_TO_BE_CREATED_FATRAS_HOWTO_LABEL` that is available in
`<path/to/sim/dataset>`. A good example dataset would be e.g. a ttbar sample with pileup 200 ....
```

**Comment by msmk0** [comment]
@paulgessinger @XiaocongAi `chore` or `doc` as the title for documentation updates?

**Comment by paulgessinger** [comment]
I think it's `docs` following angular at least.

**Comment by XiaocongAi** [comment]
Hi @msmk0 , thank you for the suggestion. The duplication for the simulation how-to is removed via a ref. Could you have a look?

**Review by msmk0 — APPROVED** [review]
@XiaocongAi Thanks for updating this. Looks good.

**Pull request merged**
