### PR TITLE
Initial step fix

### PR DESCRIPTION
**Pull request by asalzburger**
This PR fixes a problem seen with sPhenix:

- the approach descriptor allowed for negative path solutions (overstepping)
- for approaching the surface this does not make sense, hence this PR disallows the negative path solution if presents and swaps with the positive path solution

It adds a UnitTest for to check the correct behaviour.

### CODE REVIEW

**Comment by asalzburger** [comment]
Hey @paulgessinger - this is the fix I would like to be part of v0.30.00, it's actually only a few lines.

**Comment by paulgessinger** [comment]
... and not having overstepping here is acceptable because we don't care if we're slightly behind the approach? Does this not have the potential to throw off the navigation?

**Comment by asalzburger** [comment]
> ... and not having overstepping here is acceptable because we don't care if we're slightly behind the approach? Does this not have the potential to throw off the navigation?

When you ask for `approachSurfaces(...)` then you are by definition before you reached the `Layer`, so there should be no case where you made a `Propagator::step(...)` that could have led to *overstepping*.

**Comment by paulgessinger** [comment]
Ok so because after having *approached an approach surface* the only thing you'll ever do is go to the corresponding layer, you'll be fine, navigation wise, because the approach surfaces is **before** the relevant layer in question. Ok I guess.

**Pull request merged**
