### PR TITLE
refactor!: Move MinimalSourceLink to tests (EDM rework 3b/4)

### PR DESCRIPTION
**Pull request by msmk0**
BREAKING CHANGE: The `MinimalSourceLink` is removed from the public interface.

Users are expected to provide their own concrete source link implementation. The provided `MinimalSourceLink` is a very rigid example implementation that only allows a narrow use case. It is intended to be used for tests and only used as such in the code base. The examples framework uses a different and completely independent source link type. To avoid confusion for users and clarify its purpose, the `MinimalSourceLink` is removed from the public interface, renamed to `TestSourceLink`, and moved to the common test helpers.

This PR must be merged after #513.

### CODE REVIEW

**Review by asalzburger — APPROVED** [review]
Looks good.

**Comment by asalzburger** [comment]
@msmk0 - can you rebase this one, to see the changes of 3b wrt 3a, please?

**Comment by asalzburger** [comment]
Ah, also - there seems to be a conflict..

**Comment by msmk0** [comment]
@asalzburger Rebased and ready to be reviewed.

**Review by asalzburger — APPROVED** [review]
Looks good, indeed.

**Comment by asalzburger** [comment]
I update the branch, with the include-what-you-use changes that went into master, and will merge when CI is successful.

**Pull request merged**
