### PR TITLE
fix: Output ROOT file closing on destruct

### PR DESCRIPTION
**Pull request by paulgessinger**
While I believe the writing should happen in `endRun`, I've seen
segfaults when ROOT's exit handler tries to close them and sees
corrupted memory. This PR should fix that for these two classes.

### CODE REVIEW

**Comment by AJPfleger** [comment]
Does this problem affect only these two classes? I am asking, because we use the same approach for some/all other writer-classes.

**Comment by paulgessinger** [comment]
We certainly could. I saw crashes for these two classes specifically, so those are the ones I touched for now.

**Review by AJPfleger — APPROVED** [review]
The changes look good to me, but I think we should do one of the following:
- Check and adapt the other writer-classes
- Open an Issue to not forget about ^ in the future

**Comment by AJPfleger** [comment]
Yes, [#881](https://github.com/acts-project/acts/issues/881) seems well suited.

**Pull request merged**
