### PR TITLE
feat: Vertexing mu scan and CI job that creates it

### PR DESCRIPTION
**Pull request by paulgessinger**
This PR adds a configuration + plotting script for this kind of plot produced by the CI:

vertexing

This currently runs on 25 events, but we might have to tune this to keep the runtime reasonable.

### CODE REVIEW

**Review by AJPfleger — APPROVED** [review]
lgtm

**Comment by paulgessinger** [comment]
I made mistake with where I put the output file. Need to fix that before merging.

**Comment by paulgessinger** [comment]
Ready now, can you reapprove @AJPfleger?

**Review by AJPfleger — APPROVED** [review]
lgtm
thanks for restricting the `$ rm` in the last commit.

**Pull request merged**
