### PR TITLE
ci: Change physmon PR determination

### PR DESCRIPTION
**Pull request by paulgessinger**
Tries to use an action to make determining the PR more robust. Kodiak updates the PR with a push, not a synchronize, so the report workflow did not run correctly.

### CODE REVIEW

**Review by benjaminhuth — APPROVED** [review]
Let's hope this solves this issue reliable!

**Comment by benjaminhuth** [comment]
Ah but the PR number job is failing @paulgessinger

**Comment by paulgessinger** [comment]
Ok @benjaminhuth, hopefully now it'll work.

**Comment by benjaminhuth** [comment]
Unfortunately the physmon job it still fails @paulgessinger

**Pull request closed without merging**
