### PR TITLE
refactor: make usage of vertex constraint more evident

### PR DESCRIPTION
**Pull request by felix-russo**
Removes intricate use of `constraint` in `AMVFinder`

### CODE REVIEW

**Review by andiwand — APPROVED** [review]
code looks fine but physmon seems to be degraded

**Comment by felix-russo** [comment]
> code looks fine but physmon seems to be degraded

Yes, I didn't find the time to investigate yet, will do so shortly!

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [6766fe83769431d63c77eb7401ec79d29029cc29]
### :white_check_mark: All tests successful

|status|job|
|------|---|
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33432330) |
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430447) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430446) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430445) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430444) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430443) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430442) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430441) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430440) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430439) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430438) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430437) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430436) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430435) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430433) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33430432) |

**Comment by felix-russo** [comment]
This should not break athena, I will investigate

**Comment by paulgessinger** [comment]
The changes seen in Athena seem pretty wide, I see taus, jets and muons being widely affected. Not sure about the scale yet.

**Comment by felix-russo** [comment]
Yeah this should not affect athena! I will hopefully find the time to investigate soon, but this is not at all ready

**Comment by paulgessinger** [comment]
This seems to change the chi2/ndf quite visibly:

https://acts-athena-outputs.web.cern.ch/test_data18_13TeV_1000evt/pulls/2529/dcube_expert_last/

image

image

**Pull request closed without merging**
