### PR TITLE
refactor: Brush over new detector geometry part 1

### PR DESCRIPTION
**Pull request by andiwand**
- consistent pass by value
- reformat documentation

pull changes out of https://github.com/acts-project/acts/pull/2214

### CODE REVIEW

**Review by asalzburger — APPROVED** [review]
Looks mostly cosmetics, fine with me.

**Comment by paulgessinger** [comment]
Isn't it usually safer to use constant refs, because that decreases the likelihood that the caller accidentally copies? Especially with vector arguments I've seen that happen for sure. Might not be super relevant for the geometry construction.

**Comment by andiwand** [comment]
> Isn't it usually safer to use constant refs, because that decreases the likelihood that the caller accidentally copies? Especially with vector arguments I've seen that happen for sure. Might not be super relevant for the geometry construction.

Not sure - you lose the ability to move the vector to where it belongs and will always end up with a copy. clang tidy will check the intermediate steps so should not be forgotten. The caller might forget it but then you have a single copy as before

**Comment by paulgessinger** [comment]
> > Isn't it usually safer to use constant refs, because that decreases the likelihood that the caller accidentally copies? Especially with vector arguments I've seen that happen for sure. Might not be super relevant for the geometry construction.
> 
> 
> 
> Not sure - you lose the ability to move the vector to where it belongs and will always end up with a copy. clang tidy will check the intermediate steps so should not be forgotten. The caller might forget it but then you have a single copy as before

Fair enough. Maybe we should take some extra care for vectors that are large or contain very complex objects, but that doesn't seem to be the case here anyway.

**Comment by asalzburger** [comment]
Looks like we have an agreement here, I see it as Andreas does, the PR makes this consistent and hence allows copy or move, whatever is better.

**Review by asalzburger — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/5931891)!

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203825) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203824) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203823) |
|:red_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203822) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsTrkSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203821) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203820) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203819) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203818) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203817) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203816) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203815) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203814) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203813) |
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203812) |
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203811) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203810) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/31203809) |

**Comment by CarloVarni** [comment]
I believe the failure is coming from Athena and is un-related to this PR

**Comment by asalzburger** [comment]
None of this code is running in Athena already.

**Pull request merged**
