### PR TITLE
Add track EDM visualization

### PR DESCRIPTION
**Pull request by XiaocongAi**
This PR add the visualization for a track to show optionally the surface (yellow color), calibrated measurement (orange color), predicted (light blue color)/filtered (dark blue color)/smoothed (green color) track parameters at each track state.

To get a realistic fitted track,  the test first construct a detector with six plane surfaces, then create measurements and construct KalmanFitter to perform the fit, and finally draw the fitted track as below:
image

### CODE REVIEW

**Comment by XiaocongAi** [comment]
The zoomed plots: 

image

image

**Comment by asalzburger** [comment]
I override the patch, since the overall has no change.

**Comment by asalzburger** [comment]
To avoid these overlaps seen on the last picture, one could stack the out of plane prescriptions, right?

**Comment by XiaocongAi** [comment]
@asalzburger , right. We could use different out of plane factors for them. Let me change this.

**Comment by XiaocongAi** [comment]
@asalzburger , the plot looks much better now. :smiley:

**Pull request merged**
