### PR TITLE
Add a CI job that builds the CUDA plugin

### PR DESCRIPTION
**Pull request by paulgessinger**
Build off of a test image I created based on Ubuntu18.04. It starts from the nvidia image with cuda 10.2, and then adds our dependencies on top.

### CODE REVIEW

**Comment by paulgessinger** [comment]
This now gets a [build failure](https://github.com/paulgessinger/acts/runs/926579791?check_suite_focus=true) that looks like 

```console
FAILED: Tests/UnitTests/Plugins/Cuda/Seeding/CMakeFiles/SeedfinderCudaTest.dir/SeedfinderCudaTest.cpp.o 
/usr/bin/g++-8   -I../Plugins/Cuda/include -I/usr/local/cuda/targets/x86_64-linux/include -I../Core/include -ICore -isystem /usr/local/include/eigen3 -Werror -Wall -Wextra -Wpedantic -Wshadow -Wunused-local-typedefs -O3 -DNDEBUG    -std=gnu++17 -MD -MT Tests/UnitTests/Plugins/Cuda/Seeding/CMakeFiles/SeedfinderCudaTest.dir/SeedfinderCudaTest.cpp.o -MF Tests/UnitTests/Plugins/Cuda/Seeding/CMakeFiles/SeedfinderCudaTest.dir/SeedfinderCudaTest.cpp.o.d -o Tests/UnitTests/Plugins/Cuda/Seeding/CMakeFiles/SeedfinderCudaTest.dir/SeedfinderCudaTest.cpp.o -c ../Tests/UnitTests/Plugins/Cuda/Seeding/SeedfinderCudaTest.cpp
In file included from ../Tests/UnitTests/Plugins/Cuda/Seeding/SeedfinderCudaTest.cpp:9:
../Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp:30:7: error: 'Seedfinder' is not a class template
 class Seedfinder<external_spacepoint_t, Acts::Cuda> {
       ^~~~~~~~~~
../Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp:42:64: error: wrong number of template arguments (2, should be 1)
   Seedfinder(const Seedfinder<external_spacepoint_t, Acts::Cuda>&) = delete;
                                                                ^
../Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp:30:51: note: provided for 'template<class external_spacepoint_t> class Acts::Seedfinder'
 class Seedfinder<external_spacepoint_t, Acts::Cuda> {
                                                   ^
../Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp:43:47: error: wrong number of template arguments (2, should be 1)
   Seedfinder<external_spacepoint_t, Acts::Cuda>& operator=(
                                               ^
...
```

@beomki-yeo any idea what causes this?

**Comment by paulgessinger** [comment]
Or maybe @krasznaa would have an idea?

**Comment by krasznaa** [comment]
Hi Paul,

As I wrote in https://github.com/acts-project/acts/pull/353#issuecomment-665021674, to get Beomki's code just to compile and run, I had to make all the following changes in it:

```diff
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp b/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp
index 85ef5eaff..8a82e7992 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp
@@ -14,6 +14,7 @@
 #include "Acts/Seeding/InternalSpacePoint.hpp"
 #include "Acts/Seeding/SeedFilter.hpp"
 #include "Acts/Seeding/SeedfinderConfig.hpp"
+#include "Acts/Seeding/Seedfinder.hpp"
 
 #include <array>
 #include <list>
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuMatrix.hpp b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuMatrix.hpp
index 85deb15dd..1fea29b51 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuMatrix.hpp
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuMatrix.hpp
@@ -47,7 +47,7 @@ class CpuMatrix {
   ~CpuMatrix() {
     if (!m_pinned) {
       delete m_hostPtr;
-    } else if (m_pinned) {
+    } else if (m_pinned && m_hostPtr) {
       cudaFreeHost(m_hostPtr);
     }
   }
@@ -75,7 +75,7 @@ class CpuMatrix {
   void zeros() { memset(m_hostPtr, 0, m_size * sizeof(var_t)); }
 
  private:
-  var_t* m_hostPtr;
+  var_t* m_hostPtr = nullptr;
   size_t m_nCols;
   size_t m_nRows;
   size_t m_size;
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuScalar.hpp b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuScalar.hpp
index c0ed7c922..1c441f9b5 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuScalar.hpp
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuScalar.hpp
@@ -41,7 +41,7 @@ class CpuScalar {
   ~CpuScalar() {
     if (!m_pinned) {
       delete m_hostPtr;
-    } else if (m_pinned) {
+    } else if (m_pinned && m_hostPtr) {
       cudaFreeHost(m_hostPtr);
     }
   }
@@ -51,7 +51,7 @@ class CpuScalar {
   void Set(var_t val) { m_hostPtr[0] = val; }
 
  private:
-  var_t* m_hostPtr;
+  var_t* m_hostPtr = nullptr;
   size_t m_size;
   bool m_pinned;
 };
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuVector.hpp b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuVector.hpp
index 231394f51..7c85af6f4 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuVector.hpp
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CpuVector.hpp
@@ -10,6 +10,8 @@
 
 #include "Acts/Plugins/Cuda/Utilities/CudaVector.cu"
 
+#include <cstring>
+
 namespace Acts {
 
 template <typename var_t>
@@ -44,7 +46,7 @@ class CpuVector {
   ~CpuVector() {
     if (!m_pinned) {
       delete m_hostPtr;
-    } else if (m_pinned) {
+    } else if (m_pinned && m_hostPtr) {
       cudaFreeHost(m_hostPtr);
     }
   }
@@ -66,7 +68,7 @@ class CpuVector {
   void zeros() { memset(m_hostPtr, 0, m_size * sizeof(var_t)); }
 
  private:
-  var_t* m_hostPtr;
+  var_t* m_hostPtr = nullptr;
   size_t m_size;
   bool m_pinned;
 };
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaMatrix.cu b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaMatrix.cu
index 521a36cf5..4c87025bd 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaMatrix.cu
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaMatrix.cu
@@ -55,7 +55,7 @@ public:
   }
   
   ~CudaMatrix(){
-    cudaFree(m_devPtr);
+    if(m_devPtr) cudaFree(m_devPtr);
   }
 
   var_t* get(size_t row=0, size_t col=0){
@@ -76,7 +76,7 @@ public:
   }
   
 private:
-  var_t* m_devPtr; 
+  var_t* m_devPtr = nullptr; 
   size_t m_nCols;
   size_t m_nRows;
   size_t m_size;
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaVector.cu b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaVector.cu
index 7ec682db6..07637f5d3 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaVector.cu
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Utilities/CudaVector.cu
@@ -43,7 +43,7 @@ public:
   }
   
   ~CudaVector(){ 
-    cudaFree(m_devPtr); 
+    if(m_devPtr) cudaFree(m_devPtr); 
   }
   
   var_t* get(size_t offset=0) { return m_devPtr+offset; }
@@ -60,7 +60,7 @@ public:
   }
   
 private:
-  var_t* m_devPtr; 
+  var_t* m_devPtr = nullptr; 
   size_t m_size;
 };
 }
diff --git a/Plugins/Cuda/src/Seeding/Kernels.cu b/Plugins/Cuda/src/Seeding/Kernels.cu
index 15244c53b..6148093eb 100644
--- a/Plugins/Cuda/src/Seeding/Kernels.cu
+++ b/Plugins/Cuda/src/Seeding/Kernels.cu
@@ -101,7 +101,9 @@ namespace Acts{
                     int*  tmpBcompIndex,
                     int*  TcompIndex,
                     int*  tmpTcompIndex){
-    
+    if (grid.x == 0) {
+      return;
+    }
     //int sharedMemSize = (2*sizeof(int))*block.x + 2*sizeof(int);
     int sharedMemSize = 2*sizeof(int);
     
@@ -145,6 +147,9 @@ namespace Acts{
                            float* spTcompMatPerSpM,
                            float* circTcompMatPerSpM
                            ){
+    if (grid.x == 0) {
+      return;
+    }
     int sharedMemSize = sizeof(float)*6;
     cuTransformCoordinate<<< grid, block, sharedMemSize >>>(
                                      nSpM,
@@ -196,6 +201,9 @@ namespace Acts{
                     Triplet* TripletsPerSpM,
                     cudaStream_t* stream
                     ){    
+    if (grid.x == 0) {
+      return;
+    }
     int sharedMemSize = sizeof(Triplet)*(*nTrplPerSpBLimit_cpu);
     sharedMemSize += sizeof(float)*(*compatSeedLimit_cpu); 
     sharedMemSize += sizeof(int);
```

I did come across this build error myself as well. I solved it with:

```diff
diff --git a/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp b/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp
index 85ef5eaff..8a82e7992 100644
--- a/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp
+++ b/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.hpp
@@ -14,6 +14,7 @@
 #include "Acts/Seeding/InternalSpacePoint.hpp"
 #include "Acts/Seeding/SeedFilter.hpp"
 #include "Acts/Seeding/SeedfinderConfig.hpp"
+#include "Acts/Seeding/Seedfinder.hpp"
 
 #include <array>
 #include <list>
```

Since without that include the compiler doesn't see the original template, the one that the CUDA implementation specialises. (And as I wrote in my PR, I just don't see any value in implementing the CUDA seedfinder as a specialisation of the CPU one and not as a completely separate class. But c'est la vie.)

Cheers,
        Attila

**Comment by paulgessinger** [comment]
I didn't make that connection. Trying this now.

**Comment by paulgessinger** [comment]
Another question: I only build the core lib and the CUDA plugin in this new job here, since the rest of the build would be more or less redundant w.r.t. to the ubuntu20.04 build. Any opinions on that?

**Comment by krasznaa** [comment]
In principle you should only build the CUDA specific (test) executables. (`SeedfinderCudaTest`, `ActsUnitTestCuda`, `ActsUnitTestCudaMostSimplified`)
  - https://github.com/acts-project/acts/blob/master/Tests/UnitTests/Plugins/Cuda/Seeding/CMakeLists.txt
  - https://github.com/acts-project/acts/blob/master/Tests/UnitTests/Plugins/Cuda/Utilities/CMakeLists.txt

Everything else should be the same as in the "standard" build. (And these will trigger the build of everything that they need, including all the existing CUDA code.)

**Comment by paulgessinger** [comment]
Yeah, the core lib is build always, and I enable the unit test flag, which will cause these test executables (and their dependencies) to be build. I guess that's what we want here.

**Comment by paulgessinger** [comment]
Ok the plugin builds (with warnings), the test run fails afterwards. I guess this is expected as the job runner does not have a CUDA device, is that correct?

**Comment by krasznaa** [comment]
That's correct. The code (currently) doesn't know what to do when trying to execute on a host without an NVidia device. Later on we may want to correct this, but I'm afraid for now you should only do compilation checks in the CI.

**Comment by paulgessinger** [comment]
Ok this seems to work now, with the `v4` CI images. This is good to go from my side.

**Comment by krasznaa** [comment]
I think you guys should just go ahead with this. :+1:

**Comment by paulgessinger** [comment]
@msmk0, @asalzburger could you approve?

**Comment by asalzburger** [comment]
As discussed in the developers meeting - merging this one.

**Pull request merged**
