### PR TITLE
feat: full_chain_itk.py uses eta-dependent cuts

### PR DESCRIPTION
**Pull request by timadye**
* `addCKFTracks` can now specify a `trackSelectorConfig = list(TrackSelectorConfig)` for eta-dependent cuts, with binning specified in `absEta[1]`. `addCKFTracks()` can be called with any of:
  1. `trackSelectorConfig = (TrackSelectorConfig(), TrackSelectorConfig(), ...)`. See `full_chain_itk.py` for an example.
  2. `trackSelectorConfig = TrackSelectorConfig()`. Can also be specified as `TrackSelectorConfig()` as an non-kwarg. See `full_chain_odd.py` for an example.
  3. `trackSelectorConfig = None` (default)
* `TrackSelectorConfig` includes new cuts `maxHoles`, `maxOutliers`, `maxSharedHits`, and `maxChi2`.
* `full_chain_itk.py` now uses Athena's ITk track selections.

### CODE REVIEW

**Comment by timadye** [comment]
currently pybind doesn't allow the creation of a `TrackSelector` with `EtaBinnedConfig`

**Comment by timadye** [comment]
> I can't get it to create a `TrackSelector` with `EtaBinnedConfig`, rather than the usual `Config`.

This was because `TrackFindingAlgorithm::Config` only stored a `Acts::TrackSelector::Config`. The last commit changed it to a `std::variant<Acts::TrackSelector::Config, Acts::TrackSelector::EtaBinnedConfig>`, so either can be specified.

Now it works. `addCKFTracks()` can be called with any of:
1. `trackSelectorConfig = (TrackSelectorConfig(), TrackSelectorConfig(), ...)`. See `full_chain_itk.py` for an example.
2. `trackSelectorConfig = TrackSelectorConfig()`. Can also be specified as `TrackSelectorConfig()` as an non-kwarg. See `full_chain_odd.py` for an example.
3. `trackSelectorConfig = None` (default)

**Review by andiwand — APPROVED** [review]
lgtm!

**Comment by acts-project-service** [comment]
## :white_check_mark: Athena integration test results [4e25aa214953a5555ea9a087323abe3b32a5411c]
### :white_check_mark: All tests successful

|status|job|report|
|------|---|------|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931646)||
|:green_circle: | [test_ActsEFTrackFit](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931645)||
|:green_circle: | [test_ActsBenchmarkWithSpot](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931644)||
|:green_circle: | [test_ActsConversionWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931643)||
|:green_circle: | [test_ActsWorkflow](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931642)||
|:green_circle: | [test_ActsValidateAmbiguityResolution](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931641)||
|:green_circle: | [test_ActsValidateResolvedTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931640)||
|:green_circle: | [test_ActsValidateTracks](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931639)||
|:green_circle: | [test_ActsValidateActsCoreSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931638)||
|:green_circle: | [test_ActsValidateActsSpacePoints](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931637)||
|:green_circle: | [test_ActsValidateSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931636)||
|:green_circle: | [test_ActsValidateOrthogonalSeeds](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931635)||
|:green_circle: | [test_ActsValidateClusters](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931634)||
|:green_circle: | [test_ActsPersistifyEDM](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931633)||
|:green_circle: | [test_ActsGSFRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931632)||
|:green_circle: | [test_ActsKfRefitting](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931631)||
|:green_circle: | [test_ActsExtrapolationAlgTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931630)||
|:green_circle: | [test_ActsITkTest](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931629)||
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931628)||
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931627)||
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931626)||
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931625)||
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931624)||
|:green_circle: | [run_art_test: test_data18_13TeV_1000evt](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931623)||
|:green_circle: | [run_art_test: test_ttbarPU40_reco](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35931622)||

**Comment by timadye** [comment]
Using the Athena ITk track selections now in `full_chain_itk.py` gives much better tracking efficiency for ttbar + PU200:
trksel_eff
at the expense of some extra duplicates:
trksel_dup
The job took ~25% longer, but I had some problems with the machine at the time, so it may have been unrelated.

**Pull request merged**
