### PR TITLE
feat: Prototype full-chain sim+reco for Generic and ATLAS detectors

### PR DESCRIPTION
**Pull request by timadye**
* Implemented in `ckf_tracks.py`, which previously worked just for the Generic Detector. The changes should be compatible with existing tests using `ckf_tracks.py`.
* Config can be specified with command-line options.
* Use `ckf_tracks.py --atlas` to select options to load config from `acts-detector-examples` (get in touch if you don't have this).
* Requires #1095 to use with `--atlas` and without `--build-itk-geometry`.

```
usage: ckf_tracks.py [-h] [-l LOGLEVEL] [-n EVENTS] [--gen-nparticles GEN_NPARTICLES] [--gen-nvertices GEN_NVERTICES] [--generic-detector] [-a] [-g GEO_DIR] [-i INPUT_PARTICLES] [-o OUTPUT_DIR] [--bf-constant-tesla BF_CONSTANT_TESLA]
                     [--output-trajectories-csv] [--no-material] [--mat-input-file MAT_INPUT_FILE] [--ckf-truth-smeared-seeds] [--ckf-truth-estimated-seeds] [--geo-selection-config-file GEO_SELECTION_CONFIG_FILE] [--build-itk-geometry]
                     [--geo-tgeo-jsonconfig GEO_TGEO_JSONCONFIG] [--geo-tgeo-filename GEO_TGEO_FILENAME] [--digi-config-file DIGI_CONFIG_FILE]

Example script to run CKF tracking

optional arguments:
  -h, --help            show this help message and exit
  -l LOGLEVEL, --loglevel LOGLEVEL
                        The output log level. Please set the wished number (0 = VERBOSE, 1 = DEBUG, 2 = INFO, 3 = WARNING, 4 = ERROR, 5 = FATAL). (default: 2)
  -n EVENTS, --events EVENTS
                        The number of events to process. (default: 100)
  --gen-nparticles GEN_NPARTICLES
                        Number of generated particles per event. (default: 4)
  --gen-nvertices GEN_NVERTICES
                        Number of generated vertices. (default: 2)
  --generic-detector    Setup Generic Detector. (default: True)
  -a, --atlas           Setup ATLAS Detector using the ITk standalone geometry specified in --geo-dir. Get in touch if you don't have this. (default: False)
  -g GEO_DIR, --geo-dir GEO_DIR
                        Input directory containing geometry. (default: None)
  -i INPUT_PARTICLES, --input-particles INPUT_PARTICLES
                        Input particles path. (default: None)
  -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Directory to write outputs to. (default: /mercury/data2/adye/acts/run-211103)
  --bf-constant-tesla BF_CONSTANT_TESLA
                        Set a constant magnetic field vector in Tesla. (default: 2)
  --output-trajectories-csv
                        output trajectories to CSV files (default: False)
  --no-material         Decorate material to the geometry (--atlas or --build-itk-geometry only) (default: False)
  --mat-input-file MAT_INPUT_FILE
                        Name of the material map input file, supported: '.json', '.cbor' or '.root'. (default: None)
  --ckf-truth-smeared-seeds
                        Use track parameters smeared from truth particles for steering CKF (default: False)
  --ckf-truth-estimated-seeds
                        Use track parameters estimated from truth tracks for steering CKF (default: False)
  --geo-selection-config-file GEO_SELECTION_CONFIG_FILE
                        Json file for space point geometry selection (default: None)
  --build-itk-geometry  use itk.buildITkGeometry to create TGeo geometry (skips --geo-tgeo-*, defaults --mat-input-file) (default: False)
  --geo-tgeo-jsonconfig GEO_TGEO_JSONCONFIG
                        TGeo Json config file name (--atlas only). (default: None)
  --geo-tgeo-filename GEO_TGEO_FILENAME
                        TGeo Root file name (--atlas only). (default: None)
  --digi-config-file DIGI_CONFIG_FILE
                        Configuration (.json) file for digitization description (default: None)
```

### CODE REVIEW

**Comment by timadye** [comment]
This was something I was playing with to run the full chain from Python. @asalzburger and others are doing something similar, so it this will likely be superseded by someting better. At the very least, I should merge in #1093.

**Comment by paulgessinger** [comment]
Thanks @timadye!

I wonder if it would make sense to rename your script here to something else, like `full_chain.py` or something, and keep `ckf_tracks.py` as a more of a *minimal* example? (I know it's not that minimal). Maybe fewer customization points, it's easier to read the script and figure out what's actually going on.

What do you think?

**Comment by timadye** [comment]
> I wonder if it would make sense to rename your script here to something else, like `full_chain.py` or something, and keep `ckf_tracks.py` as more of a _minimal_ example? (I know it's not that minimal). Maybe fewer customization points, it's easier to read the script and figure out what's actually going on.

Yes, it's not so useful as an example with all this extra stuff. On the other hand, just renaming to `full_chain.py` means lots of duplicated (Python) code. I discussed with @asalzburger, and opened #1098 to follow up with some ideas.

**Comment by timadye** [comment]
This is still useful to demonstrate the desired functionality, but doesn't need to stay as an open PR.

**Pull request closed without merging**
