### PR TITLE
refactor: SSS xyzCoordinateCheck calculations

### PR DESCRIPTION
**Pull request by LuisFelipeCoelho**
This PR reduces duplicated calculations in `xyzCoordinateCheck` function.

### CODE REVIEW

**Review by CarloVarni — APPROVED** [review]

**Comment by LuisFelipeCoelho** [comment]
I believe that this could be further optimised. Maybe `topHalfStripLength * topStripDirection` and `bottomHalfStripLength * bottomStripDirection` could be calculated only once per event

**Comment by CarloVarni** [comment]
> I believe that this could be further optimised. Maybe `topHalfStripLength * topStripDirection` and `bottomHalfStripLength * bottomStripDirection` could be calculated only once per event (but for every SP)

Agree! These values can be store in the 'spacePointData' object. In my tests I noticed that these values are calculated anyway for ~95% of the input space points.. so no worries about computing them for all space points. 

Do you wanna do it in another PR or in this one?

**Comment by CarloVarni** [comment]
If they are added to the spacePointData then this Pr will become a breaking one

**Comment by LuisFelipeCoelho** [comment]
I see, if they are calculated for ~95% of the input space points we should do that. I can make a follow up PR to this one

**Pull request merged**
