### PR TITLE
refactor: Make Detectors constructible without boost po

### PR DESCRIPTION
**Pull request by paulgessinger**
Adds an overload to the detector's `finalize()` which accepts a newly
added `Config` object. The previous overload that takes boost program
options constructs such a `Config` object and forwards to the other
overload. This allows construction of the detector directly, with out
program options.

Additionally, the defaults for configuration values are harmonized, the
canonical source is now the `Config` objects, but I tried to have the po
versions consistents.

Currently this only ports
 - `AlignedDetector`
 - `GenericDetector`
 - `DD4hepDetector`

I think `TGeoDetector` should definitely be added.
@asalzburger do you think I anything else is important?

### CODE REVIEW

**Comment by asalzburger** [comment]
Hi @paulgessinger - `TGeoDetector` is unavoidable as it is heavily used, but then we can leave it.

**Review by asalzburger — APPROVED** [review]

**Comment by paulgessinger** [comment]
I'll add the TGeo detector tomorrow.

**Comment by paulgessinger** [comment]
I will add the TGeoDetector.

**Comment by paulgessinger** [comment]
Ok. `TGeoDetector` added. This also rationalizes the way the various TGeo helper functions were spread around the code. They should now all be located in the `TGeoDetector` files.

I briefly checked with help from @niermann999 that the ITk TGeo input seems to produce the same number of layers as was the case before the change, and from checking a few obj files and test propagation, the geometry seems to be ok.

image

**Comment by paulgessinger** [comment]
@asalzburger could you have another look and potentially reapprove?

**Review by asalzburger — APPROVED** [review]

**Pull request merged**
