### PR TITLE
feat: Adding inner and outer tube covers for disc approach descriptor

### PR DESCRIPTION
**Pull request by noemina**
This allows to fix propagation problems seen in the inclined section of the ITk tracking geometry.

FYI: @timadye @niermann999 @paulgessinger @asalzburger

### CODE REVIEW

**Comment by paulgessinger** [comment]
I post here the two diagnostics plots from @noemina for documentation.

image_2022_03_09T16_05_48_514Z
image_2022_03_09T16_14_27_554Z

**Comment by noemina** [comment]
Failures are expected as this change affects the construction of disc layers.

**Comment by paulgessinger** [comment]
At least the CKF histograms seem to be identical for the ODD (that's all I have implemented right now):
[ckf.html.gz](https://github.com/acts-project/acts/files/8224592/ckf.html.gz)

**Review by asalzburger — APPROVED** [review]
Looks ok to me.

**Comment by paulgessinger** [comment]
I think the CI failures might have been transient due to GitHub's outage yesterday.

**Comment by timadye** [comment]
The failure seems to be due to changes in the root file hashes. Those tests are for the generic detector. Clearly this will change the ITk reco output. Could it also change the generic detector?

**Comment by paulgessinger** [comment]
Very likely, yes. In principle it's ok if the files change, we should just do some sanity checks that everything looks reasonable.

**Pull request merged**
