### PR TITLE
chore: Ignore issues labeled bug in stale bot

### PR DESCRIPTION
**Pull request by paulgessinger**

### CODE REVIEW

**Comment by HadrienG2** [comment]
Note to reviewers: while this prevents auto-closing bugs, it also means that the "Stale" label will stop being usable as a warning that a bug has been opened for a long time and may not be valid anymore.

For this purpose, alternatives to stalebot such as explicitly searching for bugs older than N days will need to be used.

**Comment by paulgessinger** [comment]
Alternatively, we can also disable the auto closing, and keep the stale label, if that could help us to regular review of open issues. What do you think @HadrienG2?

**Comment by HadrienG2** [comment]
Since @robertlangenberg would be the one doing the manual work as the current meeting chair and seemed to enjoy having a stale label for this purpose, I think he should have the final word.

Personally I would tend to prefer having just the filter query for e-mail traffic trauma reasons, but on a rational level I know that the e-mail traffic associated to stale issues should become much more reasonable in the long run if we stick with the freshly introduced regular issue triage routine during our weekly meetings.

**Comment by robertlangenberg** [comment]
I would also extend the time until closure, 45 days from opening to auto-closing an issue (30days until stale + 15 days until closing, right?) is really not that much. If the number of tickets increases, well, that's life, and it hopefully won't matter that things get more crowded if we go over issues regularly in the meeting. How about 30 until stale and another 30 until auto closing? that would also prevent stuff from being auto closed if we look at stale labels less than every other week.

**Comment by paulgessinger** [comment]
Ok, I changed this to 30 days until marked stale and then 30 days until close. Ok @robertlangenberg?

**Comment by robertlangenberg** [comment]
sounds good, merging now

**Comment by paulgessinger** [comment]
Hm, but would we not want to include them to support evaluation in the meeting? I feel like Bug is somewhat clear in what it means, but **anything** can be long term in principle.

**Comment by paulgessinger** [comment]
This better @robertlangenberg ?

**Review by robertlangenberg — APPROVED** [review]
Thanks Paul

**Pull request merged**
