### PR TITLE
feat: Perform the Greedy Solver after the ML Solver

### PR DESCRIPTION
**Pull request by Corentin-Allaire**
This PR modify the odd full chain to call the Greedy solver on the output of the MLSolver. This has been tested on ttbar mu=200 PU and removes almost all the remaining duplicates at almost no cost in term of efficiency and speed.

This PR also change the full chain default back to mu=200 and the seeding range to match the  ODD eta range.

### CODE REVIEW

**Review by andiwand — APPROVED** [review]
lgtm!

**Comment by andiwand** [comment]
this requires some reference file changes

**Comment by Corentin-Allaire** [comment]
> this requires some reference file changes

Ah yes, I forgot about that. I am on it

**Review by andiwand — APPROVED** [review]

**Comment by acts-project-service** [comment]
## :red_circle: Athena integration test results
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32320013) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6170152)!

**Pull request merged**
